@ifset JA  @c ----------- v -----------  JA  -*- tab-width: 8 -*-
@node tagsrch.txt, , , 目次
@unnumbered タグと特別な検索
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
*tagsrch.txt*   For Vim version 8.1.  Last change: 2019 Jun 10


		  VIM REFERENCE MANUAL    by Bram Moolenaar
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@verbatim
*tagsrch.txt*   For Vim バージョン 8.1.  Last change: 2019 Jun 10


		  VIMリファレンスマニュアル    by Bram Moolenaar
@end verbatim
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
Tags and special searches				*tags-and-searches*

See section |29.1| of the user manual for an introduction.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{tags-and-searches}
@cindex tags-and-searches
タグと特別な検索

初めにユーザーマニュアルのセクション |@ref{29.1}| を参照すること。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
1. Jump to a tag		|tag-commands|
2. Tag stack			|tag-stack|
3. Tag match list		|tag-matchlist|
4. Tags details			|tag-details|
5. Tags file format		|tags-file-format|
6. Include file searches	|include-search|
7. Using 'tagfunc'		|tag-function|
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@multitable @columnfractions .5 .5
@item 1. タグへのジャンプ @tab |@ref{tag-commands}|
@item 2. タグスタック @tab |@ref{tag-stack}|
@item 3. タグマッチリスト @tab |@ref{tag-matchlist}|
@item 4. タグの詳細 @tab |@ref{tag-details}|
@item 5. タグファイルの書式 @tab |@ref{tags-file-format}|
@item 6. インクルードファイルの検索 @tab |@ref{include-search}|
@item 7. '@option{tagfunc}' を使う @tab |@ref{tag-function}|
@end multitable
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
==============================================================================
1. Jump to a tag					*tag-commands*
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{tag-commands}
@cindex tag-commands
@cindex タグへのジャンプ
@section 1. タグへのジャンプ
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*tag* *tags*
A tag is an identifier that appears in a "tags" file.  It is a sort of label
that can be jumped to.  For example: In C programs each function name can be
used as a tag.  The "tags" file has to be generated by a program like ctags,
before the tag commands can be used.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{tag}
@anchor{tags}
@cindex tag
@cindex tags
タグとは "tags" ファイルに現われる識別子である。タグはラベルのようなものであり、そこにジャンプすることができる。例えば: C のプログラムではそれぞれの関数名をタグとして使うことができる。タグ機能を使う前には、ctags のようなプログラムによって "tags" ファイルを生成しなければならない。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
With the ":tag" command the cursor will be positioned on the tag.  With the
CTRL-] command, the keyword on which the cursor is standing is used as the
tag.  If the cursor is not on a keyword, the first keyword to the right of the
cursor is used.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
":tag" コマンドはカーソルをタグ上に移動する。@command{CTRL-]} コマンドはカーソルの下にあるキーワードをタグとして使用する。もしカーソルがキーワード上になければ、カーソル位置から右側で最初に現れるキーワードを使用する。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
The ":tag" command works very well for C programs.  If you see a call to a
function and wonder what that function does, position the cursor inside of the
function name and hit CTRL-].  This will bring you to the function definition.
An easy way back is with the CTRL-T command.  Also read about the tag stack
below.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
":tag" コマンドはCプログラムでよく機能する。もし関数呼び出しを見つけた時にその関数が何をするのか疑問に思ったら、カーソルを関数名の上に置いて @kbd{CTRL-]} を叩けばよい。これで関数定義に導いてもらえるだろう。簡単に戻る方法は @command{CTRL-T} コマンドを使うことである。後述するタグスタックについても読むとよい。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
						*:ta* *:tag* *E426* *E429*
:[count]ta[g][!] {name}
			Jump to the definition of {name}, using the
			information in the tags file(s).  Put {name} in the
			tag stack.  See |tag-!| for [!].
			{name} can be a regexp pattern, see |tag-regexp|.
			When there are several matching tags for {name}, jump
			to the [count] one.  When [count] is omitted the
			first one is jumped to. See |tag-matchlist| for
			jumping to other matching tags.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@table @asis
@anchor{:ta}
@anchor{:tag}
@anchor{E426}
@anchor{E429}
@pindex :ta
@pindex :tag
@erindex E426
@erindex E429
@item :[count]ta[g][!] @{name@}
tags ファイル内の情報を用いて、@{name@} の定義へジャンプする。@{name@} はタグスタックに積まれる。[!] については |@ref{tag-!}| を参照。

@{name@} は正規表現を使用できる。|@ref{tag-regexp}| を参照。

@{name@} に対してマッチするタグが複数ある場合、[count] 番目のタグへジャンプする。[count] が指定されないときは最初のタグへジャンプする。他のマッチするタグへジャンプするには |@ref{tag-matchlist}| を参照。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
g<LeftMouse>						*g<LeftMouse>*
<C-LeftMouse>					*<C-LeftMouse>* *CTRL-]*
CTRL-]			Jump to the definition of the keyword under the
			cursor.  Same as ":tag {name}", where {name} is the
			keyword under or after cursor.
			When there are several matching tags for {name}, jump
			to the [count] one.  When no [count] is given the
			first one is jumped to. See |tag-matchlist| for
			jumping to other matching tags.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{g<LeftMouse>}
@anchor{<C-LeftMouse>}
@anchor{CTRL-]}
@kindex g<LeftMouse>
@kindex <C-LeftMouse>
@kindex CTRL-]
@item g<LeftMouse> または
@itemx <C-LeftMouse> または
@itemx @kbd{CTRL-]}
カーソルの下のキーワードを定義している場所にジャンプする。":tag @{name@}" と同様であるが、@{name@} はカーソルの下、もしくは次に現われるキーワードである。

@{name@} に対してマッチするタグが複数ある場合、[count] 番目のタグへジャンプする。[count] が指定されないときは最初のタグへジャンプする。他のマッチするタグへジャンプするには |@ref{tag-matchlist}| を参照。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*v_CTRL-]*
{Visual}CTRL-]		Same as ":tag {name}", where {name} is the text that
			is highlighted.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{v_CTRL-]}
@kindex v_CTRL-]
@item @{Visual@}@kbd{CTRL-]}
":tag @{name@}" と同様であるが、@{name@} はハイライトされているテキストである。
@end table
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*telnet-CTRL-]*
CTRL-] is the default telnet escape key.  When you type CTRL-] to jump to a
tag, you will get the telnet prompt instead.  Most versions of telnet allow
changing or disabling the default escape key.  See the telnet man page.  You
can 'telnet -E {Hostname}' to disable the escape character, or 'telnet -e
{EscapeCharacter} {Hostname}' to specify another escape character.  If
possible, try to use "ssh" instead of "telnet" to avoid this problem.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{telnet-CTRL-]}
@kindex telnet-CTRL-]
@kbd{CTRL-]} は telnet の標準エスケープキーである。タグにジャンプしようと @kbd{CTRL-]} を打つと、代わりに telnet のプロンプトが立ち上がるだろう。telnet のたいていのバージョンは、標準エスケープキーを変更、もしくは使用不可能にできる。telnet のマニュアルを参照すること。エスケープキーを使用不可能にするには 'telnet -E @{ホスト名@}'、エスケープ文字を他の文字にするには 'telnet -e @{エスケープ文字@} @{ホスト名@}' を使用する。もし可能なら telnet の代わりに ssh を使うことで、この問題を回避できる。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*tag-priority*
When there are multiple matches for a tag, this priority is used:
1. "FSC"  A full matching static tag for the current file.
2. "F C"  A full matching global tag for the current file.
3. "F  "  A full matching global tag for another file.
4. "FS "  A full matching static tag for another file.
5. " SC"  An ignore-case matching static tag for the current file.
6. "  C"  An ignore-case matching global tag for the current file.
7. "   "  An ignore-case matching global tag for another file.
8. " S "  An ignore-case matching static tag for another file.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{tag-priority}
@cindex tag-priority
タグのマッチが複数ある場合、以下の優先度が使われる:
@enumerate
@item "FSC"  カレントファイル内の全一致する static タグ。
@item "F C"  カレントファイル内の全一致する global タグ。
@item "F  "  別のファイル内の全一致する global タグ。
@item "FS "  別のファイル内の全一致する static タグ。
@item " SC"  カレントファイル内の大文字、小文字を無視した一致をする static タグ。
@item "  C"  カレントファイル内の大文字、小文字を無視した一致をする global タグ。
@item "   "  別のファイル内の大文字、小文字を無視した一致をする global タグ。
@item " S "  別のファイル内の大文字、小文字を無視した一致をする static タグ。
@end enumerate
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Note that when the current file changes, the priority list is mostly not
changed, to avoid confusion when using ":tnext".  It is changed when using
":tag {name}".
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@quotation
@strong{Note:} @*
カレントファイルが変わっても、優先度のリストはほとんどの場合変化しないので注意すること。これは "@command{:tnext}" を使うときの混乱を避けるためである。優先度のリストは ":tag @{name@}" を使ったときに変化する。
@end quotation
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
The ignore-case matches are not found for a ":tag" command when:
- 'tagcase' is "followic" and the 'ignorecase' option is off
- 'tagcase' is "followscs" and the 'ignorecase' option is off and the
  'smartcase' option is off or the pattern contains an upper case character.
- 'tagcase' is "match"
- 'tagcase' is "smart" and the pattern contains an upper case character.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
以下の場合は ":tag " で大文字小文字を無視した検索は行われません:
@itemize
@item '@option{tagcase}' が "@var{followic}" で '@option{ignorecase}' オプションがオフの時
@item '@option{tagcase}' が "@var{followscs}" で '@option{ignorecase}' オプションがオフで '@option{smartcase}' オプションがオフであるか、パターンに大文字が含まれている時
@item '@option{tagcase}' が "@var{match}" である
@item '@option{tagcase}' が "@var{smart}" でパターンに大文字が含まれる時
@end itemize
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
The ignore-case matches are found when:
- a pattern is used (starting with a "/")
- for ":tselect"
- when 'tagcase' is "followic" and 'ignorecase' is on
- when 'tagcase' is "followscs" and 'ignorecase' is on or the 'smartcase'
  option is on and the pattern does not contain an upper case character
- when 'tagcase' is "ignore"
- when 'tagcase' is "smart" and the patter does not contain an upper case
  character
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
以下の場合は大文字小文字を無視した検索が行われます:
@itemize
@item パターンが使用される時 ("/" で始まる)
@item ":tselect" の時
@item '@option{tagcase}' が "@var{followic}" で '@option{ignorecase}' がオンの時
@item '@option{tagcase}' が "@var{followscs}" で '@option{ignorecase}' がオン、または '@option{smartcase}' オプションがオンでパターンに大文字が含まれていない時
@item '@option{tagcase}' が "@var{ignore}" の時
@item '@option{tagcase}' が "@var{smart}" でパターンに大文字が含まれていない時
@end itemize
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Note that using ignore-case tag searching disables binary searching in the
tags file, which causes a slowdown.  This can be avoided by fold-case sorting
the tag file. See the 'tagbsearch' option for an explanation.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@quotation
@strong{Note:} @*
大文字小文字を無視したタグ検索はタグファイル内での二分探索を無効にし速度の低下を引き起こします。これは大文字小文字を保持したままタグファイルを並び替える事で回避できます。'@option{tagbsearch}' オプションの説明を参照
@end quotation
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
==============================================================================
2. Tag stack				*tag-stack* *tagstack* *E425*
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{tag-stack}
@anchor{tagstack}
@anchor{E425}
@cindex tag-stack
@cindex tagstack
@erindex E425
@cindex タグスタック
@section 2. タグスタック
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
On the tag stack is remembered which tags you jumped to, and from where.
Tags are only pushed onto the stack when the 'tagstack' option is set.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
タグスタック上にはジャンプ先のタグと、どこから来たのかという情報が記憶される。タグは '@option{tagstack}' オプションが設定されているときにだけ積まれる。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
g<RightMouse>						*g<RightMouse>*
<C-RightMouse>					*<C-RightMouse>* *CTRL-T*
CTRL-T			Jump to [count] older entry in the tag stack
			(default 1).
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@table @asis
@anchor{g<RightMouse>}
@anchor{<C-RightMouse>}
@anchor{CTRL-T}
@kindex g<RightMouse>
@kindex <C-RightMouse>
@kindex CTRL-T
@item g<RightMouse> または
@itemx <C-RightMouse> または
@itemx @kbd{CTRL-T}
タグスタック中の [count] 分だけ古いエントリにジャンプする (デフォルトは 1)。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
						*:po* *:pop* *E555* *E556*
:[count]po[p][!]	Jump to [count] older entry in tag stack (default 1).
			See |tag-!| for [!].
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{:po}
@anchor{:pop}
@anchor{E555}
@anchor{E556}
@pindex :po
@pindex :pop
@erindex E555
@erindex E556
@item :[count]po[p][!]
タグスタック中の [count] 分だけ古いエントリにジャンプする (デフォルトは 1)。

[!] については |@ref{tag-!}| を参照。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
:[count]ta[g][!]	Jump to [count] newer entry in tag stack (default 1).
			See |tag-!| for [!].
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item :[count]ta[g][!]
タグスタック中の [count] 分だけ新しいエントリにジャンプする (デフォルトは 1)。

[!] については |@ref{tag-!}| を参照。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*:tags*
:tags			Show the contents of the tag stack.  The active
			entry is marked with a '>'.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{:tags}
@pindex :tags
@item :tags
タグスタックの内容を表示する。現在のエントリは '>' でマークされる。
@end table
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
The output of ":tags" looks like this:

   # TO tag      FROM line  in file/text
   1  1 main		 1  harddisk2:text/vim/test
 > 2  2 FuncA		58  i = FuncA(10);
   3  1 FuncC	       357  harddisk2:text/vim/src/amiga.c
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
":tags" の出力は以下のようになる:
@verbatim
   # TO tag      FROM line  in file/text
   1  1 main             1  harddisk2:text/vim/test
 > 2  2 FuncA           58  i = FuncA(10);
   3  1 FuncC          357  harddisk2:text/vim/src/amiga.c
@end verbatim
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
This list shows the tags that you jumped to and the cursor position before
that jump.  The older tags are at the top, the newer at the bottom.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
このリストはジャンプ先のタグとジャンプ前のカーソル位置を表示する。上から順に古いタグが並び、一番下が最も新しいタグである。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
The '>' points to the active entry.  This is the tag that will be used by the
next ":tag" command.  The CTRL-T and ":pop" command will use the position
above the active entry.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
'>' は現在のエントリを指している。これは次の ":tag" コマンドで使われるタグである。CTRL-T と ":pop" コマンドは 1 つ上のタグを使う。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Below the "TO" is the number of the current match in the match list.  Note
that this doesn't change when using ":pop" or ":tag".
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
"TO" の列にはマッチリスト中の現在のマッチ数を表示する。これは ":pop" や ":tag" を使っても変化しないので注意すること。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
The line number and file name are remembered to be able to get back to where
you were before the tag command.  The line number will be correct, also when
deleting/inserting lines, unless this was done by another program (e.g.
another instance of Vim).
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
行番号とファイル名は、タグコマンドを実行する前にいた位置に戻ることができるように記憶される。行番号は行の削除や挿入が行われた時にも正しく維持される。ただし、別のプログラム(例えば、Vim の別インスタンス)で編集した場合を除く。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
For the current file, the "file/text" column shows the text at the position.
An indent is removed and a long line is truncated to fit in the window.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
ジャンプ前の位置がカレントファイル内であれば、"file/text" の列にその行が表示される。インデントは取り除かれ、長い行はウィンドウに収まるように切り詰められる。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
You can jump to previously used tags with several commands.  Some examples:

	":pop" or CTRL-T	to position before previous tag
	{count}CTRL-T		to position before {count} older tag
	":tag"			to newer tag
	":0tag"			to last used tag
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
前に使ったタグにジャンプするコマンドはいくつかある。例えば:
@verbatim
":pop" or CTRL-T    ひとつ前に使われたタグにジャンプする。
{count}CTRL-T       {count}分だけ前のタグにジャンプする。
":tag"              現在のエントリより新しいタグにジャンプする。
":0tag"             最後に使われたタグにジャンプする。
@end verbatim
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
The most obvious way to use this is while browsing through the call graph of
a program.  Consider the following call graph:

	main  --->  FuncA  --->  FuncC
	      --->  FuncB
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
これらの最も明白な利用方法は、プログラムの関数呼び出しをあちこち拾い読みするときである。次のような呼び出し図を考える:
@verbatim
main  --->  FuncA  --->  FuncC
      --->  FuncB
@end verbatim
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
(Explanation: main calls FuncA and FuncB; FuncA calls FuncC).
You can get from main to FuncA by using CTRL-] on the call to FuncA.  Then
you can CTRL-] to get to FuncC.  If you now want to go back to main you can
use CTRL-T twice.  Then you can CTRL-] to FuncB.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
(解説: main は FuncA と FuncB を呼び出し、FuncA は FuncC を呼び出す)。
FuncA の呼び出し部分の上で @kbd{CTRL-]} を使うことによって、main から FuncA に行くことができる。同様に @kbd{CTRL-]} を使って FuncC へ行くことができる。mainに 戻るには @kbd{CTRL-T} を 2 回使う。そこで @kbd{CTRL-]} を使って FuncB に行くことができる。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
If you issue a ":ta {name}" or CTRL-] command, this tag is inserted at the
current position in the stack.  If the stack was full (it can hold up to 20
entries), the oldest entry is deleted and the older entries shift one
position up (their index number is decremented by one).  If the last used
entry was not at the bottom, the entries below the last used one are
deleted.  This means that an old branch in the call graph is lost.  After the
commands explained above the tag stack will look like this:
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
":ta @{name@}" や @kbd{CTRL-]} コマンドは、タグスタック上の現在の位置にタグを追加する。もしスタックが満たされていた場合(スタックは 20 エントリまで保持できる)、最も古いエントリが削除され、古いものから順にひとつずつ上に移動する(インデックス番号は 1 ずつ減る)。もし最後に使われたエントリが一番下になかった場合、最後に使われたエントリより下にあるものは削除される。つまり古いタグ経路は失われる。上のパラグラフの説明を実行したあとのタグスタックは次のような状態になる:
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
   # TO tag	FROM line  in file/text
   1  1 main		1  harddisk2:text/vim/test
   2  1 FuncB	       59  harddisk2:text/vim/src/main.c
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@verbatim
# TO tag     FROM line  in file/text
1  1 main            1  harddisk2:text/vim/test
2  1 FuncB          59  harddisk2:text/vim/src/main.c
@end verbatim
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
The |gettagstack()| function returns the tag stack of a specified window. The
|settagstack()| function modifies the tag stack of a window.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
|@ref{gettagstack()}| 関数は指定されたウィンドウのタグスタックを返す。|@ref{settagstack()}| 関数はウィンドウのタグスタックを変更する。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*E73*
When you try to use the tag stack while it doesn't contain anything you will
get an error message.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{E73}
@erindex E73
タグスタックを使おうとしたとき、タグスタックに何も入っていないとエラーが表示される。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
==============================================================================
3. Tag match list				*tag-matchlist* *E427* *E428*
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{tag-matchlist}
@anchor{E427}
@anchor{E428}
@cindex tag-matchlist
@erindex E427
@erindex E428
@cindex タグマッチリスト
@section 3. タグマッチリスト
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
When there are several matching tags, these commands can be used to jump
between them.  Note that these commands don't change the tag stack, they keep
the same entry.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
以下のコマンドは複数のタグがマッチしたときに、タグの間を移動するために使うことができる。これらのコマンドはタグスタックを変更せず、同じエントリを保つことに注意すること。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*:ts* *:tselect*
:ts[elect][!] [name]	List the tags that match [name], using the
			information in the tags file(s).
			When [name] is not given, the last tag name from the
			tag stack is used.
			See |tag-!| for [!].
			With a '>' in the first column is indicated which is
			the current position in the list (if there is one).
			[name] can be a regexp pattern, see |tag-regexp|.
			See |tag-priority| for the priorities used in the
			listing.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@table @asis
@anchor{:ts}
@anchor{:tselect}
@pindex :ts
@pindex :tselect
@item :ts[elect][!] [name]
タグファイルの情報を用いて、[name] にマッチするタグをリスト表示する。

[name] を省略した場合、タグスタック上の最後のタグが使われる。

[!] については |@ref{tag-!}| を参照。

最初の列に '>' があるものはリスト中の現在の位置を指し示している (それがあるならば)。[name] は正規表現を取り得る。|@ref{tag-regexp}| を参照。リストに使われているプロパティは |@ref{tag-priority}| を参照。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
			Example output:

>
	 nr pri kind tag		file
	  1 F	f    mch_delay		os_amiga.c
			mch_delay(msec, ignoreinput)
	> 2 F	f    mch_delay		os_msdos.c
			mch_delay(msec, ignoreinput)
	  3 F	f    mch_delay		os_unix.c
			mch_delay(msec, ignoreinput)
	Enter nr of choice (<CR> to abort):
<
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
出力例:
@verbatim
 nr pri kind tag                file
  1 F   f    mch_delay          os_amiga.c
                mch_delay(msec, ignoreinput)
> 2 F   f    mch_delay          os_msdos.c
                mch_delay(msec, ignoreinput)
  3 F   f    mch_delay          os_unix.c
                mch_delay(msec, ignoreinput)
Enter nr of choice (<CR> to abort):
@end verbatim
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
			See |tag-priority| for the "pri" column.  Note that
			this depends on the current file, thus using
			":tselect xxx" can produce different results.
			The "kind" column gives the kind of tag, if this was
			included in the tags file.
			The "info" column shows information that could be
			found in the tags file.  It depends on the program
			that produced the tags file.
			When the list is long, you may get the |more-prompt|.
			If you already see the tag you want to use, you can
			type 'q' and enter the number.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
"pri" については |@ref{tag-priority}| を参照。この例は現在のファイルに依存しているため、":tselect xxx" を使ったときには違う結果が得られることに注意すること。

"kind" はタグファイルからタグの種類が得られる場合のみ、その情報を示す。

"info" はタグファイルから得られる情報が表示される。この情報はタグファイルを生成したプログラムに依存する。

リストが長い場合には |@ref{more-prompt}| が表示される。もしすでに使いたいタグを見つけているのなら、'q' のあとに "nr" の番号を入力すればよい。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*:sts* *:stselect*
:sts[elect][!] [name]	Does ":tselect[!] [name]" and splits the window for
			the selected tag.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{:sts}
@anchor{:stselect}
@pindex :sts
@pindex :stselect
@item :sts[elect][!] [name]
":tselect[!] [name]" を実行し、ウィンドウを分割して選択された tag を表示する。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*g]*
g]			Like CTRL-], but use ":tselect" instead of ":tag".
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{g]}
@kindex g]
@item g]
@kbd{CTRL-]} と動作は似ているが、":tag" の代わりに ":tselect" を用いる。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*v_g]*
{Visual}g]		Same as "g]", but use the highlighted text as the
			identifier.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{v_g]}
@kindex v_g]
@item @{Visual@}g]
"g]" と同じ。ただし、選択されたテキストが検索に使われる。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*:tj* *:tjump*
:tj[ump][!] [name]	Like ":tselect", but jump to the tag directly when
			there is only one match.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{:tj}
@anchor{:tjump}
@pindex :tj
@pindex :tjump
@item :tj[ump][!] [name]
"@command{:tselect}" と動作は似ているが、適合する tag が 1 つだけのときには直接移動する。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*:stj* *:stjump*
:stj[ump][!] [name]	Does ":tjump[!] [name]" and splits the window for the
			selected tag.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{:stj}
@anchor{:stjump}
@pindex :stj
@pindex :stjump
@item :stj[ump][!] [name]
":tjump[!] [name]" を実行し、ウィンドウを分割して選択された tag を表示する。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*g_CTRL-]*
g CTRL-]		Like CTRL-], but use ":tjump" instead of ":tag".
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{g_CTRL-]}
@kindex g_CTRL-]
@item g @kbd{CTRL-]}
CTRL-]と動作は似ているが、":tag" の代わりに ":tjump" を用いる。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*v_g_CTRL-]*
{Visual}g CTRL-]	Same as "g CTRL-]", but use the highlighted text as
			the identifier.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{v_g_CTRL-]}
@kindex v_g_CTRL-]
@item @{Visual@}g @kbd{CTRL-]}
"g CTRL-]" と同じ。ただし、選択されたテキストが検索に使われる。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*:tn* *:tnext*
:[count]tn[ext][!]	Jump to [count] next matching tag (default 1).  See
			|tag-!| for [!].
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{:tn}
@anchor{:tnext}
@pindex :tn
@pindex :tnext
@item :[count]tn[ext][!]
適合する tag のうち、[count] 番目の tag に移動する。(省略時は 1)

[!] に関しては |@ref{tag-!}| を参照。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*:tp* *:tprevious*
:[count]tp[revious][!]	Jump to [count] previous matching tag (default 1).
			See |tag-!| for [!].
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{:tp}
@anchor{:tprevious}
@pindex :tp
@pindex :tprevious
@item :[count]tp[revious][!]
適合する tag のうち、[count] 分だけ前の tag に移動する。(省略時は 1)

[!] に関しては |@ref{tag-!}| を参照。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*:tN* *:tNext*
:[count]tN[ext][!]	Same as ":tprevious".
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{:tN}
@anchor{:tNext}
@pindex :tN
@pindex :tNext
@item :[count]tN[ext][!]
"@command{:tprevious}" と同様。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*:tr* *:trewind*
:[count]tr[ewind][!]	Jump to first matching tag.  If [count] is given, jump
			to [count]th matching tag.  See |tag-!| for [!].
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{:tr}
@anchor{:trewind}
@pindex :tr
@pindex :trewind
@item :[count]tr[ewind][!]
適合した tag のうち最初の tag に移動する。もし [count] が与えられていたら、[count] 番目の tag に移動する。

[!] については |@ref{tag-!}| を参照。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*:tf* *:tfirst*
:[count]tf[irst][!]	Same as ":trewind".
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{:tf}
@anchor{:tfirst}
@pindex :tf
@pindex :tfirst
@item :[count]tf[irst][!]
"@command{:trewind}" と同じ。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*:tl* *:tlast*
:tl[ast][!]		Jump to last matching tag.  See |tag-!| for [!].
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{:tl}
@anchor{:tlast}
@pindex :tl
@pindex :tlast
@item :tl[ast][!]
適合した tag のうち最後の tag に移動する。

[!] に関しては |@ref{tag-!}| を参照。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*:lt* *:ltag*
:lt[ag][!] [name]	Jump to tag [name] and add the matching tags to a new
			location list for the current window.  [name] can be
			a regexp pattern, see |tag-regexp|.  When [name] is
			not given, the last tag name from the tag stack is
			used.  The search pattern to locate the tag line is
			prefixed with "\V" to escape all the special
			characters (very nomagic). The location list showing
			the matching tags is independent of the tag stack.
			See |tag-!| for [!].
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{:lt}
@anchor{:ltag}
@pindex :lt
@pindex :ltag
@item :lt[ag][!] [name]
タグ [name] にジャンプし、マッチするタグ全てをカレントウィンドウの新しいロケーションリストに追加する。[name] は正規表現でもよい (|@ref{tag-regexp}| を参照)。[name] が指定されないときはタグスタックにある最後のタグ名が使われる。タグにマッチする行を特定するための検索パターンには、特別な文字を全てエスケープするために "\V" がつけられる (very nomagic)。マッチするタグを保持するロケーションリストはタグスタックとは独立している。

[!] については |@ref{tag-!}| を参照。
@end table
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
When there is no other message, Vim shows which matching tag has been jumped
to, and the number of matching tags: >
	tag 1 of 3 or more
The " or more" is used to indicate that Vim didn't try all the tags files yet.
When using ":tnext" a few times, or with ":tlast", more matches may be found.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
他にメッセージがないとき、Vim は今までに移動した tag と tag の数を表示する:
@verbatim
tag 1 of 3 or more
@end verbatim
" or more" は、Vim がまだすべての tag ファイルを検索していないことを示すために用いられる。":tnext" を数回用いるか、":tlast" を使用したとき、さらに tag が見つけられるだろう。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
When you didn't see this message because of some other message, or you just
want to know where you are, this command will show it again (and jump to the
same tag as last time): >
	:0tn
<
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
他のメッセージがあったときや、現在の場所を知りたいときには次のコマンドで再び表示することができる。(最後に行った移動と同じ tag に移動する。):
@example
:0tn
@end example
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
							*tag-skip-file*
When a matching tag is found for which the file doesn't exist, this match is
skipped and the next matching tag is used.  Vim reports this, to notify you of
missing files.  When the end of the list of matches has been reached, an error
message is given.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{tag-skip-file}
@cindex tag-skip-file
マッチしたタグに対するファイルが見つからなかった場合、スキップされて次にマッチするタグが使われる。Vim はファイルがないことを通知する。もしリストの終端に達していたならば、エラーメッセージが与えられる。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*tag-preview*
The tag match list can also be used in the preview window.  The commands are
the same as above, with a "p" prepended.
{not available when compiled without the |+quickfix| feature}
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{tag-preview}
@cindex tag-preview
タグマッチリストはプレビューウィンドウ内でも使用できる。そのコマンドは上記のものに似ているが、先頭に "p" がつく。

@{|@ref{+quickfix}| が無効なときは利用できない@}
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*:pts* *:ptselect*
:pts[elect][!] [name]	Does ":tselect[!] [name]" and shows the new tag in a
			"Preview" window.  See |:ptag| for more info.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@table @asis
@anchor{:pts}
@anchor{:ptselect}
@pindex :pts
@pindex :ptselect
@item :pts[elect][!] [name]
"@command{:tselect[!] [name]}" を実行し、"Preview" ウィンドウに新しいタグを表示する。詳細は |@ref{:ptag}| を参照すること。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*:ptj* *:ptjump*
:ptj[ump][!] [name]	Does ":tjump[!] [name]" and shows the new tag in a
			"Preview" window.  See |:ptag| for more info.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{:ptj}
@anchor{:ptjump}
@pindex :ptj
@pindex :ptjump
@item :ptj[ump][!] [name]
":tjump[!] [name]" を実行し、"Preview" ウィンドウに新しいタグを表示する。詳細は |@ref{:ptag}| を参照すること。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*:ptn* *:ptnext*
:[count]ptn[ext][!]	":tnext" in the preview window.  See |:ptag|.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{:ptn}
@anchor{:ptnext}
@pindex :ptn
@pindex :ptnext
@item :[count]ptn[ext][!]
プレビューウィンドウで "@command{:tnext}" を実行する。|@ref{:ptag}| を参照すること。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*:ptp* *:ptprevious*
:[count]ptp[revious][!]	":tprevious" in the preview window.  See |:ptag|.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{:ptp}
@anchor{:ptprevious}
@pindex :ptp
@pindex :ptprevious
@item :[count]ptp[revious][!]
プレビューウィンドウで "@command{:tprevious}" を実行する。|@ref{:ptag}| を参照すること。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*:ptN* *:ptNext*
:[count]ptN[ext][!]	Same as ":ptprevious".
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{:ptN}
@anchor{:ptNext}
@pindex :ptN
@pindex :ptNext
@item :[count]ptN[ext][!]
"@command{:ptprevious}" と同じ。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*:ptr* *:ptrewind*
:[count]ptr[ewind][!]	":trewind" in the preview window.  See |:ptag|.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{:ptr}
@anchor{:ptrewind}
@pindex :ptr
@pindex :ptrewind
@item :[count]ptr[ewind][!]
プレビューウィンドウで "@command{:trewind}" を実行する。|@ref{:ptag}| を参照すること。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*:ptf* *:ptfirst*
:[count]ptf[irst][!]	Same as ":ptrewind".
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{:ptf}
@anchor{:ptfirst}
@pindex :ptf
@pindex :ptfirst
@item :[count]ptf[irst][!]
"@command{:ptrewind}" と同じ。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*:ptl* *:ptlast*
:ptl[ast][!]		":tlast" in the preview window.  See |:ptag|.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{:ptl}
@anchor{:ptlast}
@pindex :ptl
@pindex :ptlast
@item :ptl[ast][!]
プレビューウィンドウで "@command{:tlast}" を実行する。|@ref{:ptag}| を参照すること。
@end table
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
==============================================================================
4. Tags details						*tag-details*
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{tag-details}
@cindex tag-details
@cindex タグの詳細
@section 4. タグの詳細
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*static-tag*
A static tag is a tag that is defined for a specific file.  In a C program
this could be a static function.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{static-tag}
@cindex static-tag
static タグは特別なファイルのために定義されたタグである。C プログラムでは static 関数が当てはまる。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
In Vi jumping to a tag sets the current search pattern.  This means that
the "n" command after jumping to a tag does not search for the same pattern
that it did before jumping to the tag.  Vim does not do this as we consider it
to be a bug.  You can still find the tag search pattern in the search history.
If you really want the old Vi behavior, set the 't' flag in 'cpoptions'.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
Vi はタグにジャンプするときに現在の検索パターンを設定する。これはタグにジャンプしたあとの "n" コマンドは、その前の検索パターンと同じ検索を行わないということである。Vim ではこのようなバグとも考えられることはしない。検索履歴にある検索パターンで検索できる。もし古い Vi の振る舞いを望むならば、'@option{cpoptions}' に '@var{t}' を設定する。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*tag-binary-search*
Vim uses binary searching in the tags file to find the desired tag quickly
(when enabled at compile time |+tag_binary|).  But this only works if the
tags file was sorted on ASCII byte value.  Therefore, if no match was found,
another try is done with a linear search.  If you only want the linear search,
reset the 'tagbsearch' option.  Or better: Sort the tags file!
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{tag-binary-search}
@cindex tag-binary-search
Vim は希望のタグをすばやく見つけるために、タグファイル内で二分探索を行う(|@ref{+tag_binary}| がコンパイル時に有効になっていれば)。しかしこれはタグファイルが ASCII コードでソートされている場合にのみ機能する。したがって、もし適合しないものが見つかった場合は、その他の方法として線形探索が行われる。もし線形探索のみを利用したいならば、'@option{tagbsearch}' オプションをリセットすればよい。そうでなければ: タグファイルをソートすること！
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Note that the binary searching is disabled when not looking for a tag with a
specific name.  This happens when ignoring case and when a regular expression
is used that doesn't start with a fixed string.  Tag searching can be a lot
slower then.  The former can be avoided by case-fold sorting the tags file.
See 'tagbsearch' for details.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@quotation
@strong{Note:} @*
検索が明確な名前をもったタグでない場合は二分探索は利用できないことに注意すること。これは大文字小文字を無視した検索や固定文字列で始まらない正規表現による検索で発生する。そのときはタグ検索はかなり遅くなるだろう。先人はタグファイルを大文字と小文字を区別せずにソートすることで回避できた。詳細は 'tagbsearch' を参照のこと。
@end quotation
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*tag-regexp*
The ":tag" and ":tselect" commands accept a regular expression argument.  See
|pattern| for the special characters that can be used.
When the argument starts with '/', it is used as a pattern.  If the argument
does not start with '/', it is taken literally, as a full tag name.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{tag-regexp}
@cindex tag-regexp
"@command{:tag}" と "@command{:tselect}" コマンドは引数に正規表現を受け付ける。使用できる特殊文字については |@ref{pattern}| を参照すること。引数が '/' で始まる場合はパターンとして使われる。もし引数が '/' で始まらなければ、完全なタグ名の文字列として扱われる。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
Examples: >
    :tag main
<	jumps to the tag "main" that has the highest priority. >
    :tag /^get
<	jumps to the tag that starts with "get" and has the highest priority. >
    :tag /norm
<	lists all the tags that contain "norm", including "id_norm".
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
例:
@table @asis
@item :tag main
最も優先度の高い "main" というタグにジャンプする。
@item :tag /^get
最も優先度の高い "get" で始まるタグにジャンプする。
@item :tag /norm
"norm" を含むすべてのタグを列挙する。これは "id_norm" というタグも含まれる。
@end table
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
When the argument both exists literally, and match when used as a regexp, a
literal match has a higher priority.  For example, ":tag /open" matches "open"
before "open_file" and "file_open".
When using a pattern case is ignored.  If you want to match case use "\C" in
the pattern.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
もし引数と全く同じタグと、正規表現によってマッチしたタグがあった場合、引数と同じタグが優先される。例えば、":tag /open" は "open_file" や "file_open" よりも前に "open" にマッチする。

正規表現を使うときは大文字・小文字は区別されない。大文字・小文字を区別したいなら正規表現の中で "\C" を使うこと。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*tag-!*
If the tag is in the current file this will always work.  Otherwise the
performed actions depend on whether the current file was changed, whether a !
is added to the command and on the 'autowrite' option:
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{tag-!}
@cindex tag-!
もしタグが現在のファイル上にあるならば、いつも機能するだろう。そうでなければ、実行結果は現在のファイルが変更されているか、コマンドに ! がつけられているか、'@option{autowrite}' オプションが設定されているかに依存する:
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
  tag in       file	   autowrite			~
current file  changed	!   option	  action	~
-----------------------------------------------------------------------------
    yes		 x	x     x	  goto tag
    no		 no	x     x	  read other file, goto tag
    no		yes    yes    x   abandon current file, read other file, goto
				  tag
    no		yes	no    on  write current file, read other file, goto
				  tag
    no		yes	no   off  fail
-----------------------------------------------------------------------------
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@multitable @columnfractions .2 .15 .1 .15 .4
@item タグが現在のファイル内 @tab 変更あり @tab ! @tab autowrite オプション @tab 動作
@item yes @tab x @tab x @tab x @tab タグに行く
@item no @tab no @tab x @tab x @tab 対象ファイルを読み込み、タグに行く
@item no @tab yes @tab yes @tab x @tab 現在のファイルを捨て、対象ファイルを読み込んでタグに行く
@item no @tab yes @tab no @tab on @tab 現在のファイルを保存し、対象ファイルを読み込んでタグに行く
@item no @tab yes @tab no @tab off @tab 失敗する
@end multitable
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
- If the tag is in the current file, the command will always work.
- If the tag is in another file and the current file was not changed, the
  other file will be made the current file and read into the buffer.
- If the tag is in another file, the current file was changed and a ! is
  added to the command, the changes to the current file are lost, the other
  file will be made the current file and read into the buffer.
- If the tag is in another file, the current file was changed and the
  'autowrite' option is on, the current file will be written, the other
  file will be made the current file and read into the buffer.
- If the tag is in another file, the current file was changed and the
  'autowrite' option is off, the command will fail.  If you want to save
  the changes, use the ":w" command and then use ":tag" without an argument.
  This works because the tag is put on the stack anyway.  If you want to lose
  the changes you can use the ":tag!" command.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@itemize
@item タグが現在のファイル上にある場合は、コマンドはいつも機能する。
@item タグが他のファイル上にあり、現在のファイルが変更されていないならば、対象となるファイルがバッファに読み込まれる。
@item タグが他のファイル上にあり、現在のファイルが変更されていて、かつ!がコマンドにつけられている場合には、現在のファイルに対する変更は失われ、対象となるファイルがバッファに読み込まれる。
@item タグが他のファイル上にあり、現在のファイルが変更されていて、かつ '@option{autowrite}' オプションが設定されている場合には、現在のファイルは保存され、対象となるファイルがバッファに読み込まれる。
@item タグが他のファイル上にあり、現在のファイルが変更されていて、かつ '@option{autowrite}' オプションが設定されていない場合には、コマンドは失敗する。変更を保存したいならば ":w" コマンドを使用し、そのあとで ":tag" を引数なしで実行する。これはタグがスタック上に残っているためにうまく機能する。変更を失ってもよいのならば、":tag!" コマンドを使用できる。
@end itemize
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*tag-security*
Note that Vim forbids some commands, for security reasons.  This works like
using the 'secure' option for exrc/vimrc files in the current directory.  See
|trojan-horse| and |sandbox|.
When the {tagaddress} changes a buffer, you will get a warning message:
	"WARNING: tag command changed a buffer!!!"
In a future version changing the buffer will be impossible.  All this for
security reasons: Somebody might hide a nasty command in the tags file, which
would otherwise go unnoticed.  Example: >
	:$d|/tag-function-name/
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{tag-security}
@cindex tag-security
@quotation
@strong{Note:} @*
Vim はセキュリティの都合上、いくつかのコマンドを禁止していることに注意すること。これはちょうど現在のディレクトリにある exrc/@file{vimrc} ファイルに '@option{secure}' オプションが使われているのと同じように機能する。|@ref{trojan-horse}| と |@ref{sandbox}| を参照すること。@{tagaddress@} がバッファを変更したとき、次のようなエラーメッセージが表示される:
@display
"WARNING: tag command changed a buffer!!!"
@end display
将来のバージョンではバッファを変更することは不可能になるだろう。これらはすべてセキュリティの理由である: 誰かが気づかれないように実行される厄介なコマンドをタグファイルに隠しているかもしれない。例えば:
@example
:$d|/tag-function-name/
@end example
@end quotation
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
In Vi the ":tag" command sets the last search pattern when the tag is searched
for.  In Vim this is not done, the previous search pattern is still remembered,
unless the 't' flag is present in 'cpoptions'.  The search pattern is always
put in the search history, so you can modify it if searching fails.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
Vi では ":tag" コマンドによってタグを検索すると、最新の検索パターンを上書きする。Vim では '@option{cpoptions}' に '@var{t}' フラグが設定されていなければ、前の検索パターンは引き続き記憶される。検索パターンはいつも検索履歴にあるので、もし検索に失敗したらそこを修正するとよい。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
					*emacs-tags* *emacs_tags* *E430*
Emacs style tag files are only supported if Vim was compiled with the
|+emacs_tags| feature enabled.  Sorry, there is no explanation about Emacs tag
files here, it is only supported for backwards compatibility :-).
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{emacs-tags}
@anchor{emacs_tags}
@anchor{E430}
@cindex emacs-tags
@cindex emacs_tags
@erindex E430
@cindex Emacs スタイルのタグファイル
Emacs スタイルのタグファイルは、Vim のコンパイル時に |@ref{+emacs_tags}| 機能を有効にした場合にのみ使用できる。すまないが、Emacs タグファイルについての説明はここではしない。それは下位互換のためにのみ提供している :-)。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Lines in Emacs tags files can be very long.  Vim only deals with lines of up
to about 510 bytes.  To see whether lines are ignored set 'verbose' to 5 or
higher.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
Emacs タグファイルの行は非常に長くなることがある。Vim は行の約 510 バイトまでしか扱わない。行が無視されたかどうかは 'verbose' を 5 以上にしていればわかる。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*tags-option*
The 'tags' option is a list of file names.  Each of these files is searched
for the tag.  This can be used to use a different tags file than the default
file "tags".  It can also be used to access a common tags file.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{tags-option}
@cindex tags-option
'@option{tags}' オプションはファイル名のリストで構成される。これらのファイルからタグが検索される。デフォルトの "tags" ファイルよりも、異なる @file{tags} ファイルがよく使われるだろう。共通の @file{tags} ファイルにもよくアクセスするだろう。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
The next file in the list is not used when:
- A matching static tag for the current buffer has been found.
- A matching global tag has been found.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
以下のようなときは、リストの次のファイルを使わない:
@itemize
@item 現在のバッファに対する static タグが見つかった場合。
@item global タグが見つかった場合。
@end itemize
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
This also depends on whether case is ignored.  Case is ignored when:
- 'tagcase' is "followic" and 'ignorecase' is set
- 'tagcase' is "ignore"
- 'tagcase' is "smart" and the pattern only contains lower case
  characters.
- 'tagcase' is "followscs" and 'smartcase' is set and the pattern only
  contains lower case characters.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
これは大文字小文字が無視されるかどうかにも依存します。大文字小文字は以下の場合に無視されます:
@itemize
@item '@option{tagcase}' が "@var{followic}" で '@option{ignorecase}' が設定されている
@item '@option{tagcase}' が "@var{ignore}" である
@item '@option{tagcase}' が "@var{smart}" でパターンに小文字だけが含まれている
@item '@option{tagcase}' が "@var{followscs}" で '@option{smartcase}' が設定されておりパターンに小文字のみが含まれている
@end itemize
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
If case is not ignored, and the tags file only has a match without matching
case, the next tags file is searched for a match with matching case.  If no
tag with matching case is found, the first match without matching case is
used.  If case is ignored, and a matching global tag with or without matching
case is found, this one is used, no further tags files are searched.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
大文字小文字が無視されず、タグファイルが大文字小文字を除外したマッチのみとなる場合、続くタグファイルは大文字小文字をマッチして検索されます。大文字小文字をマッチしてタグファイルが見つからない場合、大文字小文字を除外してマッチした最初の結果が使用されます。もし大文字小文字が無視されグローバルのタグでマッチした、もしくは大文字小文字を除外してマッチした場合、タグファイルの検索は行われず見付かったそのファイルが使用されます。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
When a tag file name starts with "./", the '.' is replaced with the path of
the current file.  This makes it possible to use a tags file in the directory
where the current file is (no matter what the current directory is).  The idea
of using "./" is that you can define which tag file is searched first: In the
current directory ("tags,./tags") or in the directory of the current file
("./tags,tags").
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
タグファイル名が "./" で始まるとき、'.' は現在のファイルのパスで置き換えられる。これにより、現在のファイルがあるディレクトリの @file{tags} ファイルを使用することができる(たとえ現在のディレクトリがどこであろうと)。"./" を使用する概念は、どのタグファイルを最初に検索するかを決定することである: 現在のディレクトリにするか ("tags,./tags")、現在のファイルがあるディレクトリにするか("./tags,tags")である。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
For example: >
	:set tags=./tags,tags,/home/user/commontags
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
例:
@example
:set tags=./tags,tags,/home/user/commontags
@end example
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
In this example the tag will first be searched for in the file "tags" in the
directory where the current file is.  Next the "tags" file in the current
directory.  If it is not found there, then the file "/home/user/commontags"
will be searched for the tag.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
この例では、現在のファイルがあるディレクトリの "tags" ファイルがまず検索される。次に現在のディレクトリにある "tags" ファイルが検索される。もしまだ見つからなければ、"/home/user/commontags" が検索される。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
This can be switched off by including the 'd' flag in 'cpoptions', to make
it Vi compatible.  "./tags" will then be the tags file in the current
directory, instead of the tags file in the directory where the current file
is.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
これは '@option{cpoptions}' に '@var{d}' フラグを含めることで Vi 互換のようにすることができる。"./tags" は現在のファイルがあるディレクトリの @file{tags} ファイルではなく、現在のディレクトリの @file{tags} ファイルを意味するようになる。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Instead of the comma a space may be used.  Then a backslash is required for
the space to be included in the string option: >
	:set tags=tags\ /home/user/commontags
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
コンマの代わりにスペースを使用してもよい。文字列オプションに含めるためにはスペースの前にバックスラッシュが必要となる:
@example
:set tags=tags\ /home/user/commontags
@end example
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
To include a space in a file name use three backslashes.  To include a comma
in a file name use two backslashes.  For example, use: >
	:set tags=tag\\\ file,/home/user/common\\,tags
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
ファイル名にスペースを含めるにはバックスラッシュを３つ並べる。コンマをファイル名に使用する場合にはバックスラッシュを２つ並べる。例えば:
@example
:set tags=tag\\\ file,/home/user/common\\,tags
@end example
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
for the files "tag file" and "/home/user/common,tags".  The 'tags' option will
have the value "tag\ file,/home/user/common\,tags".
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
"tag file" と "/home/user/common,tags" というファイルが指定できる。'@option{tags}' オプションは "tag\ file,/home/user/common\,tags" という値を持つだろう。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
If the 'tagrelative' option is on (which is the default) and using a tag file
in another directory, file names in that tag file are relative to the
directory where the tag file is.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
'@option{tagrelative}' オプションをオンにし(デフォルト)、他のディレクトリでタグファイルを使用すると、タグファイル内に記述されたファイル名はタグファイルがあるディレクトリを基準として相対パスになる。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
==============================================================================
5. Tags file format				*tags-file-format* *E431*
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{tags-file-format}
@anchor{E431}
@cindex tags-file-format
@erindex E431
@cindex タグファイルの書式
@section 5. タグファイルの書式
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
						*ctags* *jtags*
A tags file can be created with an external command, for example "ctags".  It
will contain a tag for each function.  Some versions of "ctags" will also make
a tag for each "#defined" macro, typedefs, enums, etc.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{ctags}
@anchor{jtags}
@pindex ctags
@pindex jtags
@file{tags} ファイルは "ctags" のような外部コマンドによって生成される。それはそれぞれの関数へのタグを含んでいる。"ctags" のあるバージョンでは "#defined" マクロや typedef、enum などに対してもタグを作ることができる。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Some programs that generate tags files:
ctags			As found on most Unix systems.  Only supports C.  Only
			does the basic work.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@cindex tags ファイルを生成するプログラム
@unnumberedsubsec tags ファイルを生成するプログラム:
@table @asis
@item ctags
ほとんどの Unix システムにある。C 言語のみ対応し、基本的な機能を提供する。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
							*Exuberant_ctags*
exuberant ctags		This is a very good one.  It works for C, C++, Java,
			Fortran, Eiffel and others.  It can generate tags for
			many items.  See http://ctags.sourceforge.net.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{Exuberant_ctags}
@cindex Exuberant_ctags
@item exuberant ctags
これはとてもよいものだ。C 言語、C++、Java、Fortran、Eiffel、そしてその他に対応している。多くの項目にタグを生成することができる。

@url{http://ctags.sourceforge.net} を参照。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
etags			Connected to Emacs.  Supports many languages.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item etags
Emacs に連携する。多言語に対応している。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
JTags			For Java, in Java.  It can be found at
			http://www.fleiner.com/jtags/.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item JTags
Java 用、Java で書かれている。
@url{http://www.fleiner.com/jtags/} で入手できる。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
ptags.py		For Python, in Python.  Found in your Python source
			directory at Tools/scripts/ptags.py.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item ptags.py
Python 用、Python で書かれている。Python のソースディレクトリ Tools/scripts/ptags.py にある。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
ptags			For Perl, in Perl.  It can be found at
			http://www.eleves.ens.fr:8080/home/nthiery/Tags/.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item ptags
Perl 用、Perl で書かれている。これはここで見つかる。
@url{http://www.eleves.ens.fr:8080/home/nthiery/Tags/}
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
gnatxref		For Ada.  See http://www.gnuada.org/.  gnatxref is
			part of the gnat package.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item gnatxref
Ada 用。@url{http://www.gnuada.org/} を参照。
gnatxref は gnat パッケージの一部である。
@end table
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
The lines in the tags file must have one of these two formats:

1.  {tagname}		{TAB} {tagfile} {TAB} {tagaddress}
2.  {tagname}		{TAB} {tagfile} {TAB} {tagaddress} {term} {field} ..
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
tags ファイルは次の 2 つの形式のどれかで構成されなければならない:
@enumerate
@item @{tagname@}             @{TAB@} @{tagfile@} @{TAB@} @{tagaddress@}
@item @{tagname@}             @{TAB@} @{tagfile@} @{TAB@} @{tagaddress@} @{term@} @{field@} ..
@end enumerate
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Previously an old format was supported, see |tag-old-static|.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
以前には古い形式がサポートされていた、|@ref{tag-old-static}| を参照。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
The first format is a normal tag, which is completely compatible with Vi.  It
is the only format produced by traditional ctags implementations.  This is
often used for functions that are global, also referenced in other files.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
最初の形式は通常のタグで、Viで完全に互換性がある。伝統的なctagsによってのみ作られる形式である。これはしばしばグローバルな関数や他のファイルを参照する場合に使用される。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
The lines in the tags file can end in <LF> or <CR><LF>.  On the Macintosh <CR>
also works.  The <CR> and <NL> characters can never appear inside a line.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
タグファイルの行は <LF> または <CR><LF> で終わる。Macintosh では <CR> も機能する。<CR> と <NL> は行内に決して現れない。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
The second format is new.  It includes additional information in optional
fields at the end of each line.  It is backwards compatible with Vi.  It is
only supported by new versions of ctags (such as Exuberant ctags).
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
2 番目の形式は新しい。各行の末尾にある任意的なフィールドに追加の情報を含む。これは以前の Vi とも互換性がある。新しいバージョンの ctags にのみサポートされている(Exuberant ctags とか)。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
{tagname}	The identifier.  Normally the name of a function, but it can
		be any identifier.  It cannot contain a <Tab>.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@table @asis
@item @{tagname@}
識別子。普通は関数名であるが、どんな識別子でも構わない。<Tab> を含めることはできない。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
{TAB}		One <Tab> character.  Note: previous versions allowed any
		white space here.  This has been abandoned to allow spaces in
		{tagfile}.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item @{TAB@}
1 文字の <Tab>。
@quotation
@strong{Note:} @*
以前のバージョンではここでどんな空白文字も許可していた。これは @{tagfile@} 内にスペースを使うことを断念したためである。
@end quotation
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
{tagfile}	The file that contains the definition of {tagname}.  It can
		have an absolute or relative path.  It may contain environment
		variables and wildcards (although the use of wildcards is
		doubtful).  It cannot contain a <Tab>.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item @{tagfile@}
@{tagname@} の定義を含むファイル名。絶対パスでも相対パスでも構わない。環境変数やワイルドカードを含んでもよい(ワイルドカードの使用方法はあいまいだが)。<Tab> を含むことはできない。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
{tagaddress}	The Ex command that positions the cursor on the tag.  It can
		be any Ex command, although restrictions apply (see
		|tag-security|).  Posix only allows line numbers and search
		commands, which are mostly used.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item @{tagaddress@}
カーソルをタグ上に移動する Ex コマンド。制限 (|@ref{tag-security}| を参照)はあるが、どんな Ex コマンドでも使用可能である。Posix では主に使われる行番号と検索コマンドのみ許可する。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
{term}		;" The two characters semicolon and double quote.  This is
		interpreted by Vi as the start of a comment, which makes the
		following be ignored.  This is for backwards compatibility
		with Vi, it ignores the following fields. Example:
			APP	file	/^static int APP;$/;"	v
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item @{term@}
;" セミコロンとダブルクォートの 2 文字。これは Vi によってコメントとみなされ、続く文字列は無視される。以前の Vi との互換性を保つためにある。これは続くフィールドを無視する。例
@example
APP     file    /^static int APP;$/;"   v
@end example
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
		When {tagaddress} is not a line number or search pattern, then
		{term} must be |;".  Here the bar ends the command (excluding
		the bar) and ;" is used to have Vi ignore the rest of the
		line.  Example:
			APP	file.c	call cursor(3, 4)|;"	v
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@{tagaddress@} が行番号または検索パターンではない場合、@{term@} は |;" でなければならない。ここで、バーはコマンドを終了させる (バーを除く)。そして ;" は Vi に残りの行を無視させるために使われる。例:
@example
APP     file.c  call cursor(3, 4)|;"    v
@end example
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
{field} ..	A list of optional fields.  Each field has the form:

			<Tab>{fieldname}:{value}

		The {fieldname} identifies the field, and can only contain
		alphabetical characters [a-zA-Z].
		The {value} is any string, but cannot contain a <Tab>.
		These characters are special:
			"\t" stands for a <Tab>
			"\r" stands for a <CR>
			"\n" stands for a <NL>
			"\\" stands for a single '\' character
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item @{field@} ..
任意のフィールドのリスト。各フィールドは次の書式を持つ:
@example
<Tab>@{fieldname@}:@{value@}
@end example
@{fieldname@} はフィールドの識別子であり、アルファベットのみ使用可能である[a-zA-Z]。

@{value@} は任意の文字列であるが、<Tab> は使用できない。

以下の特殊文字が使用できる:
@multitable @columnfractions .99
@item "\t" は <Tab> を表す
@item "\r" は <CR> を表す
@item "\n" は <NL> を表す
@item "\\" は \ を表す
@end multitable
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
		There is one field that doesn't have a ':'.  This is the kind
		of the tag.  It is handled like it was preceded with "kind:".
		See the documentation of ctags for the kinds it produces.

		The only other field currently recognized by Vim is "file:"
		(with an empty value).  It is used for a static tag.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
':' を持たないフィールドがある。これはタグの一種である。"kind:" を先頭につけたものとして扱われる。kinds については、それを提供する ctags のドキュメントを参照。

現在 Vim が認識できるその他のフィールドは "file:" (値はなし)だけである。これは static タグに使われる。
@end table
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
The first lines in the tags file can contain lines that start with
	!_TAG_
These are sorted to the first lines, only rare tags that start with "!" can
sort to before them.  Vim recognizes two items.  The first one is the line
that indicates if the file was sorted.  When this line is found, Vim uses
binary searching for the tags file:
	!_TAG_FILE_SORTED<Tab>1<Tab>{anything} ~
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
tags ファイルの先頭行には、
@example
!_TAG_
@end example
で始まる行を含めることができる。これらは極稀な "!" で始まるタグを除けば先頭行にソートされる。Vim は 2 つのタグを認識する。1 つはファイルがソートされているかどうかを示す行で、この行が見つかった場合には、Vim は tags ファイルに対して二分探索を使用する:
@example
!_TAG_FILE_SORTED<TAB>1<TAB>@{anything@}
@end example
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
A tag file may be case-fold sorted to avoid a linear search when case is
ignored.  (Case is ignored when 'ignorecase' is set and 'tagcase' is
"followic", or when 'tagcase' is "ignore".)  See 'tagbsearch' for details.
The value '2' should be used then:
	!_TAG_FILE_SORTED<Tab>2<Tab>{anything} ~
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
大文字小文字を無視する設定の時、線形探索を避けるためにタグファイルは大文字小文字を区別せずにソートされることがある。 ('@option{ignorecase}' がセットされかつ '@option{tagcase}' が "@var{followic}" の時、または '@option{tagcase}' が "@var{ignore}" の時に大文字小文字は無視される。) 詳細は '@option{tagbsearch}' を参照のこと。その時、値として '2' が使われる:
@example
!_TAG_FILE_SORTED<TAB>2<TAB>@{anything@}
@end example
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
The other tag that Vim recognizes is the encoding of the tags file:
	!_TAG_FILE_ENCODING<Tab>utf-8<Tab>{anything} ~
Here "utf-8" is the encoding used for the tags.  Vim will then convert the tag
being searched for from 'encoding' to the encoding of the tags file.  And when
listing tags the reverse happens.  When the conversion fails the unconverted
tag is used.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
Vim が認識するもう 1 つのタグはタグファイルのエンコーディングを指定するものである:
@example
!_TAG_FILE_ENCODING<Tab>utf-8<Tab>@{anything@}
@end example
ここで "@var{utf-8}" はタグのエンコーディングである。Vim はタグを検索するときに検索するタグを '@option{encoding}' からタグファイルのエンコーディングに変換する。そして、タグをリストするときに元に戻す。変換が失敗したときは元のままのタグが使われる。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*tag-search*
The command can be any Ex command, but often it is a search command.
Examples:
	tag1	file1	/^main(argc, argv)/ ~
	tag2	file2	108 ~
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{tag-search}
@cindex tag-search
コマンドはどんな Ex コマンドでも使用可能であるが、検索コマンドがよく使われるであ
ろう。

例:
@verbatim
tag1    file1   /^main(argc, argv)/ ~
tag2    file2   108 ~
@end verbatim
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
The command is always executed with 'magic' not set.  The only special
characters in a search pattern are "^" (begin-of-line) and "$" (<EOL>).
See |pattern|.  Note that you must put a backslash before each backslash in
the search text.  This is for backwards compatibility with Vi.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
コマンドは常に 'magic' がセットされない状態で実行される。検索パターンで使用できる特殊文字は "^" (行頭) と "$" (<EOL>) だけである。|@ref{pattern}| を参照すること。検索文字列中のバックスラッシュの前にはバックスラッシュをつけなければならないことに注意すること。これは以前の Vi と互換性がある。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*E434* *E435*
If the command is a normal search command (it starts and ends with "/" or
"?"), some special handling is done:
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{E434}
@anchor{E435}
@erindex E434
@erindex E435
もしコマンドが普通の検索コマンド ("/" か "?" で始まり、終わる) であるならば、いくつかの特別な扱いをされる:
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
- Searching starts on line 1 of the file.
  The direction of the search is forward for "/", backward for "?".
  Note that 'wrapscan' does not matter, the whole file is always searched.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@itemize
@item 検索はファイルの 1 行目から開始する。

検索方向は "/" で前方、"?" で後方となる。'@option{wrapscan}' は問題にならず、いつもファイル全体を検索することに注意。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
- If the search fails, another try is done ignoring case.  If that fails too,
  a search is done for:
	"^tagname[ \t]*("
  (the tag with '^' prepended and "[ \t]*(" appended).  When using function
  names, this will find the function name when it is in column 0.  This will
  help when the arguments to the function have changed since the tags file was
  made.  If this search also fails another search is done with:
	"^[#a-zA-Z_].*\<tagname[ \t]*("
  This means: A line starting with '#' or an identifier and containing the tag
  followed by white space and a '('.  This will find macro names and function
  names with a type prepended.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item 検索が失敗した場合は、大文字小文字を無視してもう一度検索する。それも失敗した場合には次の検索が行われる:
@example
"^tagname[ \t]*("
@end example
(タグの先頭に '^'、末尾に "[ \t]*(" が追加される)。関数名の検索の場合には、これはカラム0の位置にある関数名を見つけるだろう。関数の引数がtagsファイルを作成したときから変更になったときなどに役立つだろう。この検索でも見つからない場合にはさらに次の検索が行われる:
@example
"^[#a-zA-Z_].*\<tagname[ \t]*("
@end example
この意味は: '#' もしくは識別子で始まり、空白文字と '(' が続くタグを含む行である。これは型が先頭にあるマクロ名や関数名を見つけるだろう。
@end itemize
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
							*tag-old-static*
Until March 2019 (patch 8.1.1092) an outdated format was supported:
    {tagfile}:{tagname} {TAB} {tagfile} {TAB} {tagaddress}
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{tag-old-static}
@cindex tag-old-static
旧式のフォーマットは 2019 年 3 月 (patch 8.1.1092) までサポートされていた:
@verbatim
{tagfile}:{tagname} {TAB} {tagfile} {TAB} {tagaddress}
@end verbatim
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
This format is for a static tag only.  It is obsolete now, replaced by
the second format.  It is only supported by Elvis 1.x, older Vim versions and
a few versions of ctags.  A static tag is often used for functions that are
local, only referenced in the file {tagfile}.  Note that for the static tag,
the two occurrences of {tagfile} must be exactly the same.  Also see
|tags-option| below, for how static tags are used.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
この形式は static タグにのみ使用できる。現在では廃れており、2 番目の形式に置き換えられている。これは Elvis 1.x と古いバージョンの Vim、それといくつかのバージョンの ctags によってのみサポートされている。static タグはローカル関数によく用いられ、@{tagfile@} 内のみ参照する。static タグでは 2 つの @{tagfile@} は正確に一致していなければならないことに注意すること。static タグがどのように使われるかについては |@option{tags-option}| を参照すること。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
The support was removed, since when you can update to the new Vim version you
should also be able to update ctags to one that supports the second format.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
新しいバージョンの Vim に更新するときに、2 番目の形式をサポートする ctags に更新できるべきでもあるので、このサポートは削除された。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
==============================================================================
6. Include file searches		*include-search* *definition-search*
							*E387* *E388* *E389*
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{include-search}
@anchor{definition-search}
@anchor{E387}
@anchor{E388}
@anchor{E389}
@cindex include-search
@cindex definition-search
@erindex E387
@erindex E388
@erindex E389
@cindex インクルードファイルの検索
@section 6. インクルードファイルの検索
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
These commands look for a string in the current file and in all encountered
included files (recursively).  This can be used to find the definition of a
variable, function or macro.  If you only want to search in the current
buffer, use the commands listed at |pattern-searches|.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
これらのコマンドは対象となる文字列を現在のファイルと、遭遇するすべてのインクルードファイルを再帰的に探す。これは変数や関数、マクロの定義を探すのに利用できる。現在のバッファに対してだけ検索をしたいのならば、|@ref{pattern-searches}| に列挙されているコマンドを使うとよい。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
These commands are not available when the |+find_in_path| feature was disabled
at compile time.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
これらのコマンドは、コンパイル時に |@ref{+find_in_path}| 機能を使用不可にした場合には利用できない。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
When a line is encountered that includes another file, that file is searched
before continuing in the current buffer.  Files included by included files are
also searched.  When an include file could not be found it is silently
ignored.  Use the |:checkpath| command to discover which files could not be
found, possibly your 'path' option is not set up correctly.  Note: the
included file is searched, not a buffer that may be editing that file.  Only
for the current file the lines in the buffer are used.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
他のファイルをインクルードする行に遭遇すると、現在のバッファを続けて検索する前にインクルードファイルを検索する。インクルードファイルによってインクルードされるファイルも同様に検索される。インクルードファイルが見つからなかった場合は黙って無視する。見つからなかったファイルを知りたいときは |@ref{:checkpath}| コマンドを使う。たぶん '@option{path}' オプションが正しく設定されていないのだろう。
@quotation
@strong{Note:} @*
インクルードファイルはファイルが検索され、そのファイルを編集中のバッファが存在しても対象にならない。バッファにある行は、現在のファイルにのみ適用される。
@end quotation
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
The string can be any keyword or a defined macro.  For the keyword any match
will be found.  For defined macros only lines that match with the 'define'
option will be found.  The default is "^#\s*define", which is for C programs.
For other languages you probably want to change this.  See 'define' for an
example for C++.  The string cannot contain an end-of-line, only matches
within a line are found.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
検索文字列は任意のキーワードや定義されたマクロが指定できる。キーワードの場合はマッチするものを見つける。定義されたマクロの場合は 'define' オプションにマッチする行だけが見つけられる。デフォルトは C プログラム用の "^#\s*define" である。他の言語の場合はおそらく変更したいだろう。C++ 用の例は 'define' を参照。その文字列に改行を含めることはできない。一行内にマッチするものだけが見つかる。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
When a match is found for a defined macro, the displaying of lines continues
with the next line when a line ends in a backslash.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
定義されたマクロが見つかった場合、行末がバックスラッシュのときは次の行も表示する。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
The commands that start with "[" start searching from the start of the current
file.  The commands that start with "]" start at the current cursor position.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
"[" で始まるコマンドは現在のファイルの先頭から検索を開始する。"]" で始まるコマンドは現在のカーソル位置から検索を開始する。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
The 'include' option is used to define a line that includes another file.  The
default is "\^#\s*include", which is for C programs.  Note: Vim does not
recognize C syntax, if the 'include' option matches a line inside
"#ifdef/#endif" or inside a comment, it is searched anyway.  The 'isfname'
option is used to recognize the file name that comes after the matched
pattern.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
'@option{include}' オプションは他のファイルをインクルードする行を定義する。デフォルトは C プログラム用の "\^#\s*include" である。
@quotation
@strong{Note:} @*
Vim は C の構文を認識しない。もし '@option{include}' オプションにマッチする行が "#ifdef/#endif" の間やコメント行であっても、とにかく検索される。'@option{isfname}' オプションはマッチパターンに続くファイル名を認識するために使用される。
@end quotation
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
The 'path' option is used to find the directory for the include files that
do not have an absolute path.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
'@option{path}' オプションは絶対パスを持たないインクルードファイルを探すためのディレクトリを指定する。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
The 'comments' option is used for the commands that display a single line or
jump to a line.  It defines patterns that may start a comment.  Those lines
are ignored for the search, unless [!] is used.  One exception: When the line
matches the pattern "^# *define" it is not considered to be a comment.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
'@option{comments}' オプションは単一行を表示するコマンド、もしくは行にジャンプするコマンドで使用される。これはコメントの開始パターンを定義する。それらの行は [!] を使用しない限り検索において無視される。ひとつの例外: 行が "^# *define" というパターンにマッチしたとき、コメントであるとはみなされない。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
If you want to list matches, and then select one to jump to, you could use a
mapping to do that for you.  Here is an example: >

  :map <F4> [I:let nr = input("Which one: ")<Bar>exe "normal " . nr ."[\t"<CR>
<
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
もしマッチしたリストを表示して、その中からジャンプ先を選択したいならば、マッピングが利用できる。例:
@example
:map <F4> [I:let nr = input("Which one: ")<Bar>exe "normal " . nr ."[\t"<CR>
@end example
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
							*[i*
[i			Display the first line that contains the keyword
			under the cursor.  The search starts at the beginning
			of the file.  Lines that look like a comment are
			ignored (see 'comments' option).  If a count is given,
			the count'th matching line is displayed, and comment
			lines are not ignored.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@table @asis
@anchor{[i}
@kindex [i
@item [i
カーソルの下にあるキーワードを含む 1 行を表示する。検索はファイルの先頭から開始する。コメントとみなせる行は無視される('@option{comments}' オプションを参照すること)。数字が与えられた場合は、先頭から指定した個数目にマッチした行を表示する。この場合はコメント行は無視されない。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*]i*
]i			like "[i", but start at the current cursor position.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{]i}
@kindex ]i
@item ]i
"[i" と同様だが、検索が現在のカーソル位置から開始される。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*:is* *:isearch*
:[range]is[earch][!] [count] [/]pattern[/]
			Like "[i"  and "]i", but search in [range] lines
			(default: whole file).
			See |:search-args| for [/] and [!].
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{:is}
@anchor{:isearch}
@pindex :is
@pindex :isearch
@item :[range]is[earch][!] [count] [/]pattern[/]
"[i" や "]i" と同様だが、[range] で指定された範囲から検索する (デフォルト: ファイル全体)。

[/] と [!] については |@ref{:search-args}| を参照。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*[I*
[I			Display all lines that contain the keyword under the
			cursor.  Filenames and line numbers are displayed
			for the found lines.  The search starts at the
			beginning of the file.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{[I}
@kindex [I
@item [I
カーソルの下にあるキーワードを含む行をすべて表示する。結果にはファイル名と行番号が表示される。検索はファイルの先頭から開始される。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*]I*
]I			like "[I", but start at the current cursor position.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{]I}
@kindex ]I
@item ]I
"[I" と同様だが、検索が現在のカーソル位置から開始される。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*:il* *:ilist*
:[range]il[ist][!] [/]pattern[/]
			Like "[I" and "]I", but search in [range] lines
			(default: whole file).
			See |:search-args| for [/] and [!].
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{:il}
@anchor{:ilist}
@pindex :il
@pindex :ilist
@item :[range]il[ist][!] [/]pattern[/]
"[I" や "]I" と同様だが、[range] で指定された範囲から検索する (デフォルト: ファイル全体)。

[/] と [!] については |@ref{:search-args}| を参照。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*[_CTRL-I*
[ CTRL-I		Jump to the first line that contains the keyword
			under the cursor.  The search starts at the beginning
			of the file.  Lines that look like a comment are
			ignored (see 'comments' option).  If a count is given,
			the count'th matching line is jumped to, and comment
			lines are not ignored.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{[_CTRL-I}
@kindex [_CTRL-I
@item [ CTRL-I
カーソルの下にあるキーワードを含む最初の 1 行にジャンプする。検索はファイルの先頭から開始する。コメントとみなせる行は無視される ('@option{comments}' オプションを参照すること)。数字が与えられた場合は、先頭から指定した個数目にマッチした行にジャンプする。この場合はコメント行は無視されない。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*]_CTRL-I*
] CTRL-I		like "[ CTRL-I", but start at the current cursor
			position.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{]_CTRL-I}
@kindex ]_CTRL-I
@item ] CTRL-I
"[ CTRL-I" と同様だが、検索が現在のカーソル位置から開始される。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*:ij* *:ijump*
:[range]ij[ump][!] [count] [/]pattern[/]
			Like "[ CTRL-I"  and "] CTRL-I", but search in
			[range] lines (default: whole file).
			See |:search-args| for [/] and [!].
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{:ij}
@anchor{:ijump}
@pindex :ij
@pindex :ijump
@item :[range]ij[ump][!] [count] [/]pattern[/]
"[ CTRL-I" や "] CTRL-I" と同様だが、[range] で指定された範囲から検索する(デフォルト: ファイル全体)。

[/] と [!] については |@ref{:search-args}| を参照。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
CTRL-W CTRL-I					*CTRL-W_CTRL-I* *CTRL-W_i*
CTRL-W i		Open a new window, with the cursor on the first line
			that contains the keyword under the cursor.  The
			search starts at the beginning of the file.  Lines
			that look like a comment line are ignored (see
			'comments' option).  If a count is given, the count'th
			matching line is jumped to, and comment lines are not
			ignored.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{CTRL-W_CTRL-I}
@anchor{CTRL-W_i}
@kindex CTRL-W_CTRL-I
@kindex CTRL-W_i
@item @kbd{CTRL-W} @kbd{CTRL-I} または
@itemx @kbd{CTRL-W} i
新しいウィンドウを開き、カーソルの下にあったキーワードを含む最初の 1 行に移動する。検索はファイルの先頭から開始する。コメントとみなせる行は無視される('@option{comments}' オプションを参照すること)。数字が与えられた場合は、先頭から指定した個数目にマッチした行にジャンプする。この場合はコメント行は無視されない。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*:isp* *:isplit*
:[range]isp[lit][!] [count] [/]pattern[/]
			Like "CTRL-W i"  and "CTRL-W i", but search in
			[range] lines (default: whole file).
			See |:search-args| for [/] and [!].
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{:isp}
@anchor{:isplit}
@pindex :isp
@pindex :isplit
@item :[range]isp[lit][!] [count] [/]pattern[/]
"CTRL-W i" や "CTRL-W i" と同様だが、[range] で指定された範囲から検索する(デフォルト: ファイル全体)。

[/] と [!] については |@ref{:search-args}| を参照。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*[d*
[d			Display the first macro definition that contains the
			macro under the cursor.  The search starts from the
			beginning of the file.  If a count is given, the
			count'th matching line is displayed.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{[d}
@kindex [d
@item [d
カーソルの下にあるマクロを含む最初のマクロ定義を表示する。検索はファイルの先頭から開始する。数字が与えられた場合は、先頭から指定した個数目にマッチした行を表示する。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*]d*
]d			like "[d", but start at the current cursor position.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{]d}
@kindex ]d
@item ]d
"[d" と同様だが、検索が現在のカーソル位置から開始される。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*:ds* *:dsearch*
:[range]ds[earch][!] [count] [/]string[/]
			Like "[d"  and "]d", but search in [range] lines
			(default: whole file).
			See |:search-args| for [/] and [!].
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{:ds}
@anchor{:dsearch}
@pindex :ds
@pindex :dsearch
@item :[range]ds[earch][!] [count] [/]string[/]
"[d" や "]d" と同様だが、[range] で指定された範囲から検索する(デフォルト: ファイル全体)。

[/] と [!] については |@ref{:search-args}| を参照。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*[D*
[D			Display all macro definitions that contain the macro
			under the cursor.  Filenames and line numbers are
			displayed for the found lines.  The search starts
			from the beginning of the file.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{[D}
@kindex [D
@item [D
カーソルの下にあるマクロを含むすべてのマクロ定義を表示する。結果にはファイル名と行番号が表示される。検索はファイルの先頭から開始される。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*]D*
]D			like "[D", but start at the current cursor position.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{]D}
@kindex ]D
@item ]D
"[D" と同様だが、検索が現在のカーソル位置から開始される。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*:dli* *:dlist*
:[range]dli[st][!] [/]string[/]
			Like `[D`  and `]D`, but search in [range] lines
			(default: whole file).
			See |:search-args| for [/] and [!].
			Note that `:dl` works like `:delete` with the "l"
			flag, not `:dlist`.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{:dli}
@anchor{:dlist}
@pindex :dli
@pindex :dlist
@item :[range]dli[st][!] [/]string[/]
`[D` や `]D` と同様だが、[range] で指定された範囲から検索する (デフォルト: ファイル全体)。

[/] と [!] については |@ref{:search-args}| を参照。
@quotation
@strong{Note:} @*
`@command{:dl}` は `@command{:dlist}` ではなく、`@command{:delete}` に "l" レジスタを指定したものとして機能する。
@end quotation
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*[_CTRL-D*
[ CTRL-D		Jump to the first macro definition that contains the
			keyword under the cursor.  The search starts from
			the beginning of the file.  If a count is given, the
			count'th matching line is jumped to.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{[_CTRL-D}
@kindex [_CTRL-D
@item [ @kbd{CTRL-D}
カーソルの下にあるキーワードを含む最初のマクロ定義にジャンプする。検索はファイルの先頭から開始する。数字が与えられた場合は、先頭から指定した個数目にマッチした行にジャンプする。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*]_CTRL-D*
] CTRL-D		like "[ CTRL-D", but start at the current cursor
			position.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{]_CTRL-D}
@kindex ]_CTRL-D
@item ] @kbd{CTRL-D}
"[ CTRL-D" と同様だが、検索が現在のカーソル位置から開始される。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*:dj* *:djump*
:[range]dj[ump][!] [count] [/]string[/]
			Like "[ CTRL-D"  and "] CTRL-D", but search  in
			[range] lines (default: whole file).
			See |:search-args| for [/] and [!].
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{:dj}
@anchor{:djump}
@pindex :dj
@pindex :djump
@item :[range]dj[ump][!] [count] [/]string[/]
"[ CTRL-D" や "] CTRL-D" と同様だが、[range] で指定された範囲から検索する (デフォルト: ファイル全体)。

[/] と [!] については |@ref{:search-args}| を参照。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
CTRL-W CTRL-D					*CTRL-W_CTRL-D* *CTRL-W_d*
CTRL-W d		Open a new window, with the cursor on the first
			macro definition line that contains the keyword
			under the cursor.  The search starts from the
			beginning of the file.  If a count is given, the
			count'th matching line is jumped to.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{CTRL-W_CTRL-D}
@anchor{CTRL-W_d}
@kindex CTRL-W_CTRL-D
@kindex CTRL-W_d
@item @kbd{CTRL-W} @kbd{CTRL-D} または
@itemx @kbd{CTRL-W} d
新しいウィンドウを開き、カーソルの下にあったキーワードを含む最初のマクロ定義に移動する。検索はファイルの先頭から開始する。数字が与えられた場合は、先頭から指定した個数目にマッチした行にジャンプする。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*:dsp* *:dsplit*
:[range]dsp[lit][!] [count] [/]string[/]
			Like "CTRL-W d", but search in [range] lines
			(default: whole file).
			See |:search-args| for [/] and [!].
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{:dsp}
@anchor{:dsplit}
@pindex :dsp
@pindex :dsplit
@item :[range]dsp[lit][!] [count] [/]string[/]
"CTRL-W d" と同様だが、[range] で指定された範囲から検索する (デフォルト: ファイル全体)。

[/] と [!] については |@ref{:search-args}| を参照。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
					*:che* *:chec* *:check* *:checkpath*
:che[ckpath]		List all the included files that could not be found.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{:che}
@anchor{:chec}
@anchor{:check}
@anchor{:checkpath}
@pindex :che
@pindex :chec
@pindex :check
@pindex :checkpath
@item :che[ckpath]
ファイルが見つからないすべてのインクルードファイル名をリスト表示する。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
:che[ckpath]!		List all the included files.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item :che[ckpath]!
すべてのインクルードファイル名をリスト表示する。
@end table
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
								*:search-args*
Common arguments for the commands above:
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{:search-args}
@cindex :search-args
上記コマンドに共通の引数:
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
[!]	When included, find matches in lines that are recognized as comments.
	When excluded, a match is ignored when the line is recognized as a
	comment (according to 'comments'), or the match is in a C comment
	(after "//" or inside /* */).  Note that a match may be missed if a
	line is recognized as a comment, but the comment ends halfway the line.
	And if the line is a comment, but it is not recognized (according to
	'comments') a match may be found in it anyway.  Example: >
		/* comment
		   foobar */
<	A match for "foobar" is found, because this line is not recognized as
	a comment (even though syntax highlighting does recognize it).
	Note: Since a macro definition mostly doesn't look like a comment, the
	[!] makes no difference for ":dlist", ":dsearch" and ":djump".
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@table @asis
@item [!]
使用した場合は、コメントとみなせる行に対しても検索をする。使用しなかった場合は '@option{comments}' によってコメントとみなされる行や C コメント("//" の後ろか /* */ の間)にあるものは無視される。コメントとみなされた行が、途中からコメントでなくなるようなときは見逃すかもしれないことに注意。

また、コメント行であっても、('@option{comments}' によって) 認識されないでとにかくマッチするかもしれない。例:
@verbatim
/* comment
foobar */
@end verbatim
"foobar" に対する検索はマッチする。これは行がコメントとして認識されないためである(たとえ構文強調表示が認識したとしても)。
@quotation
@strong{Note:} @*
マクロ定義はたいていコメントと誤認されることはないので、"@command{:dlist}" や "@command{:dsearch}"、"@command{:djump}" に [!] を使用することは大差がない。
@end quotation
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
[/]	A pattern can be surrounded by '/'.  Without '/' only whole words are
	matched, using the pattern "\<pattern\>".  Only after the second '/' a
	next command can be appended with '|'.  Example: >
	:isearch /string/ | echo "the last one"
<	For a ":djump", ":dsplit", ":dlist" and ":dsearch" command the pattern
	is used as a literal string, not as a search pattern.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item [/]
パターンは '/' で囲むことができる。'/' なしの場合、"\<pattern\>" というパターンを使うことによって、完全な語だけがマッチする。2 つ目の '/' の後にだけ、'|' を使うことによって次のコマンドを追加できる。例:
@example
:isearch /string/ | echo "the last one"
@end example
"@command{:djump}", "@command{:dsplit}", "@command{:dlist}", "@command{:dsearch}" コマンドではパターンは検索パターンとしてではなく文字通りに使われる。
@end table
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
==============================================================================
7. Using 'tagfunc'						*tag-function*
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{tag-function}
@cindex tag-function
@section 7. '@option{tagfunc}' を使う
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
It is possible to provide Vim with a function which will generate a list of
tags used for commands like |:tag|, |:tselect| and Normal mode tag commands
like |CTRL-]|.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
|@ref{:tag}|、|@ref{:tselect}| のようなコマンド、および |@ref{CTRL-]}| のようなノーマルモードタグコマンドに使われるタグのリストを生成する関数を Vim に提供することが可能である。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
The function used for generating the taglist is specified by setting the
'tagfunc' option.  The function will be called with three arguments:
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
タグリストの生成に使用される関数は、'@option{tagfunc}' オプションを設定することによって指定される。関数は 3 つの引数で呼び出される:
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
   a:pattern	The tag identifier used during the tag search.
   a:flags	List of flags to control the function behavior.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@itemize
@item a:pattern タグ検索中に使用されたタグ識別子。
@item a:flags   関数の挙動を制御するためのフラグのリスト。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
   a:info	Dict containing the following entries:
		    buf_ffname	  Full filename which can be used for priority.
		    user_data	  Custom data String, if stored in the tag
				  stack previously by tagfunc.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item  a:info   以下のエントリを含む辞書:
@multitable @columnfractions .3 .7
@item buf_ffname @tab 優先順位のために使用できる完全ファイル名。
@item user_data @tab カスタムデータ文字列。以前の tagfunc によってタグスタックに格納されている場合。
@end multitable
@end itemize
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Currently two flags may be passed to the tag function:
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
現在、タグ関数には 2 つのフラグを渡すことができる:
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
  'c'		The function was invoked by a normal command being processed
	        (mnemonic: the tag function may use the context around the
		cursor to perform a better job of generating the tag list.)
  'i'		In Insert mode, the user was completing a tag (with
		|i_CTRL-X_CTRL-]|).
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@multitable @columnfractions .1 .9
@item 'c' @tab この関数は、処理中の通常のコマンドによって呼び出された。(ニーモニック: タグ関数は、カーソルの周りのコンテキストを使用して、タグリストを生成するためのより良い作業を実行できる。)
@item 'i' @tab 挿入モードで、ユーザーはタグを補完していた (|@ref{i_CTRL-X_CTRL-]}| で)
@end multitable
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Note that when 'tagfunc' is set, the priority of the tags described in
|tag-priority| does not apply.  Instead, the priority is exactly as the
ordering of the elements in the list returned by the function.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@quotation
@strong{Note:} @*
'@option{tagfunc}' が設定されている場合、|@ref{tag-priority}| に記述されているタグの優先順位は適用されない。代わりに、優先順位は、関数によって返されるリスト内の要素の順序とまったく同じである。
@end quotation
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
								*E987*
The function should return a List of Dict entries.  Each Dict must at least
include the following entries and each value must be a string:
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{E987}
@erindex E987
関数は辞書エントリのリストを返すべきである。各辞書は少なくとも次のエントリを含み、各値は文字列でなければならない:
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
	name		Name of the tag.
	filename	Name of the file where the tag is defined.  It is
			either relative to the current directory or a full path.
	cmd		Ex command used to locate the tag in the file.  This
			can be either an Ex search pattern or a line number.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@multitable @columnfractions .2 .8
@item name @tab タグ名。
@item filename @tab タグが定義されているファイルの名前。カレントディレクトリからの相対パスか、フルパスのどちらかである。
@item cmd @tab ファイル内のタグを見つけるために使用される Ex コマンド。これはEx検索パターンまたは行番号のどちらかである。
@end multitable
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
Note that the format is similar to that of |taglist()|, which makes it possible
to use its output to generate the result.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@quotation
@strong{Note:} @*
フォーマットは |@ref{taglist()}| のものと似ており、これにより、結果を生成するためにその出力を使用することが可能になる。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
The following fields are optional:
	kind		Type of the tag.
	user_data	String of custom data stored in the tag stack which
			can be used to disambiguate tags between operations.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
以下のフィールドはオプションである:
@multitable @columnfractions .2 .8
@item kind @tab タグの種類。
@item user_data @tab オペレーション間でタグの曖昧さを解消するために使用できる、タグスタックに格納されたカスタムデータの文字列。
@end multitable
@end quotation
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
If the function returns |v:null| instead of a List, a standard tag lookup will
be performed instead.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
関数がリストの代わりに、|@ref{v:null}| を返した場合、標準のタグ検索が代わりに実行される。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
It is not allowed to change the tagstack from inside 'tagfunc'.  *E986*
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{E986}
@erindex E986
タグスタックを '@option{tagfunc}' の内部から変更することはできない。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
The following is a hypothetical example of a function used for 'tagfunc'.  It
uses the output of |taglist()| to generate the result: a list of tags in the
inverse order of file names.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
以下は、'@option{tagfunc}' に使用される関数の仮定の例である。結果 (ファイル名の逆順のタグのリスト) を生成するために |@ref{taglist()}| の出力を使用している。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
>
	function! TagFunc(pattern, flags, info)
	  function! CompareFilenames(item1, item2)
	    let f1 = a:item1['filename']
	    let f2 = a:item2['filename']
	    return f1 >=# f2 ?
			\ -1 : f1 <=# f2 ? 1 : 0
	  endfunction

	  let result = taglist(a:pattern)
	  call sort(result, "CompareFilenames")

	  return result
	endfunc
	set tagfunc=TagFunc
<
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@verbatim
function! TagFunc(pattern, flags, info)
  function! CompareFilenames(item1, item2)
    let f1 = a:item1['filename']
    let f2 = a:item2['filename']
    return f1 >=# f2 ?
                \ -1 : f1 <=# f2 ? 1 : 0
  endfunction

  let result = taglist(a:pattern)
  call sort(result, "CompareFilenames")

  return result
endfunc
set tagfunc=TagFunc
@end verbatim
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
 vim:tw=78:ts=8:noet:ft=help:norl:
@end ifset
