@ifset JA  @c ----------- v -----------  JA  -*- tab-width: 8 -*-
@node workshop.txt, , , 目次
@unnumbered Sun Visual Workshop インターフェイス
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
*workshop.txt*  For Vim version 8.1.  Last change: 2019 Jan 17


		  VIM REFERENCE MANUAL    by Gordon Prieur
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@verbatim
*workshop.txt*  For Vim バージョン 8.1.  Last change: 2019 Jan 17


                VIM リファレンスマニュアル    by Gordon Prieur
@end verbatim
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
Sun Visual WorkShop Features			*workshop* *workshop-support*
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{workshop}
@anchor{workshop-support}
@cindex workshop
@cindex workshop-support
Sun Visual WorkShop との連携機能
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
The support for WorkShop was removed in patch 8.1.0763 in January 2019.
The product has not been available for a long time and has been replaced by
|NetBeans|.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
WorkShop のサポートは、2019 年 1 月の patch 8.1.0763 で削除された。
この製品は長い間入手できず、|@ref{NetBeans}| に置き換えられた。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
 vim:tw=78:ts=8:noet:ft=help:norl:
@end ifset
