@ifset JA  @c ----------- v -----------  JA  -*- tab-width: 8 -*-
@node arabic.txt, , , 目次
@unnumbered アラビア語のサポート
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
*arabic.txt*	For Vim version 8.1.  Last change: 2019 May 05


		  VIM REFERENCE MANUAL	  by Nadim Shaikli
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@verbatim
*arabic.txt*    For Vim バージョン 8.1.  Last change: 2019 May 05


                  VIMリファレンスマニュアル       by Nadim Shaikli
@end verbatim
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
Arabic Language support (options & mappings) for Vim		*Arabic*
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{Arabic}
@cindex Arabic
アラビア語サポート (オプション & マッピング)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
								*E800*
In order to use right-to-left and Arabic mapping support, it is
necessary to compile Vim with the |+arabic| feature.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{E800}
@erindex E800
right-to-left (右横書き) とアラビア語マッピングを使用するには、Vim を |@ref{+arabic}| 機能付きでコンパイルする必要があります。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
These functions have been created by Nadim Shaikli <nadim-at-arabeyes.org>
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
これらの機能は Nadim Shaikli <nadim-at-arabeyes.org> によって作成されました。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
It is best to view this file with these settings within Vim's GUI: >

	:set encoding=utf-8
	:set arabicshape
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
このファイルは GUI の Vim で以下の設定をして表示するのが最適です:
@example
:set encoding=utf-8
:set arabicshape
@end example
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
Introduction
------------
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@unnumberedsec はじめに
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
Arabic is a rather demanding language in which a number of special
features are required.	Characters are right-to-left oriented and
ought to appear as such on the screen (i.e. from right to left).
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
アラビア語はいくつかの特殊な機能を必要とする言語です。文字は右から左へ向かうのでスクリーン上でもそのように表示する必要があります (つまり右から左へ表示する)。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
Arabic also requires shaping of its characters, meaning the same
character has a different visual form based on its relative location
within a word (initial, medial, final or stand-alone).	Arabic also
requires two different forms of combining and the ability, in
certain instances, to either superimpose up to two characters on top
of another (composing) or the actual substitution of two characters
into one (combining).  Lastly, to display Arabic properly one will
require not only ISO-8859-6 (U+0600-U+06FF) fonts, but will also
require Presentation Form-B (U+FE70-U+FEFF) fonts both of which are
subsets within a so-called ISO-10646-1 font.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------

アラビア語は文字変形 (shaping) も必要とします。文字を書く位置によって同じ文字でも別の字形になります (単語の最初、中、最後、または単独で書くかで変わる)。アラビア語は二種類の文字合成も必要とします。場合によっては、1 つの文字に他の文字を最大 2 つまで重ねる (合成、composing) か、2 つの文字を 1 つの文字に置換する (結合、combining) かします。

アラビア語を適切に表示するには ISO-8859-6 (U+0600-U+06FF) のフォントに加えて Presentation Form-B (U+FE70-U+FEFF) のフォントも必要です。これらはいわゆる ISO-10646-1 フォントのサブセットです。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
The commands, prompts and help files are not in Arabic, therefore
the user interface remains the standard Vi interface.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
コマンド、プロンプト、ヘルプファイルはアラビア語にはなりません。したがってユーザーインターフェイスは標準の Vi インターフェイスのままです。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
Highlights
----------
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@unnumberedsec 特徴
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
o  Editing left-to-right files as in the original Vim hasn't changed.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@itemize
@item left-to-right ファイルの編集はオリジナルの VIM と変わりません。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  Viewing and editing files in right-to-left windows.	 File
   orientation is per window, so it is possible to view the same
   file in right-to-left and left-to-right modes, simultaneously.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item right-to-left ウィンドウでのファイルの表示と編集。表示方向はウィンドウ単位なので、同じファイルを right-to-left と left-to-right で同時に表示できます。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  No special terminal with right-to-left capabilities is required.
   The right-to-left changes are completely hardware independent.
   Only Arabic fonts are necessary.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item right-to-left のための特殊な端末を必要としない。right-to-left の機能はハードウェアに依存していません。必要なのはアラビア語フォントだけです。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  Compatible with the original Vim.   Almost all features work in
   right-to-left mode (there are liable to be bugs).
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item オリジナルの VIM との互換性。ほとんどの機能は right-to-left モードでも機能します (バグになりやすい)。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  Changing keyboard mapping and reverse insert modes using a single
   command.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item キーボードマッピングと反転挿入モード (reverse insert mode) を 1 つのコマンドで切り替える。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  Toggling complete Arabic support via a single command.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item アラビア語サポートを 1 つのコマンドで切り替える。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  While in Arabic mode, numbers are entered from left to right.  Upon
   entering a none number character, that character will be inserted
   just into the left of the last number.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item アラビア語モードでは数字は左から右へ入力されます。その後で数字以外の文字を入力すると、その文字は数字の一番左側に挿入されます。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  Arabic keymapping on the command line in reverse insert mode.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item 反転挿入モードでのコマンドラインのアラビア語キーマッピング。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  Proper Bidirectional functionality is possible given Vim is
   started within a Bidi capable terminal emulator.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item 正式な双方向機能は VIM を双方向対応端末エミュレータ上で実行すれば利用可能です。
@end itemize
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
Arabic Fonts						*arabicfonts*
------------
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{arabicfonts}
@cindex arabicfonts
@cindex アラビア語フォント
@unnumberedsec アラビア語フォント
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Vim requires monospaced fonts of which there are many out there.
Arabic requires ISO-8859-6 as well as Presentation Form-B fonts
(without Form-B, Arabic will _NOT_ be usable).	It is highly
recommended that users search for so-called 'ISO-10646-1' fonts.
Do an Internet search or check www.arabeyes.org for further
info on where to attain the necessary Arabic fonts.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
VIM は固定幅フォントを使います。アラビア語には ISO-8859-6 と Presentation Form-B のフォントが必要です (Form-B 無しではアラビア語は使用できない)。フォントを探す際にはいわゆる 'ISO-10646-1' フォントを探してください。インターネットを検索するか @url{www.arabeyes.org} を見て必要なアラビア語フォントを手に入れてください。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
Font Installation
-----------------
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@unnumberedsec フォントのインストール
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  Installation of fonts for X Window systems (Unix/Linux)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@unnumberedsubsec X ウィンドウシステム (Unix/Linux) でのフォントのインストール
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
   Depending on your system, copy your_ARABIC_FONT file into a
   directory of your choice.  Change to the directory containing
   the Arabic fonts and execute the following commands:
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
システムによって違いますが、アラビア語フォントのファイルを適当なディレクトリにコピーします。そのアラビア語フォントをコピーしたディレクトリに移動して次のコマンドを実行します:
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
     %	mkfontdir
     %	xset +fp path_name_of_arabic_fonts_directory
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@verbatim
% mkfontdir
% xset +fp path_name_of_arabic_fonts_directory
@end verbatim
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
Usage
-----
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@unnumberedsec 使用方法
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
Prior to the actual usage of Arabic within Vim, a number of settings
need to be accounted for and invoked.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
実際に Vim でアラビア語を使用する前に、しなければならない設定がいくつかあります。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  Setting the Arabic fonts
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@unnumberedsubsec アラビア語フォントを設定する
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
   +  For Vim GUI set the 'guifont' to your_ARABIC_FONT.  This is done
      by entering the following command in the Vim window.
>
		:set guifont=your_ARABIC_FONT
<
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@itemize
@item VIM GUI で '@option{guifont}' をアラビア語フォントに設定します。VIM ウィンドウで次のように入力します。
@example
:set guifont=your_ARABIC_FONT
@end example
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
      NOTE: the string 'your_ARABIC_FONT' is used to denote a complete
	    font name akin to that used in Linux/Unix systems.
	    (e.g. -misc-fixed-medium-r-normal--20-200-75-75-c-100-iso10646-1)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@quotation
@strong{Note:} @*
'your_ARABIC_FONT' の部分には Linux/Unix システムで使用されている 実際のフォント名を入れてください。

(例: -misc-fixed-medium-r-normal--20-200-75-75-c-100-iso10646-1)
@end quotation
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
      You can append the 'guifont' set command to your .vimrc file
      in order to get the same above noted results.  In other words,
      you can include ':set guifont=your_ARABIC_FONT' to your .vimrc
      file.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
'@option{guifont}' の設定を @file{.vimrc} ファイルに書くこともできます。言い換えると、':set guifont=your_ARABIC_FONT' を @file{.vimrc} ファイルに書くことができます。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
   +  Under the X Window environment, you can also start Vim with
      '-fn your_ARABIC_FONT' option.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item X ウィンドウ環境では、'-fn your_ARABIC_FONT' を VIM の起動引数に指定する方法もあります。
@end itemize
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  Setting the appropriate character Encoding
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@unnumberedsubsec 適切なエンコーディングを設定する
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
   To enable the correct Arabic encoding the following command needs
   to be appended,
>
		:set encoding=utf-8
<
   to your .vimrc file (entering the command manually into you Vim
   window is highly discouraged).  In short, include ':set
   encoding=utf-8' to your .vimrc file.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
アラビア語に適したエンコーディングを設定するには次のコマンドを @file{.vimrc} ファイルに追加します。
@example
:set encoding=utf-8
@end example
(このコマンドを VIM ウィンドウで直接実行しないでください)

簡単に言えば ':set encoding=utf-8' を @file{.vimrc} ファイルに書くだけです。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
   Attempts to use Arabic without UTF-8 will result the following
   warning message,

								*W17*  >
     Arabic requires UTF-8, do ':set encoding=utf-8'
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
アラビア語を UTF-8 以外のエンコーディングで使用すると次の警告メッセージが表示されます。
@anchor{W17}
@erindex W17
@display
Arabic requires UTF-8, do ':set encoding=utf-8'
@end display
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  Enable Arabic settings [short-cut]
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@unnumberedsubsec アラビア語設定の有効化 [近道]
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
   In order to simplify and streamline things, you can either invoke
   Vim with the command-line option,

     % vim -A my_utf8_arabic_file ...
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
手っ取り早く設定するには、コマンドラインから次のようにして VIM を起動するか、
@example
% vim -A my_utf8_arabic_file ...
@end example
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
   or enable 'arabic' via the following command within Vim
>
		:set arabic
<
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
または VIM の中で次のコマンドを実行して '@option{arabic}' を有効にします
@example
:set arabic
@end example
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
   The two above noted possible invocations are the preferred manner
   in which users are instructed to proceed.  Barring an enabled 'termbidi'
   setting, both command options:
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
これが最も簡単な方法です。'@option{termbidi}' が有効化されていなければ、次の設定が実行されます:
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
     1. set the appropriate keymap
     2. enable the deletion of a single combined pair character
     3. enable rightleft    mode
     4. enable rightleftcmd mode (affecting the command-line)
     5. enable arabicshape  mode (do visual character alterations)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@enumerate
@item 適切なキーマップを設定する
@item 合成文字を一度で削除できるようにする
@item rightleft モードを有効にする
@item rightleftcmd モードを有効にする (コマンドラインに作用する)
@item arabicshape モードを有効にする (表示文字を変更する)
@end enumerate
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
   You may also append the command to your .vimrc file and simply
   include ':set arabic' to it.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@file{.vimrc} ファイルに ':set arabic' を書いておくこともできます。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
   You are also capable of disabling Arabic support via
>
		:set noarabic
<
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
次のコマンドでアラビア語サポートを無効化できます
@example
:set noarabic
@end example
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
   which resets everything that the command had enabled without touching
   the global settings as they could affect other possible open buffers.
   In short the 'noarabic' command,
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
コマンドによって有効にされた設定がすべてリセットされます。他のバッファに影響があるようなグローバル設定は変更されません。簡単に言えば '@command{noarabic}' コマンドによって次の設定が実行されます:
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
     1. resets to the alternate keymap
     2. disables the deletion of a single combined pair character
     3. disables rightleft mode
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@enumerate
@item キーマップ切替をリセットする
@item 合成文字を一度で削除できる機能を無効化にする
@item rightleft モードを無効化する
@end enumerate
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
   NOTE: the 'arabic' command takes into consideration 'termbidi' for
	 possible external bi-directional (bidi) support from the
	 terminal ("mlterm" for instance offers such support).
	 'termbidi', if available, is superior to rightleft support
	 and its support is preferred due to its level of offerings.
	 'arabic' when 'termbidi' is enabled only sets the keymap.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@quotation
@strong{Note:} @*
'@command{arabic}' コマンドは '@option{termbidi}' を見て端末が双方向テキスト (bi-directional, bidi) をサポートしているかどうかを考慮します (例えば "mlterm" がサポートしています)。

'@option{termbidi}' が利用できる場合は、rightleft のサポートが優れているそちらの使用をお勧めします。

'@option{termbidi}' が有効な場合は '@command{arabic}' はキーマップのみ設定します。
@end quotation
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
   If, on the other hand, you'd like to be verbose and explicit and
   are opting not to use the 'arabic' short-cut command, here's what
   is needed (i.e. if you use ':set arabic' you can skip this section) -
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
もし、冗長で明示的な方法が好きで、'@command{arabic}' コマンドを使って近道をしたくないという場合は、以下の説明を読んでください (':set arabic' を使用する方はこの節は飛ばして構いません)。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
   +  Arabic Keymapping Activation
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@unnumberedsubsec アラビア語キーマッピングの有効化
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
      To activate the Arabic keymap (i.e. to remap your English/Latin
      keyboard to look-n-feel like a standard Arabic one), set the
      'keymap' command to "arabic".  This is done by entering
>
		:set keymap=arabic
<
      in your Vim window.  You can also append the 'keymap' set command to
      your .vimrc file.  In other words, you can include ':set keymap=arabic'
      to your .vimrc file.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
アラビア語キーマップを有効可するには (つまり English/Latin キーボードを標準のアラビア語キーボードのようにするには)、'@command{keymap}' コマンドを "arabic" に設定します。VIM ウィンドウで次のように入力します
@example
:set keymap=arabic
@end example
'@command{keymap}' 設定コマンドを @file{.vimrc} ファイルに書くこともできます。言い換えれば、@file{.vimrc} ファイルに ':set keymap=arabic' を含めることができます。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
      To turn toggle (or switch) your keymapping between Arabic and the
      default mapping (English), it is advised that users use the 'CTRL-^'
      key press while in insert (or add/replace) mode.	The command-line
      will display your current mapping by displaying an "Arabic" string
      next to your insertion mode (e.g. -- INSERT Arabic --) indicating
      your current keymap.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
アラビア語のキーマッピングとデフォルト (English) のキーマッピングを切り替えるには、挿入モード (または追加/置換モード) で '@kbd{CTRL-^}' キーを押します。コマンドラインのモード表示の隣に "Arabic" の文字列が表示され (例: -- INSERT Arabic --)、それが現在のキーマップを示します。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
   +  Arabic deletion of a combined pair character
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@unnumberedsubsec 合成文字の削除
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
      By default Vim has the 'delcombine' option disabled.  This option
      allows the deletion of ALEF in a LAM_ALEF (LAA) combined character
      and still retain the LAM (i.e. it reverts to treating the combined
      character as its natural two characters form -- this also pertains
      to harakat and their combined forms).  You can enable this option
      by entering
>
		:set delcombine
<
      in our Vim window.  You can also append the 'delcombine' set command
      to your .vimrc file.  In other words, you can include ':set delcombine'
      to your .vimrc file.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
初期設定では '@option{delcombine}' オプションは無効化されています。このオプションは LAM_ALEF (LAA) 合成文字内の ALEF を削除し、LAM だけを残すことを可能にします (つまり合成文字を解除して元の字形に戻す。これは harakat とその合成字形にも関係する)。このオプションを有効化するには VIM ウィンドウで次のように入力します
@example
:set delcombine
@end example
'@option{delcombine}' の設定コマンドを @file{.vimrc} ファイルに書くこともできます。言い換えれば、@file{.vimrc} ファイルに ':set delcombine' を含めることができます。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
   +  Arabic right-to-left Mode
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@unnumberedsubsec アラビア語 right-to-left モード
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
      By default Vim starts in Left-to-right mode.  'rightleft' is the
      command that allows one to alter a window's orientation - that can
      be accomplished via,
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
初期設定では VIM は left-to-right モードで起動します。'@option{rightleft}' を設定することでウィンドウの方向を変更できます。使用方法は次のとおり。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
      - Toggling between left-to-right and right-to-left modes is
	accomplished through ':set rightleft' and ':set norightleft'.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@itemize
@item left-to-right モードと right-to-left モードの切り替えは ':set rightleft' と ':set norightleft' でできます。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
      - While in Left-to-right mode, enter ':set rl' in the command line
	('rl' is the abbreviation for rightleft).
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item left-to-right モードでは、'@command{:set rl}' コマンドを実行します ('rl' は rightleft の省略形)。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
      - Put the ':set rl' line in your '.vimrc' file to start Vim in
	right-to-left mode permanently.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item Vim を起動したときに常に right-to-left モードにしたい場合は '@file{.vimrc}' ファイルに ':set rl' を書いてください。
@end itemize
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
   +  Arabic right-to-left command-line Mode
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@unnumberedsubsec アラビア語 right-to-left コマンドラインモード
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
      For certain commands the editing can be done in right-to-left mode.
      Currently this is only applicable to search commands.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
特定のコマンドでは right-to-left モードで編集ができます。現在対応しているのは検索コマンドだけです。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
      This is controlled with the 'rightleftcmd' option.  The default is
      "search", which means that windows in which 'rightleft' is set will
      edit search commands in right-left mode.	To disable this behavior,
>
		:set rightleftcmd=
<
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
動作は '@option{rightleftcmd}' オプションで変更できます。初期設定は "@var{search}" で、これは '@option{rightleft}' がオンになっているウィンドウで検索コマンドを使うと right-left モードでの編集になります。これを無効化するには次のようにします。
@example
:set rightleftcmd=
@end example
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
      To enable right-left editing of search commands again,
>
		:set rightleftcmd&
<
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
再び検索コマンドでの right-left 編集を有効化するには次のようにします。
@example
:set rightleftcmd&
@end example
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
   +  Arabic Shaping Mode
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@unnumberedsubsec アラビア語字形モード
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
      To activate the required visual characters alterations (shaping,
      composing, combining) which the Arabic language requires, enable
      the 'arabicshape' command.  This is done by entering
>
		:set arabicshape
<
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
アラビア語は視覚字形変更 (shaping(文字変形), composing(合成), combining(結合)) を必要としますが、それを有効にするには '@option{arabicshape}' を設定します。VIM ウィンドウで次のコマンドを実行します。
@example
:set arabicshape
@end example
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
      in our Vim window.  You can also append the 'arabicshape' set
      command to your .vimrc file.  In other words, you can include
      ':set arabicshape' to your .vimrc file.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@file{.vimrc} ファイルで '@option{arabicshape}' を設定することもできます。その場合は ':set arabicshape' を @file{.vimrc} ファイルに書きます。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
Keymap/Keyboard						*arabickeymap*
---------------
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{arabickeymap}
@cindex arabickeymap
@unnumberedsec Keymap/Keyboard
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
The character/letter encoding used in Vim is the standard UTF-8.
It is widely discouraged that any other encoding be used or even
attempted.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
VIM で使用する文字エンコーディングは標準の UTF-8 です。他のエンコーディングの使用は推奨されていません。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Note: UTF-8 is an all encompassing encoding and as such is
      the only supported (and encouraged) encoding with
      regard to Arabic (all other proprietary encodings
      should be discouraged and frowned upon).
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@quotation
@strong{Note:} @*
UTF-8 はあらゆるものを含むエンコーディングで、アラビア語において唯一サポートされている (そして推奨されている) エンコーディングです (他のプロプライエタリなエンコーディングは非推奨であり使うべきではありません)。
@end quotation
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  Keyboard
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@unnumberedsubsec キーボード
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
   +  CTRL-^ in insert/replace mode toggles between Arabic/Latin mode
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@itemize
@item 挿入モードと置換モードでは @kbd{CTRL-^} でアラビア語モードとラテン語モードが切り替わります。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
   +  Keyboard mapping is based on the Microsoft's Arabic keymap (the
      de facto standard in the Arab world):
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item キーボードマッピングはマイクロソフトのアラビア語キーマップに基づいています (アラビア語圏のデファクトスタンダードです):
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
  +---------------------------------------------------------------------+
  |!   |@   |#   |$   |%   |^   |&   |*   |(   |)   |_   |+   ||   |~  ّ |
  |1 ١ |2 ٢ |3 ٣ |4 ٤ |5 ٥ |6 ٦ |7 ٧ |8 ٨ |9 ٩ |0 ٠ |-   |=   |\   |` ذ |
  +---------------------------------------------------------------------+
       |Q  َ |W  ً |E  ُ |R  ٌ |T لإ |Y إ |U ` |I ÷ |O x |P ؛ |{ < |} > |
       |q ض |w ص |e ث |r ق |t ف |y غ |u ع |i ه |o خ |p ح |[ ج |] د |
       +-----------------------------------------------------------+
	 |A  ِ |S  ٍ |D [ |F ] |G لأ |H أ |J ـ |K ، |L / |:   |"   |
	 |a ش |s س |d ي |f ب |g ل |h ا |j ت |k ن |l م |; ك |' ط |
	 +------------------------------------------------------+
	   |Z ~ |X  ْ |C { |V } |B لآ |N آ |M ' |< , |> . |? ؟ |
	   |z ئ |x ء |c ؤ |v ر |b لا |n ى |m ة |, و |. ز |/ ظ |
	   +-------------------------------------------------+
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@verbatim
+---------------------------------------------------------------------+
|!   |@   |#   |$   |%   |^   |&   |*   |(   |)   |_   |+   ||   |~  ّ |
|1 ١ |2 ٢ |3 ٣ |4 ٤ |5 ٥ |6 ٦ |7 ٧ |8 ٨ |9 ٩ |0 ٠ |-   |=   |\   |` ذ |
+---------------------------------------------------------------------+
  |Q  َ |W  ً |E  ُ |R  ٌ |T لإ |Y إ |U ` |I ÷ |O x |P ؛ |{ < |} > |
  |q ض |w ص |e ث |r ق |t ف |y غ |u ع |i ه |o خ |p ح |[ ج |] د |
  +-----------------------------------------------------------+
    |A  ِ |S  ٍ |D [ |F ] |G لأ |H أ |J ـ |K ، |L / |:   |"   |
    |a ش |s س |d ي |f ب |g ل |h ا |j ت |k ن |l م |; ك |' ط |
    +------------------------------------------------------+
      |Z ~ |X  ْ |C { |V } |B لآ |N آ |M ' |< , |> . |? ؟ |
      |z ئ |x ء |c ؤ |v ر |b لا |n ى |m ة |, و |. ز |/ ظ |
      +-------------------------------------------------+
@end verbatim
@end itemize
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Restrictions
------------
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@unnumberedsec 制限
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  Vim in its GUI form does not currently support Bi-directionality
   (i.e. the ability to see both Arabic and Latin intermixed within
   the same line).
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
VIM の GUI では Bi-directionality (双方向性) は正しくサポートされていません

(つまりアラビア語とラテン語を同じ行に書いたときに正しく表示されません)。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
Known Bugs
----------
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@unnumberedsec 既知のバグ
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
There is one known minor bug,
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
既知の小さなバグが 1 つあります。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
 1. If you insert a haraka (e.g. Fatha (U+064E)) after a LAM (U+0644)
    and then insert an ALEF (U+0627), the appropriate combining will
    not happen due to the sandwiched haraka resulting in something
    that will NOT be displayed correctly.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
1. LAM (U+0644) のうしろに haraka (例: Fatha (U+064E)) を入力して、そして ALEF (U+0627) を入力したとき、文字が正しく結合されません。これは 2 つの文字に挟まれた haraka が正しく表示されないために起こります。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
    WORK-AROUND: Don't include harakats between LAM and ALEF combos.
		 In general, don't anticipate to see correct visual
		 representation with regard to harakats and LAM+ALEF
		 combined characters (even those entered after both
		 characters).  The problem noted is strictly a visual
		 one, meaning saving such a file will contain all the
		 appropriate info/encodings - nothing is lost.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@quotation
@strong{WORK-AROUND:} @*
LAM と ALEF の間に harakats を置かないでください。

一般に、harakats と LAM+ALEF の結合文字が正しく表示されることは期待できません (2 つの文字のうしろに入力したとしてもです)。

これは表示上の問題なので、ファイルを保存するときには正しい情報が書き込まれます。情報は失われません。
@end quotation
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
No other bugs are known to exist.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
他に既知のバグはありません。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
 vim:tw=78:ts=8:noet:ft=help:norl:
@end ifset
