@ifset JA  @c ----------- v -----------  JA  -*- tab-width: 8 -*-
@node farsi.txt, , , 目次
@unnumbered ペルシア語のサポート
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
*farsi.txt*     For Vim version 8.0.  Last change: 2015 Aug 29


		  VIM REFERENCE MANUAL    by Mortaza Ghassab Shiran
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@verbatim
*farsi.txt*     For Vim バージョン 8.0.  Last change: 2015 Aug 29


                  VIMリファレンスマニュアル    by Mortaza Ghassab Shiran
@end verbatim
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
Right to Left and Farsi Mapping for Vim		*farsi* *Farsi*
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{farsi}
@anchor{Farsi}
@cindex farsi
@cindex Farsi
ペルシア語マッピングと右横書き
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
{Vi does not have any of these commands}
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@{Vi にはない機能です@}
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
						*E27*
In order to use right-to-left and Farsi mapping support, it is necessary to
compile Vim with the |+farsi| feature.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{E27}
@cindex E27
ペルシア語マッピングと右横書きを使うには、Vim をコンパイルするときに |+farsi| を有効にする必要があります。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
These functions have been made by Mortaza G. Shiran <shiran@jps.net>
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
これらの機能は Mortaza G. Shiran <shiran@@jps.net> によって作成されました。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
Introduction
------------
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@unnumberedsec はじめに
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
In right-to-left oriented files the characters appear on the screen from right
to left.  This kind of file is most useful when writing Farsi documents,
composing faxes or writing Farsi memos.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
右横書きのファイルでは、画面の右から左へ向かって文字が表示されます。そのようなファイルはペルシア語のドキュメントを書いたり、ファックスを作成したり、ペルシア語のメモ書きなどをするときにとても便利です。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
The commands, prompts and help files are not in Farsi, therefore the user
interface remains the standard Vi interface.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
コマンド、プロンプト、ヘルプファイルなどはペルシア語ではないため、ユーザーインターフェイスは Vi 標準のインターフェイスと変わりません。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
Highlights
----------
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@unnumberedsec 特色
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
o  Editing left-to-right files as in the original Vim, no change.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@itemize
@item 普通に Vim を使うように右横書きのファイルを編集できます。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  Viewing and editing files in right-to-left windows.   File orientation is
   per window, so it is possible to view the same file in right-to-left and
   left-to-right modes, simultaneously.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item 右横書きウィンドウでファイルを表示したり編集したりします。書字方向はウィンドウ単位で設定できます。そのため、同じファイルを右横書きと左横書きの両方で同時に表示できます。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  Compatibility to the original Vim.   Almost all features work in
   right-to-left mode (see bugs below).
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item 普通の Vim と互換性があります。ほとんどすべての機能は右横書きモードでも使えます。(下記のバグを参照)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  Changing keyboard mapping and reverse insert modes using a single
   command.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item キーマップと逆挿入モード (|ins-reverse|) はコマンド 1 つで切り替えできます。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  Backing from reverse insert mode to the correct place in the file
   (if possible).
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item 逆挿入モード (|ins-reverse|) から切り替わったときに、正常な位置にカーソルを移動します (それが可能な場合のみ)。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  While in Farsi mode, numbers are entered from left to right.  Upon entering
   a none number character, that character will be inserted just into the
   left of the last number.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item ペルシア語モードでも、数字は左横書きで挿入されます。そして、数字以外の文字が入力されると、その文字は数字の左側に挿入されます。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  No special terminal with right-to-left capabilities is required.  The
   right-to-left changes are completely hardware independent.  Only
   Farsi font is necessary.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item 特別な端末は必要ありません。右横書き機能はハードウェアにはまったく依存していません。必要なのはペルシア語フォントのみです。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  Farsi keymapping on the command line in reverse insert mode.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item コマンドラインでも、ペルシア語キーマップを使って逆挿入モードで入力できます。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  Toggling between left-to-right and right-to-left via F8 function key.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item 左横書きモードと右横書きモードは @key{F8} キーで切り替えられます。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  Toggling between Farsi ISIR-3342 standard encoding and Vim Farsi via F9
   function key.  Since this makes sense only for the text written in
   right-to-left mode, this function is also supported only in right-to-left
   mode.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item ペルシア語の ISIR-3342 標準エンコーディングと Vim Farsi は @key{F9} ファンクションキーで切り替えられます。これは、右横書きのテキストに対してのみ意味をなすので、右横書きモードでのみ利用できます。
@end itemize
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Farsi Fonts					*farsi-fonts*
-----------
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{farsi-fonts}
@cindex farsi-fonts
@unnumberedsec ペルシア語フォント
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
The following files are found in the subdirectories of the '$VIM/farsi/fonts'
directory:
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
次のファイルは '$VIM/farsi/fonts' ディレクトリ以下にあります:
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
   +  far-a01.pcf    X Windows fonts for Unix including Linux systems
   +  far-a01.bf     X Windows fonts for SunOS
   +  far-a01.f16    a screen fonts for Unix including Linux systems
   +  far-a01.fon    a monospaced fonts for Windows NT/95/98
   +  far-a01.com    a screen fonts for DOS
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@multitable @columnfractions .3 .7
@item far-a01.pcf @tab Linux や Unix システムの X Windows フォント
@item far-a01.bf @tab SunOS の X Windows フォント
@item far-a01.f16 @tab Linux や Unix システムのスクリーンフォント
@item far-a01.fon @tab Windows NT/95/98 の固定幅フォント
@item far-a01.com @tab DOS のスクリーンフォント
@end multitable
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
Font Installation
-----------------
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@unnumberedsec フォントのインストール
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  Installation of fonts for MS Window systems (NT/95/98)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@unnumberedsubsec MS Windows (NT/95/98) にフォントをインストールする場合
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
   From 'Control Panel' folder, start the 'Fonts' program.  Then from 'file'
   menu item select 'Install New Fonts ...'.  Browse and select the
   'far-a01.fon', then follow the installation guide.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
'コントロールパネル' から、'フォント' を選択します。'ファイル' メニューから '新しいフォントのインストール...' を選択し、'far-a01.fon' を開きます。後はインストールガイドに従ってください。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
   NOTE: several people have reported that this does not work.  The solution
   is unknown.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@quotation
@strong{Note:} @*
この方法でインストールできなかったという報告がいくつかありました。解決方法は分かりません。
@end quotation
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
o  Installation of fonts for X Window systems (Unix/Linux)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@unnumberedsubsec  X Window System にフォントをインストールする場合 (Unix/Linux)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
   Depending on your system, copy far-a01.pcf.Z or far-a01.pcf.gz into a
   directory of your choice.  Change to the directory containing the Farsi
   fonts and execute the following commands:
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
お使いのシステムに合わせて、far-a01.pcf.Z または far-a01.pcf.gz をインストールするディレクトリにコピーします。そのディレクトリに移動し、次のコマンドを実行します:
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
   >  mkfontdir
   >  xset +fp path_name_of_farsi_fonts_directory
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@verbatim
>  mkfontdir
>  xset +fp path_name_of_farsi_fonts_directory
@end verbatim
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  Installation of fonts for X Window systems (SunOS)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@unnumberedsubsec X Window System にフォントをインストールする場合 (SunOS)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
   Copy far-a01.bf font into a directory of your choice.
   Change to the directory containing the far-a01.fb fonts and
   execute the following commands:
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
インストールするディレクトリに far-a01.bf をコピーします。そのディレクトリに移動し、次のコマンドを実行します:
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
   >  fldfamily
   >  xset +fp path_name_of_fonts_directory
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@verbatim
>  fldfamily
>  xset +fp path_name_of_fonts_directory
@end verbatim
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  Installation of ASCII screen fonts (Unix/Linux)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@unnumberedsubsec ASCII スクリーンフォントをインストールする場合 (Unix/Linux)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
   For Linux system, copy the far-a01.f16 fonts into /usr/lib/kbd/consolefonts
   directory and execute the setfont program as "setfont far-a01.f16".  For
   other systems (e.g. SCO Unix), please refer to the fonts installation
   section of your system administration manuals.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
Linux システムでは、far-01.f16 を /usr/lib/kbd/consolefonts にコピーし、"setfont far-a01.f16" と、フォント設定プログラムを実行します。他のシステム (SCO Unix など) では、システム管理マニュアルのフォントインストールの項目を参照してください。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  Installation of ASCII screen fonts (DOS)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@unnumberedsubsec ASCII スクリーンフォントをインストールする場合 (DOS)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
   After system power on, prior to the first use of Vim, upload the Farsi
   fonts by executing the far-a01.com font uploading program.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
システム電源導入後、最初に Vim を起動する前に、フォントアップロードプログラムの far-a01.com を実行して、ペルシア語フォントをアップロードします。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
Usage
-----
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@unnumberedsec 使い方
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
Prior to starting Vim, the environment in which Vim can run in Farsi mode,
must be set.  In addition to installation of Farsi fonts, following points
refer to some of the system environments, which you may need to set:
Key code mapping, loading graphic card in ASCII screen mode, setting the IO
driver in 8 bit clean mode ... .
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
Vim を起動する前に、ペルシア語モードが実行できるように環境を設定してください。ペルシア語フォントのインストールに加えて、いくつかのシステム環境では、キーコードマッピング、ASCII スクリーンモードでのグラフィックカードのロード、IO ドライバの 8 ビット透過設定などを設定する必要があります。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  Setting the Farsi fonts
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@unnumberedsubsec ペルシア語フォントを設定する
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
   +  For Vim GUI set the 'guifont' to far-a01.  This is done by entering
      ':set guifont=far-a01' in the Vim window.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@itemize
@item GUI では、'guifont' に far-a01 を設定します。Vim のコマンドラインで ':set guifont=far-a01' と入力してください。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
      You can have 'guifont' set to far-a01 by Vim during the Vim startup
      by appending the ':set guifont=far-a01' into your .vimrc file
      (in case of NT/95/98 platforms _vimrc).
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
Vim を起動したときに自動的に設定されるようにするには、@file{.vimrc} ファイルに ':set guifont=far-a01' と書き加えます。NT/95/98 プラットフォームでは @file{.vimrc} ではなく @file{_vimrc} です。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
      Under the X Window environment, you can also start Vim with the
      '-fn far-a01' option.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
X Window System では、'-fn far-a01' オプションで Vim を起動することもできます。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
   +  For Vim within a xterm, start a xterm with the Farsi fonts (e.g.
      kterm -fn far-a01).  Then start Vim inside the kterm.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item xterm で Vim を使う場合は、xterm をペルシア語フォントで起動します (例 kterm -fn far-a01)。そして、kterm 内で Vim を起動します。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
   +  For Vim under DOS, prior to the first usage of Vim, upload the Farsi
      fonts by executing the far-a01.com fonts uploading program.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item DOS で Vim を使う場合は、最初に Vim を起動する前に、フォントアップロードプログラムの far-a01.com を実行して、ペルシア語フォントをアップロードします。
@end itemize
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  Farsi Keymapping Activation
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@unnumberedsubsec ペルシア語キーマップを有効にする
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
   To activate the Farsi keymapping, set either 'altkeymap' or 'fkmap'.
   This is done by entering ':set akm' or ':set fk' in the Vim window.
   You can have 'altkeymap' or 'fkmap' set as default by appending ':set akm'
   or ':set fk' in your .vimrc file or _vimrc in case of NT/95/98 platforms.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
ペルシア語キーマップを有効にするには、'@option{altkeymap}' または '@option{fkmap}' を設定します。それには、Vim のコマンドラインで '@command{:set akm}' または '@command{:set fk}' と入力してください。常にこの設定を使うには、'@command{:set akm}' または '@command{:set fk}' を、@file{.vimrc} ファイルに書き加えてください。NT/95/98 プラットフォームでは @file{.vimrc} ではなく @file{_vimrc} です。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
   To turn off the Farsi keymapping as a default second language keymapping,
   reset the 'altkeymap' by entering ':set noakm'.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
初期設定では第 2 言語としてペルシア語キーマップが使われますが、これを切り替えるには、'@command{:set noakm}' と入力して '@option{altkeymap}' をオフに設定します。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  right-to-left Farsi Mode
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@unnumberedsubsec 右横書きのペルシア語モード
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
   By default Vim starts in Left-to-right mode.  Following are ways to change
   the window orientation:
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
初期設定では、Vim は左横書きモードで起動します。ウィンドウの書字方向を変えるには次の方法があります。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
   + Start Vim with the -F option (e.g. vim -F ...).
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@itemize
@item -F オプションを使って Vim を起動する (例: vim -F ...)。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
   + Use the F8 function key to toggle between left-to-right and right-to-left.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item @key{F8} ファンクションキーを使って右横書きを左横書きを切り替える。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
   + While in Left-to-right mode, enter 'set rl' in the command line ('rl' is
     the abbreviation for rightleft).
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item 左横書きモードのときに、コマンドラインで 'set rl' と入力する ('rl' は rightleft の省略形です)。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
   + Put the 'set rl' line in your '.vimrc' file to start Vim in
     right-to-left mode permanently.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item 常に右横書きモードで Vim を起動するには、'set rl' を @file{.vimrc} ファイルに書き加えます。
@end itemize
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Encoding
--------
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@unnumberedsec エンコーディング
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
The letter encoding used is the Vim extended ISIR-3342 standard with a built
in function to convert between Vim extended ISIR-3342 and ISIR-3342 standard.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
テキストのエンコーディングは ISIR-3342 を拡張したものです。Vim 拡張 ISIR-3342 と 標準 ISIR-3342 は、組み込み関数で変換できます。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
For document portability reasons, the letter encoding is kept the same across
different platforms (i.e. UNIX's, NT/95/98, MS DOS, ...).
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
文章の可搬性のため、どのプラットフォーム (UNIX, NT/95/98, MS DOS、...) でも同じエンコーディングが使われます。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
o  Keyboard
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@unnumberedsec キーボード
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
   +  CTRL-_ in insert/replace modes toggles between Farsi(akm)/Latin
      mode as follows:
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@itemize
@item 挿入/置換モードでは、@kbd{CTRL-_} でペルシア語 (akm) とラテン語を切り替えます。以下のように動作します。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
   +  CTRL-_ moves the cursor to the end of the typed text in edit mode.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item @kbd{CTRL-_} で切り替えると、編集モードで入力したテキストの最後の位置へカーソルが移動します。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
   +  CTRL-_ in command mode only toggles keyboard mapping between Farsi(akm)/
      Latin.  The Farsi text is then entered in reverse insert mode.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item コマンドラインモードでは、@kbd{CTRL-_} はペルシア語 (akm) とラテン語のキーマップのみ切り替えます。ペルシア語のテキストは逆挿入モードで入力されます。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
   +  F8 - Toggles between left-to-right and right-to-left.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item @key{F8} キーで左横書きと右横書きを切り替えられます。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
   +  F9 - Toggles the encoding between ISIR-3342 standard and Vim extended
      ISIR-3342 (supported only in right-to-left mode).
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item @key{F9} キーで 標準 ISIR-3342 と Vim 拡張 ISIR-3342 のエンコーディングを切り替えられます (右横書きモードでのみ機能します)。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
   +  Keyboard mapping is based on the Iranian ISIRI-2901 standard.
      Following table shows the keyboard mapping while Farsi(akm) mode set:
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item ペルシア語キーマップはイランの ISIRI-2901 標準がベースになっています。次の表は、ペルシア語 (akm) モードが設定されている場合のキーマップです:
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
	-------------------------------------
	`  1  2  3  4  5  6  7  8  9  0  -  =
	¢  ±  ²  ³  ´  µ  ¶  ·  ¸  ¹  °  ­  ½
	-------------------------------------
	~  !  @  #  $  %  ^  &  *  (  )  _  +
	~  £  §  ®  ¤  ¥  ª  ¬  è  ¨  ©  é  «
	-------------------------------------
	q  w  e  r  t  z  u  i  o  p  [  ]
	Ó  Ò  Æ  Ù  Ø  Õ  Ö  à  Ê  É  Ç  
	-------------------------------------
	Q  W  E  R  T  Z  U  I  O  P  {  }
	÷  õ  ô  ó  ò  ý  ð  ö  [  ]  {  }
	-------------------------------------
	a  s  d  f  g  h  j  k  l  ;  '  \
	Ñ  Ð  á  Ã  Ü  Á  Å  Þ  Ý  Ú  Û  ë
	-------------------------------------
	A  S  D  F  G  H  J  K  L  :  "  |
	ù  û  þ  ú  ø  À  ü  æ  ç  º  »  ê
	-------------------------------------
	<  y  x  c  v  b  n  m  ,  .  /
	¾  ×  Ô  Î  Í  Ì  Ë  Ä  ß  ¦  ¯
	-------------------------------------
	>  Y  X  C  V  B  N  M  <  >  ?
	¼  ñ  Ô  Ï  Í  ¡  Ë  Â  ¾  ¼  ¿
	-------------------------------------
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@verbatim
-------------------------------------
`  1  2  3  4  5  6  7  8  9  0  -  =
¢  ±  ²  ³  ´  µ  ¶  ·  ¸  ¹  °  ­  ½
-------------------------------------
~  !  @  #  $  %  ^  &  *  (  )  _  +
~  £  §  ®  ¤  ¥  ª  ¬  è  ¨  ©  é  «
-------------------------------------
q  w  e  r  t  z  u  i  o  p  [  ]
Ó  Ò  Æ  Ù  Ø  Õ  Ö  à  Ê  É  Ç  
-------------------------------------
Q  W  E  R  T  Z  U  I  O  P  {  }
÷  õ  ô  ó  ò  ý  ð  ö  [  ]  {  }
-------------------------------------
a  s  d  f  g  h  j  k  l  ;  '  \
Ñ  Ð  á  Ã  Ü  Á  Å  Þ  Ý  Ú  Û  ë
-------------------------------------
A  S  D  F  G  H  J  K  L  :  "  |
ù  û  þ  ú  ø  À  ü  æ  ç  º  »  ê
-------------------------------------
<  y  x  c  v  b  n  m  ,  .  /
¾  ×  Ô  Î  Í  Ì  Ë  Ä  ß  ¦  ¯
-------------------------------------
>  Y  X  C  V  B  N  M  <  >  ?
¼  ñ  Ô  Ï  Í  ¡  Ë  Â  ¾  ¼  ¿
-------------------------------------
@end verbatim
@{訳注: 合成文字は表示のためにスペースと合成してあります。 @*
farsi->unicode 変換がよくわからないので微妙に違うところがあると思います。 @*
@url{http://www.farsiweb.info/table/2901-unicode.txt} @*
@url{http://www.farsiweb.info/table/3342.txt}
@}
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Note:
	¡  stands for Farsi PSP (break without space)

	¢  stands for Farsi PCN (for HAMZE attribute)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@quotation
@strong{Note:} @*
¡ はペルシア語の PSP を意味します (スペースなしの区切り)

¢ はペルシア語の PCN を意味します (ハムゼ (HANZE) 属性のため)

@{訳注: PSP (pseudo space), PCN (pseudo connection)@}
@end quotation
@end itemize
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Restrictions
------------
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@unnumberedsec 制限事項
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  In insert/replace mode and fkmap (Farsi mode) set, CTRL-B is not
   supported.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@itemize
@item 挿入モードと置換モードで '@option{fkmap}' (ペルシア語モード) がオンのとき、@kbd{CTRL-B} は使えません。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  If you change the character mapping between Latin/Farsi, the redo buffer
   will be reset (emptied).  That is, redo is valid and will function (using
   '.') only within the mode you are in.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item ペルシア語とラテン語のキーマップを切り替えた場合、繰り返しバッファはリセットされて空になります。つまり、同じモードにいる間だけ ('.' を使って) 最後の変更を繰り返せます。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  While numbers are entered in Farsi mode, the redo buffer will be reset
   (emptied).  That is, you cannot redo the last changes (using '.') after
   entering numbers.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item ペルシア語モードで数字を入力すると、繰り返しバッファはリセットされて空になります。つまり、数字を入力した後は、 ('.' を使って) 最後の変更を繰り返せません。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  While in left-to-right mode and Farsi mode set, CTRL-R is not supported.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item 左横書きモードとペルシア語モードを使っているときは @kbd{CTRL-R} は使えません。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  While in right-to-left mode, the search on 'Latin' pattern does not work,
   except if you enter the Latin search pattern in reverse.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item 右横書きモードでは、'ラテン語' のパターンを検索できません。しかし、パターンを逆向きに書けば検索できます。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  In command mode there is no support for entering numbers from left
   to right and also for the sake of flexibility the keymapping logic is
   restricted.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item コマンドラインモードでは、数字を左横書きで入力することはできません。さらに、使いやすくするために、キーマップのロジックは制限されています。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  Under the X Window environment, if you want to run Vim within a xterm
   terminal emulator and Farsi mode set, you need to have an ANSI compatible
   xterm terminal emulator.  This is because the letter codes above 128 decimal
   have certain meanings in the standard xterm terminal emulator.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item X Window System 環境の端末エミュレータ xterm で Vim のペルシア語モードを使う場合、ANSI 互換の xterm を使う必要があります。これは、標準の xterm では、文字番号が 128 より大きい文字は特別な意味を持ってしまうからです。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
   Note: Under X Window environment, Vim GUI works fine in Farsi mode.
	 This eliminates the need of any xterm terminal emulator.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@quotation
@strong{Note:} @*
X Window System 環境の GUI Vim では、ペルシア語モードはうまく機能します。xterm などの他の端末エミュレータは必要ありません。
@end quotation
@end itemize
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
Bugs
----
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@unnumberedsec バグ
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
While in insert/replace and Farsi mode set, if you repeatedly change the
cursor position (via cursor movement) and enter new text and then try to undo
the last change, the undo will lag one change behind.  But as you continue to
undo, you will reach the original line of text.  You can also use U to undo all
changes made in the current line.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
挿入モードか置換モードでペルシア語モードをオンにして、カーソルを移動するのと、文字を入力するのを何度か繰り返します。そしてアンドゥすると、カーソルを移動した時点までしかアンドゥされません。しかし、何度もアンドゥすることで元のテキストまで戻ることができます。現在行の変更をすべてアンドゥするために U を使うこともできます。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
For more information about the bugs refer to rileft.txt.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
バグについては |rileft.txt| も参照してください。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
 vim:tw=78:ts=8:ft=help:norl:
@end ifset
