@ifset JA  @c ----------- v -----------  JA  -*- tab-width: 8 -*-
@node hangulin.txt, , , 目次
@unnumbered ハングル (韓国語) の入力
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
*hangulin.txt*  For Vim version 8.0.  Last change: 2015 Nov 24


		  VIM REFERENCE MANUAL    by Chi-Deok Hwang and Sung-Hyun Nam
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@verbatim
*hangulin.txt*  For Vim バージョン 8.0.  Last change: 2015 Nov 24


        VIMリファレンスマニュアル  by Chi-Deok Hwang and Sung-Hyun Nam
@end verbatim
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
Introduction					*hangul*
------------
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{hangul}
@cindex hangul
@unnumberedsec イントロダクション
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
It is to input hangul, the Korean language, with Vim GUI version.
If you have a XIM program, you can use another |+xim| feature.
Basically, it is for anybody who has no XIM program.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
これは GUI version の Vim でハングル (韓国語) を入力するための説明です。XIM プログラムを持っている場合は、|@ref{+xim}| 機能を使うことができます。基本的にこのファイルは XIM プログラムを持っていない方向けの説明です。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Compile
-------
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@unnumberedsec コンパイル
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
Next is a basic option.  You can add any other configure option. >
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
次のオプションは最低限の指定であり、他の configure オプションを追加することもできます。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
   ./configure --with-x --enable-multibyte --enable-hangulinput \
            --disable-xim
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@verbatim
./configure --with-x --enable-multibyte --enable-hangulinput \
         --disable-xim
@end verbatim
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
And you should check feature.h.  If |+hangul_input| feature is enabled
by configure, you can select more options such as keyboard type, 2 bulsik
or 3 bulsik.  You can find keywords like next in there. >
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
そして、|@ref{+hangul_input}| 機能が configure によって有効になっているかどうか、feature.h をチェックすべきです。そして、他のオプションも選択することができます。たとえば、2 bulsik か 3 bulsik のどちらのキーボード・タイプを使うかなど。次のようなキーワードがファイルにはあります。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
	#define HANGUL_DEFAULT_KEYBOARD 2
	#define ESC_CHG_TO_ENG_MODE
	/* #define X_LOCALE */
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@example
#define HANGUL_DEFAULT_KEYBOARD 2
#define ESC_CHG_TO_ENG_MODE
/* #define X_LOCALE */
@end example
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Environment variables
---------------------
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@unnumberedsec 環境変数
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
You should set LANG variable to Korean locale such as ko, ko_KR.eucKR
or ko_KR.UTF-8.
If you set LC_ALL variable, it should be set to Korean locale also.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
LANG 変数を、ko, ko_KR.euckR および ko_KR.UTF-8 のような韓国語ロケールに指定する必要があります。

LC_ALL 変数をセットしている場合は、それも韓国語ロケールである必要があります。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Vim resource
------------
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@unnumberedsec VIM リソース
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
You may want to set 'encoding' and 'fileencodings'.
Next are examples: >
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
'@option{encoding}' と '@option{fileencodings}' をセットしたいかもしれません。

例:
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
	:set encoding=euc-kr
	:set encoding=utf-8
	:set fileencodings=ucs-bom,utf-8,cp949,euc-kr,latin1
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@example
:set encoding=euc-kr
:set encoding=utf-8
:set fileencodings=ucs-bom,utf-8,cp949,euc-kr,latin1
@end example
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Keyboard
--------
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@unnumberedsec キーボード
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
You can change keyboard type (2 bulsik or 3 bulsik) using VIM_KEYBOARD
or HANGUL_KEYBOARD_TYPE environment variables.  For sh, just do (2 bulsik): >

    export VIM_KEYBOARD="2"
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
VIM_KEYBOARD か HANGUL_KEYBOARD_TYPE 環境変数を使うことによって、キーボード・タイプ(2 bulsk か 3 bulsik)を変更することができます。sh の場合で、2 bulsik にするには、次を実行してください:
@example
export VIM_KEYBOARD="2"
@end example
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
or >
    export HANGUL_KEYBOARD_TYPE="2"
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
もしくは:
@example
export HANGUL_KEYBOARD_TYPE="2"
@end example
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
If both are set, VIM_KEYBOARD has higher priority.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
両方がセットされている場合は、VIM_KEYBOARD が優先されます。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Hangul Fonts
------------
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@unnumberedsec ハングル・フォント
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
If you use GTK version of gvim, you should set 'guifont' and 'guifontwide'.
For example: >
    set guifont=Courier\ 12
    set guifontwide=NanumGothicCoding\ 12
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
GTK バージョンの GVIM を使用している場合は '@option{guifont}' と '@option{guifontwide}' をセットするべきです。

例:
@example
set guifont=Courier\ 12
set guifontwide=NanumGothicCoding\ 12
@end example
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
If you use Motif or Athena version of gvim, you should set 'guifontset' in
your vimrc.  You can set fontset in the .Xdefaults file.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
Motif もしくは Athena バージョンの GVIM を使用している場合は vimrc 内で '@option{guifontset}' をセットするべきです。フォントセットは @file{.Xdefaults} ファイル内で指定できます。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
$HOME/.gvimrc: >
    set guifontset=english_font,hangul_font
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
$HOME/.gvimrc:
@example
set guifontset=english_font,hangul_font
@end example
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
$HOME/.Xdefaults: >
    Vim.font: english_font

    ! Nexts are for hangul menu with Athena
    *international: True
    Vim*fontSet: english_font,hangul_font

    ! Nexts are for hangul menu with Motif
    *international: True
    Vim*fontList: english_font;hangul_font:
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
$HOME/.Xdefaults:
@example
Vim.font: english_font

! 次の行は Athena version でのハングル・メニューに使われます
*international: True
Vim*fontSet: english_font,hangul_font

! 次の行は Motif version でのハングル・メニューに使われます
*international: True
Vim*fontList: english_font;hangul_font:
@end example
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
attention! the , (comma) or ; (semicolon)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
注意！ , (コンマ) か ; (セミコロン)です。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
And there should be no ':set guifont'.  If it exists, then gvim ignores
':set guifontset'.  It means Vim runs without fontset supporting.
So, you can see only English.  Hangul does not be correctly displayed.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
そして ':set guifont' が設定されていてはいけません。もし設定されていると GVim は ':set guifontset' を無視します。つまり、Vim がフォントセットのサポートなしで動作することになり、英語の文字だけが見えることになり、ハングルは正しくは表示されなくなります。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
After "fontset" feature is enabled, Vim does not allow using english
font only in "font" setting for syntax.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
"fontset" 機能が有効になった後、シンタックス定義での "font" 設定でのみ英語のフォントを使うことはできなくなります。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
For example, if you use >
   :set guifontset=eng_font,your_font
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
例えば、もし .gvimrc で次のようにしている場合は:
@example
:set guifontset=eng_font,your_font
@end example
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
in your .gvimrc, then you should do for syntax >
   :hi Comment guifg=Cyan font=another_eng_font,another_your_font
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
構文ハイライトの指定では次のようにする必要があります:
@example
:hi Comment guifg=Cyan font=another_eng_font,another_your_font
@end example
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
If you just do >
   :hi Comment font=another_eng_font
then you can see a error message.  Be careful!
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
単に次のようにした場合は:
@example
:hi Comment font=another_eng_font
@end example
たくさんのエラーメッセージが表示されることになります。注意してください！
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
hangul_font width should be twice than english_font width.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
ハングル・フォントの幅は、英語フォントの幅の 2 倍である必要があります。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Unsupported Feature
-------------------
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@unnumberedsec サポートされていない機能
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
We don't support Johab font.
We don't support Hanja input.
And We don't have any plan to support them.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
Johab フォントはサポートしていません。 @*
Hanja フォントはサポートしていません。 @*
それらをサポートする予定は一切ありません。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
If you really need such features, you can use console version of Vim with a
capable terminal emulator.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
もしも本当にそれらの機能が必要ならば、それらをサポートした端末エミュレータ上でコンソールバージョンの Vim を使ってください。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Bug or Comment
--------------
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@unnumberedsec バグ・コメント
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
Send comments, patches and suggestions to:
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
コメント、パッチ、提案などはこちらに:
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
				    SungHyun Nam <goweol@gmail.com>
				    Chi-Deok Hwang <...>
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
SungHyun Nam <goweol@@gmail.com> @*
Chi-Deok Hwang <...>
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
 vim:tw=78:ts=8:ft=help:norl:
@end ifset
