@ifset JA  @c ----------- v -----------  JA  -*- tab-width: 8 -*-
@node os_unix.txt, , , 目次
@unnumbered Unix
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
*os_unix.txt*   For Vim version 8.0.  Last change: 2005 Mar 29


		  VIM REFERENCE MANUAL    by Bram Moolenaar
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@verbatim
*os_unix.txt*   For Vim バージョン 8.0.  Last change: 2005 Mar 29


                  VIMリファレンスマニュアル       by Bram Moolenaar
@end verbatim
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
							*unix* *Unix*
This file contains the particularities for the Unix version of Vim.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{unix}
@anchor{Unix}
@cindex unix
@cindex Unix
このファイルは Unix のバージョンの Vim で特殊な事柄について書いてあります。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
For compiling Vim on Unix see "INSTALL" and "Makefile" in the src directory.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
Vim を Unix でコンパイルするには src ディレクトリにある "INSTALL" と "Makefile" をご覧下さい。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
The default help file name is "/usr/local/lib/vim/help.txt"
The files "$HOME/.vimrc" and "$HOME/.exrc" are used instead of "s:.vimrc" and
"s:.exrc".  Additionally "/usr/local/etc/vimrc" is used first.
If "/usr/local/share" exists it is used instead of "/usr/local/lib".
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
デフォルトのヘルプファイルの名前は "/usr/local/lib/vim/help.txt" です。"s:.vimrc" と "s:.exrc" の代わりに "$HOME/.vimrc" と "$HOME/.exrc" が使われます。さらに "/usr/local/etc/vimrc" が初めに使われます。もし "/usr/local/share" があれば "/usr/local/lib" の代わりにそちらが使われます。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Temporary files (for filtering) are put in "/tmp".  If you want to place them
somewhere else, set the environment variable $TMPDIR to the directory you
prefer.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
(フィルターを実行するときに使われる) 一時的なファイルは "/tmp" に置かれます。もしほかの場所におきたければ $TMPDIR 環境変数を自分の好みの場所に設定してください。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
With wildcard expansion you can use '~' (home directory) and '$'
(environment variable).
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
ワイルドカード展開と '~' (ホームディレクトリ)と '$' (環境変数) を使うことができます。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*fork* *spoon*
For executing external commands fork()/exec() is used when possible, otherwise
system() is used, which is a bit slower.  The output of ":version" includes
|+fork| when fork()/exec() is used, |+system()| when system() is used.  This
can be changed at compile time.
(For forking of the GUI version see |gui-fork|.)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{fork}
@anchor{spoon}
@cindex fork
@cindex spoon
可能であれば fork()/exec() が外部コマンドの実行に使われます、そうでない場合はもう少し遅い system() が使われます。fork()/exec() が使われる場合は |@ref{+fork}| が、system() が使われる場合は |@ref{+system()}| が "@command{:version}" コマンドの出力に含まれます。これはコンパイルするときに変更することができます。

(GUI バージョンのフォークに関しては |@ref{gui-fork}| をご覧下さい)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Because terminal updating under Unix is often slow (e.g. serial line
terminal, shell window in suntools), the 'showcmd' and 'ruler' options
are default off.  If you have a fast terminal, try setting them on.  You might
also want to set 'ttyfast'.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
Unix では端末の更新がしばしば遅いので (例: シリアルライン端末、suntools でのシェルウィンドウ)、'@option{showcmd}' と '@option{ruler}' オプションはデフォルトでオフにしてあります。もし速い端末を使っているのであればこれらをオンにしてみてください。それと '@option{ttyfast}' オプションもオンにしておきたいかもしれません。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
When using Vim in an xterm the mouse clicks can be used by Vim by setting
'mouse' to "a".  If there is access to an X-server gui style copy/paste will
be used and visual feedback will be provided while dragging with the mouse.
If you then still want the xterm copy/paste with the mouse, press the shift
key when using the mouse.  See |mouse-using|.  Visual feedback while dragging
can also be achieved via the 'ttymouse' option if your xterm is new enough.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
Vim を xterm 上で使っている場合 '@option{mouse}' オプションを "@var{a}" にセットすることで Vim でマウスクリックを使うことができるようになります。X-server へのアクセスがあれば GUI スタイルのコピー/ペーストが利用できます。そしてマウスをドラッグしている間ビジュアルなフィードバックが得られるようになります。もしまだ xterm でのマウスを使ってのコピー/ペーストを行いたい場合はマウスを使うときに @key{Shift} キーを押すようにしてください。参照 |@ref{mouse-using}|。もし十分に新しい xterm を使っていれば '@option{ttymouse}' オプションを通してドラッグする間にビジュアルなフィードバックを得られます。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
							*terminal-colors*
To use colors in Vim you can use the following example (if your terminal
supports colors, but "T_Co" is empty or zero): >
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{terminal-colors}
@cindex terminal-colors
Vim で色を使う場合は次のような例を使うことができます (もし端末が色をサポートしてはいるけれど "T_Co" が空かゼロの場合):
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
   :set t_me=^[[0;1;36m     " normal mode (undoes t_mr and t_md)
   :set t_mr=^[[0;1;33;44m  " reverse (invert) mode
   :set t_md=^[[1;33;41m    " bold mode
   :set t_se=^[[1;36;40m    " standout end
   :set t_so=^[[1;32;45m    " standout mode
   :set t_ue=^[[0;1;36m     " underline end
   :set t_us=^[[1;32m       " underline mode start
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@multitable @columnfractions .6 .4
@item :set t_me=^[[0;1;36m @tab ノーマルモード (t_mr と t_md を消す)
@item :set t_mr=^[[0;1;33;44m @tab 反転表示モードオン
@item :set t_md=^[[1;33;41m @tab 太字表示モードオン
@item :set t_se=^[[1;36;40m @tab 強調表示モードから抜ける
@item :set t_so=^[[1;32;45m @tab 強調表示モード開始
@item :set t_ue=^[[0;1;36m @tab 下線モードから抜ける
@item :set t_us=^[[1;32m @tab 下線モード開始
@end multitable
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
[the ^[ is an <Esc>, type CTRL-V <Esc> to enter it]
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
[ ^[ は <Esc> で入力するには @kbd{CTRL-V} @key{<Esc>} とタイプします]
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
For real color terminals the ":highlight" command can be used.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
本物の色端末では "@command{:highlight}" コマンドを使うこともできます。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
The file "tools/vim132" is a shell script that can be used to put Vim in 132
column mode on a vt100 and lookalikes.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
"tools/vim132" ファイルは Vim を vt100 もしくはそれによく似た端末上で 132 カラムモードで使うためのシェルスクリプトです。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
 vim:tw=78:ts=8:ft=help:norl:
@end ifset
