@ifset JA  @c ----------- v -----------  JA  -*- tab-width: 8 -*-
@node pi_gzip.txt, , , 目次
@unnumbered 圧縮ファイルの読み書き
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
*pi_gzip.txt*   For Vim version 8.1.  Last change: 2016 Nov 06


		  VIM REFERENCE MANUAL    by Bram Moolenaar
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@verbatim
*pi_gzip.txt*   For Vim version 8.1.  Last change: 2016 Nov 06


                  VIMリファレンスマニュアル    by Bram Moolenaar
@end verbatim
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
Editing compressed files with Vim		*gzip* *bzip2* *compress*
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{gzip}
@anchor{bzip2}
@anchor{compress}
@cindex gzip
@cindex bzip2
@cindex compress
圧縮されたファイルを Vim で編集する
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
1. Autocommands			|gzip-autocmd|
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@multitable @columnfractions .5 .5
@item 1. 自動実行コマンド @tab |@ref{gzip-autocmd}|
@end multitable
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
The functionality mentioned here is a |standard-plugin|.
This plugin is only available if 'compatible' is not set.
You can avoid loading this plugin by setting the "loaded_gzip" variable: >
	:let loaded_gzip = 1
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
ここで説明されているのは |@ref{standard-plugin}| @{訳注: 標準プラグイン@} です。

このプラグインは '@option{compatible}' がオフのときだけ利用できます。

変数 "loaded_gzip" を設定することでプラグインが読み込まれないようにできます:
@example
:let loaded_gzip = 1
@end example
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
{Vi does not have any of this}
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@{Vi にはこの機能はない@}
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
==============================================================================
1. Autocommands						*gzip-autocmd*
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{gzip-autocmd}
@cindex gzip-autocmd
@section 1. 自動実行コマンド
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
The plugin installs autocommands to intercept reading and writing of files
with these extensions:
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
このプラグインは自動実行コマンドをインストールして、以下の拡張子を持つファイルの読み書きを処理します:
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
	extension	compression ~
	*.Z		compress (Lempel-Ziv)
	*.gz		gzip
	*.bz2		bzip2
	*.lzma		lzma
	*.xz		xz
	*.lz		lzip
	*.zst		zstd
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@multitable @columnfractions .5 .5
@headitem 拡張子 @tab 圧縮方法(コマンド)
@item *.Z @tab compress (Lempel-Ziv)
@item *.gz @tab gzip
@item *.bz2 @tab bzip2
@item *.lzma @tab lzma
@item *.xz @tab xz
@item *.lz @tab lzip
@item *.zst @tab zstd
@end multitable
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
That's actually the only thing you need to know.  There are no options.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
あなたが知るべきことはこれだけです。オプションはありません。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
After decompressing a file, the filetype will be detected again.  This will
make a file like "foo.c.gz" get the "c" filetype.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
ファイルが伸長された後、再びファイル形式の判定処理が実行されます。それにより "foo.c.gz" のようなファイルが "c" 形式のファイルとして判定されます。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
If you have 'patchmode' set, it will be appended after the extension for
compression.  Thus editing the patchmode file will not give you the automatic
decompression.  You have to rename the file if you want this.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
'@option{patchmode}' を設定している場合、設定された値は圧縮を示す拡張子の後に付けられます。したがってパッチモードで作成されたファイルを開くときは自動的には伸長されません。そのファイルを伸長するにはファイル名を変更する必要があるでしょう。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
==============================================================================
 vim:tw=78:ts=8:noet:ft=help:norl:
@end ifset
