@ifset JA  @c ----------- v -----------  JA  -*- tab-width: 8 -*-
@node quotes.txt, , , 目次
@unnumbered Vim ユーザーの感想
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
*quotes.txt*    For Vim version 8.0.  Last change: 2010 Nov 03


		  VIM REFERENCE MANUAL    by Bram Moolenaar
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@verbatim
*quotes.txt*    For Vim バージョン 8.0.  Last change: 2010 Nov 03


		  VIMリファレンスマニュアル    by Bram Moolenaar
@end verbatim
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
							*quotes*
Here are some nice quotes about Vim that I collected from news and mail.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{quotes}
@cindex quotes
ニュースやメールから集めた、Vimに関する素晴らしい引用を紹介する。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
vim (vim) noun - Ebullient vitality and energy.  [Latin, accusative of vis,
strength]  (Dictionary)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
vim (vim) 名詞 - 溢れんばかりのバイタリティとエネルギー。 [ラテン語, 『力』の直接目的格, 力] (辞書)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Vim is so much better than vi that a great many of my old vi :map's became
immediately obsolete! (Tony Nugent, Australia)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
Vim は vi より大変優れているので、私の古い vi の多くの偉大な :map がすぐに廃れてしまった！ (Tony Nugent, オーストラリア)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Coming with a very GUI mindset from Windows, I always thought of people using
Vi as some kind of outer space alien in human clothes.  Once I tried I really
got addicted by its power and now I found myself typing Vim keypresses in the
oddest places! That's why I would like to see Vim embedded in every
application which deals with text editing.  (José Fonseca)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
Windows の GUI 志向の強い影響で、Viを使う人々は実は人間の姿をしたエイリアンなんじゃないかと思っていた。でも一度試してみるとそのパワーに病みつきになって、今では Vim 以外のソフトウェアで Vim のようにキータイプするまでになってしまった。これが、テキストを編集するあらゆるアプリケーションにVimを埋め込まれて欲しいと願う理由。(José Fonseca)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
I was a 12-year emacs user who switched to Vim about a year ago after finally
giving up on the multiple incompatible versions, flaky contributed packages,
disorganized keystrokes, etc.  And it was one of the best moves I ever made.
(Joel Burton)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
私は 12 年来の emacs ユーザーだったが、相次ぐ互換性のないバージョンアップや、役立たずの追加パッケージ群、一貫性のない操作方法などに嫌気がさして 1 年前に Vim に乗り換えた。まさに生涯最高の選択の1つだった。 (Joel Burton)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Although all of the programs were used during the preparation of the new and
revised material, most of the editing was done with Vim versions 4.5 and 5.0
under GNU-Linux (Redhat 4.2).  (Arnold Robbins, Israel, author of "Learning
the Vi editor")
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
資料の作成や修正に多くのプログラムを使用したが、編集のほとんどは GNU-Linux (RedHat 4.2) 上の Vim のバージョン 4.5 と 5.0 で行われた。(Arnold Robbins, イスラエル, "Learning the Vi editor" の著者)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Out of all the open software i've ever seen and used, and i've seen a lot, Vim
is the best, most useful and highest quality to work with, second only to the
linux kernel itself.  (Peter Jay Salzman)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
私は幾つものオープンソフトを使い、さらに多くのソフトを見てきたが、その中でも Vim は大変使いやすく、とても完成度が高く、linux kernel に次ぐ最高の作品だ。(Peter Jay Salzman)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
It's well worth noting that the _entirety_ of SourceForge was written using
Vim and its nifty PHP syntax highlighting.  I think the entire SF.net tech
staff uses Vim and we're all excited to have you aboard! (Tim Perdue)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
SourceForge の「全体が」Vim とその PHP 用のイカシた構文強調を使って書かれている、ということは大して重要ではない。大事なのは SF.net の技術スタッフ全員が Vim を使っているということであり、そして貴方が Vim を使うことを大いに歓迎しているということだ！(Tim Perdue)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Vim is one of a select bunch of tools for which I have no substitute.  It is
a brilliant piece of work! (Biju Chacko)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
Vim は私の七つ道具の 1 つで、代用品がありません。なんてすばらしい作品なんだろう！(Biju Chacko)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
A previous girlfriend of mine switched to emacs.  Needless to say, the
relationship went nowhere.  (Geoffrey Mann)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
私の元カノは emacs に走りました。もちろん、彼女とはうまくいきませんでした。(Geoffrey Mann)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
I rarely think about Vim, in the same way that I guess a fish rarely thinks
about water.  It's the environment in which everything else happens.  I'm a
fairly busy system administrator working on a lot of different platforms.  Vim
is the only thing that's consistent across all my systems, and it's just about
the only thing that doesn't break from time to time.  When a new system comes
in the door without Vim, I install it right away.  Great to have a tool that's
the same everywhere, that's completely reliable, so I can ignore it and think
about other things.  (Pete Schaeffer)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
魚が水のことを意識しないと思われるのと同様に、私はほとんど Vim について意識しない。それは全ての中にある環境である。私は相当に忙しいシステム管理者で、多くの異なるプラットフォームを扱っている。Vimは 私のシステム全てに共通して存在する唯一のもので、「時々クラッシュする」ということもない唯一のものだ。新しいシステムに Vim が入っていなかったときには、私は真っ先にインストールする。どの環境でもまったく信頼のおける同じツールを使うことができることは素晴らしく、おかげで Vim については無視することができ、その他のものについては考えることができるのだ。(Pete Schaeffer)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Having recently succeeded in running Vim via telnet through a Nokia
Communicator, I can now report that it works nicely on a Palm Pilot too.
(Allan Kelly, Scotland)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
最近ノキアの端末を通して telnet 経由で Vim を起動することに成功した、現在 Palm Pilot でも素晴らしく動いたことを報告できる。(Allan Kelly, スコットランド)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
You've done a tremendous job with 'VIM', Bram!  The more I use it, the more
impressed I get (I am an old 'vi' die hard who once started out with early
versions of 'emacs' in the late 1970's and was relieved by finding 'vi' in the
first UNIX I came across in 1983).  In my opinion, it's about time 'VIM'
replace 'emacs' as the standard for top editors.  (Bo Thide', Sweden)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
Bram! 'VIM' というなんてものすごい仕事をしたものだ！使えば使うほど感動するよ (私は古い 'vi' のダイハードで 1970 年代後半の初期の 'emacs' から使い始め、1983 年に初期の UNIX で 'vi' を見つけることで救われた)。私の考えでは、標準のトップエディタとして 'VIM' が 'emacs' に置換わる時だよ。(Bo Thide', スウェーデン)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
I love and use Vim heavily too.  (Larry Wall)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
私も Vim を深く愛し使っている。(Larry Wall @{訳注: Perlの作者@})
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Vi is like a Ferrari, if you're a beginner, it handles like a bitch, but once
you get the hang of it, it's small, powerful and FAST! (Unknown)
Vim is like a new model Ferrari, and sounds like one too - "VIIIIIIMMM!"
(Stephen Riehm, Germany)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
Vi はまるでフェラーリだ。初心者にはまるで暴れ馬だが、いったんコツさえ掴んでしまえば、非常に小さくパワフルかつ高速だ！(不明) Vim はまるでフェラーリの新モデルだ。発音もそっくり - "VIIIIIIMMM!"。(Stephen Riehm, ドイツ)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Schon bei Nutzung eines Bruchteils der Vim-Funktionen wird der Benutzer recht
schnell die Vorzuege dieses Editors kennen- und schaetzenlernen.
Translated: Even when only using a fraction of Vim-functions, the user will
quickly get used to and appreciate the advantages of this editor.  (Garry
Glendown, conclusion of an article on Vim in iX magazine 9/1998)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
Schon bei Nutzung eines Bruchteils der Vim-Funktionen wird der Benutzer recht schnell die Vorzuege dieses Editors kennen- und schaetzenlernen.
翻訳: Vim の機能をほんの少し使うだけでも、ユーザーはすぐに使うことができこのエディタの強みを正しく評価するだろう。(Garry Glendown, conclusion of an article on Vim in iX magazine 9/1998)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
I've recently acquired the O'Reilly book on Vi (it also discusses Vim
in-depth), and I'm amazed at just how powerful this application is.  (Jeffrey
Rankin)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
つい最近 Vi についてのオライリーの本を手に入れた (Vim についても深く言及されていた)。このアプリケーションがあまりにパワフルで驚愕した。(Jeffrey Rankin)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
This guide was written using the Windows 9.x distribution of gvim, which is
quite possibly the greatest thing to come along since God created the naked
girl.  (Michael DiBernardo)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
このガイドは Windows 9.x 上の gvim で書いている。これは神が裸の女性を創造して以来の最高傑作なんじゃないだろうか。(Michael DiBernardo)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Boy, I thought I knew almost everything about Vim, but every time I browse the
online documentation, I hit upon a minor but cool aspect of a Vim feature that
I didn't know before!  I must say the documentation is one the finest I've
ever seen in a product -- even better than most commercial products.
(Gautam Mudunuri)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
坊主、私は私自身 Vim についてほとんど全てのことを知っていると考えていた。しかしいつもオンラインドキュメントを眺めるたびに、それまで知らなかった Vim の機能の小さな、しかしクールな面を見つけるんだ！これは私がみた中でも (多くの商業製品と比べてさえも) 最高のドキュメントであると言わねばならない。(Gautam Mudunuri)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Vim 4.5 is really a fantastic editor.  It has sooooo many features and more
importantly, the defaults are so well thought out that you really don't have
to change anything!!  Words cannot express my amazement and gratitude to the
creators of Vim.  Keep it up.  (Vikas, USA)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
Vim 4.5 は本当に素晴らしい(ファンタスティックな)エディタだ。Vim にはものすごぉぉぉぉい多くの機能があり更に重要なことには、初期設定が素晴らしいので本当に何の変更も無しに使うことができるのだ！！Vim 作者への私の驚きと感謝の念はどんな言葉をもっても語り尽くせない。この先もそうであって。(Vikas, アメリカ合衆国)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
I wonder how long it will be before people will refer to other Vi editors as
Vim clones?  (Darren Hiebert)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
人々が他の Vi エディタを Vim のクローンと呼ぶようになるまでどのくらいかかるだろうか?  (Darren Hiebert)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
I read about [auto-positioning-in-file-based-on-the-errors-from-make] in one
of those "Perfect Programmer's Editor" threads and was delighted to discover
that Vim already supports it.  (Brendan Macmillan, Australia)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
"Perfect Programmer's Editor" のスレッドにある [make のエラーに基づいて自動的にファイルの位置へ飛ぶ] というのを読んで、Vim は既にそれをサポートしているので嬉しかった。(Brendan Macmillan, オーストラリア)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
I just discovered Vim (5.0) and I'm telling everyone I know about it!
I tell them Vim stands for Vi for the new (M)illenium.  Thanks so much!
(Matt F. Valentine)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
Vim (5.0) を発見して多くの知人とそれについて話をした。Vim は Vi の新世紀 (Millenium) を象徴するんだ、と彼らに言い聞かせた。本当にありがとう！(Matt F. Valentine)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
I think from now on "vi" should be called "Vim Imitation", not the other way
around.  (Rungun Ramanathan)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
"vi" は今から "Vim Imitation (Vim のものまね)" と呼ばれるべきで、逆ではないと考える @{訳注: Vim はもともと Vi IMitation に端を発している@}。(Rungun Ramanathan)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
The Law of Vim:
For each member b of the possible behaviour space B of program P, there exists
a finite time t before which at least one user u in the total user space U of
program P will request b becomes a member of the allowed behaviour space B'
(B' <= B).
In other words: Sooner or later everyone wants everything as an option.
(Negri)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
Vim の法則 @{訳注: 数学の公式風に！@}: @*
プログラム P の考え得る限りの動作空間 B の中で各々の要素を b とした時、プログラム P の全ユーザー空間Uのうち少なくとも 1 人のユーザー u が、ある動作bを許された動作空間 B' に加えるように要求するまでにかかる時間は有限である。(このとき B' は B' <= B となる) 言い換えれば: 遅かれ早かれ全員がオプションとして全てを欲しがるんだよ。(Negri)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Whenever I move to a new computing platform, the first thing I do is to port
Vim.  Lately, I am simply stunned by its ease of compilation using the
configure facility.  (A.M. Sabuncu, Turkey)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
あたらしい計算機プラットフォームに移る時はいつも、決まってまず最初にやるのは Vim を移植すること。後に configure を使った時にコンパイルの簡単さにビックリした。(A.M. Sabuncu, トルコ)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
The options are really excellent and very powerful.  (Anish Maharaj)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
オプションが本当に優秀でとてもパワフルだ。(Anish Maharaj)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
The Spring user-interface designs are in, and word from the boutiques is that
80x24 text-only mode is back with a *vengeance! Vi editor clone Vim burst onto
March desk-tops with a dazzling show of pastel syntax highlights for its 5.0
look.  Strident and customizable, Vim raises eyebrows with its interpretation
of the classic Vi single-key macro collection.
http://www.ntk.net/index.cgi?back=archive98/now0327.txt&line=179#l
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
ユーザーインターフェイスのデザインは春であり、80x24 テキスト専用モードのブティックからの「言葉は復讐に戻った！」。Vi エディタのクローンである Vim は、5.0 のシンタックスハイライトによって 3 月のデスクトップに眩暈のするパステルの景色をもたらした。金切り声とカスタマイズ性、Vim は伝統的な Vi のシングルキーマクロ集に独自の解釈をすることで、我々を驚かせる。@{訳注: 原文が難解でまったく自信無@} @url{http://www.ntk.net/index.cgi?back=archive98/now0327.txt&line=179#l}
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
I just wanted to take this opportunity to let you know that Vim 5 ROCKS!
Syntax highlighting: how did I survive without it?!  Thank you for creating
mankind's best editor!  (Mun Johl, USA)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
Vim 5 の衝撃をどうしても伝えたかったんだ！シンタックスハイライティング: これ無しでどうやって生きろって？！人類最高のエディタを作ってくれてありがとう！(Mun Johl, アメリカ合衆国)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Thanks again for Vim.  I use it every day on Linux.  (Eric Foster-Johnson,
author of the book "UNIX Programming Tools")
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
重ね重ね Vim には感謝する。Linux で毎日使っている。(Eric Foster-Johnson, "UNIX Programming Tools"の著者)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
The BEST EDITOR EVER (Stuart Woolford)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
史上最高のエディタ (Stuart Woolford)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
I have used most of Vim's fancy features at least once, many frequently, and I
can honestly say that I couldn't live with anything less anymore.  My
productivity has easily doubled compared to what it was when I used vi.
(Sitaram Chamarty)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
Vim の素晴らしい機能のほとんどを少なくとも 1 度は、ものによってはもう何度も頻繁に使ってきた。正直に白状しよう、どれ 1 つ欠けても生きていけない。vi を使っていた頃の自分と生産性を比べると、優に倍にはなっている。(Sitaram Chamarty)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
I luv Vim.  It is incredible.  I'm naming my first-born Vimberly.  (Jose
Unpingco, USA)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
Vim を愛している。信じられないよ(incredible)。最初の子供に Vimberly と名づけた。(Jose Unpingco, アメリカ合衆国)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Hint:  "Vim" is "vi improved" - much better! (Sven Guckes, Germany)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
ヒント: "Vim" は "vi improved (vi改)" っていうほうが良い！(Sven Guckes, ドイツ)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
I use Vim every day.  I spend more time in Vim than in any other program...
It's the best vi clone there is.  I think it's great.  (Craig Sanders,
Australia)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
毎日 Vim を使っている。他のどんなプログラムよりも Vim と共に過ごす時間が長い…。存在する vi クローンの中で最高だ。とてもすごいよ。(Craig Sanders, オーストラリア)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
I strongly advise using Vim--its infinite undo/redo saved me much grief.
(Terry Brown)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
その無限アンドゥ/リドゥで私を幾度となく悲しみから救ってくれた@minus{}@minus{}@minus{} Vim を使用するように強く薦める。(Terry Brown)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Thanks very much for writing what in my opinion is the finest text editor on
the planet.  If I were to get another cat, I would name it "Vim".
(Bob Sheehan, USA)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
私の考えうるなかで、この惑星で最良のテキストエディタを書いて(作成して)くれたことにたいへん感謝する。次に猫を飼うときは "Vim" と命名したい。(Bob Sheehan, アメリカ合衆国)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
I typed :set all and the screen FILLED up with options.  A whole screen of
things to be set and unset.  I saw some of my old friends like wrapmargin,
modelines and showmode, but the screen was FILLED with new friends!   I love
them all!   I love Vim!   I'm so happy that I've found this editor!  I feel
like how I once felt when I started using vi after a couple of years of using
ed.  I never thought I'd forsake my beloved ed, but vi ... oh god, vi was
great.  And now, Vim.  (Peter Jay Salzman, USA)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
:set all とタイプすればオプションで画面が埋め尽くされる。画面全体のものが設定か非設定かされている。wrapmargin や modelines や showmode といった古い友人たちも見つけたが、新しい友人たちで画面は埋め尽くされていた。私は彼らを愛している！！私は Vim を愛している！！このエディタに出会えてとても幸せだ！この感じはかつて ed を数年使った後に vi に出会った時感じたものに似ている。今まで私が愛した ed や、まして vi を捨て去る日が来るとは考えもしなかった…あぁ神様、vi は偉大だった。でも今は、Vim。(Peter Jay Salzman, アメリカ合衆国)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
I am really happy with such a wonderful software package.  Much better than
almost any expensive, off the shelf program.  (Jeff Walker)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
こんな素晴らしいソフトウェアパッケージがあるなんて、私は本当に幸せだ。どんな高価なソフトよりも良質で、しかも在庫切れということがない。(Jeff Walker)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Whenever I reread the Vim documentation I'm overcome with excitement at the
power of the editor.  (William Edward Webber, Australia)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
Vim のドキュメントを読むといつも、エディタのパワーに興奮し打ちのめされる。(William Edward Webber, オーストラリア)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Hurrah for Vim!! It is "at your fingertips" like vi, and has the extensions
that vi sorely needs: highlighting for executing commands on blocks, an easily
navigable and digestible help screen, and more.  (Paul Pax)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
Vim 万歳！！それは vi のように "すぐ手の届くところにあり"、vi がひどく必要とした拡張がなされている: コマンドを実行すべきブロックの強調表示、簡単に操作でき消化できるヘルプ画面、その他沢山。(Paul Pax)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
The reason WHY I don't have this amazingly useful macro anymore, is that I
now use Vim - and this is built in!! (Stephen Riehm, Germany)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
私がこの素晴らしく便利なマクロをもう使わない理由は、今はそれらが組み込まれている Vim を使っているからだ。(Stephen Riehm, ドイツ)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
I am a user of Vim and I love it.  I use it to do all my programming, C,
C++, HTML what ever.  (Tim Allwine)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
私は Vim のユーザーで、それを愛している。自分の全てのプログラミング、C、C++、HTML、そのほか全てにおいて Vim を使用している。(Tim Allwine)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
I discovered Vim after years of struggling with the original vi, and I just
can't live without it anymore.  (Emmanuel Mogenet, USA)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
私はオリジナルの vi と苦闘すること数年の後に Vim を発見し、もうそれなしでは生きていけなくなった。(Emmanuel Mogenet, アメリカ合衆国)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Emacs has not a bit of chance to survive so long as Vim is around.  Besides,
it also has the most detailed software documentation I have ever seen---much
better than most commercial software!  (Leiming Qian)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
Emacs には Vim が活躍するほどに長く生き残るチャンスはこれっぽっちもない。加えて、これほどまでに詳細に渡って記されたドキュメントを持つソフトウェアを見たことがない---しかもそれは多くの商用ソフトウェアよりも素晴らしい！(Leiming Qian)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
This version of Vim will just blow people apart when they discover just how
fantastic it is! (Tony Nugent, Australia)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
この Vim のバージョンは、それがどんなに素晴らしいものが発見するたびに人々を驚愕
させるだろう！(Tony Nugent, オーストラリア)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
I took your advice & finally got Vim & I'm really impressed.  Instant convert.
(Patrick Killelea, USA)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
貴方のアドバイスに従い、ついに Vim を入手し、本当に感動した。すぐに転向した。(Patrick Killelea, アメリカ合衆国)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Vim is by far my favorite piece of shareware and I have been particularly
pleased with version 3.0.  This is really a solid piece of work.  (Robert
Colon, USA)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
Vim はとりわけ好きなシェアウェアで、特にバージョン 3.0 がお気に入りだ。これは本当にしっかりした仕事だ。(Robert Colon, アメリカ合衆国)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Vim is a joy to use, it is so well thought and practical that I wonder why
anybody would use visual development tools.  Vim is powerful and elegant, it
looks deceptively simple but is almost as complex as a 747 (especially when I
look at my growing .vimrc), keep up that wonderful job, Vim is a centerpiece
of the free software world.  (Louis-David Mitterand, USA)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
Vim を使うは楽しいし、良く考えられていとても役に立つから、何故ほかの人たちがビジュアル開発ツールを使おうとするのか理解に苦しむ。Vim はパワフルで優雅で、一見単純だが、実は 747 @{訳注: ボーイングのジェット機@} のように複雑で (とりわけ成長した私の .vimrc)、この素晴らしい仕事を続けて欲しいし、Vim はフリーソフトウェア界の中心だ。(Louis-David Mitterand, アメリカ合衆国)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
I cannot believe how great it is to use Vim.  I think the guys at work are
getting tired of hearing me bragging about it.  Others eyes are lighting up.
(Rick Croote)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
Vim を使うことがこんなに素晴らしいなんて未だに信じられない。職場の仲間は私がそれを誉めちぎるのを聞かされ過ぎて疲れているだろう。他の人の目が輝きだす。(Rick Croote)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Emacs takes way too much time to start up and run, it is too big and bulky for
effective use and the interface is more confusing than it is of any help.  Vim
however is short, it is fast, it is powerful, it has a good interface and it
is all purpose.  (Paal Ditlefsen Ekran)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
Emacs は起動と実行にかなり時間がかかり、実際に使用するには大きくかさばっていて、インターフェイスは助けになるよりもむしろ混乱させる。しかしながら Vim は小さく、早く、パワフルで、素晴らしいインターフェイスを持っていて、あらゆる用途に使うことができる。(Paal Ditlefsen)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
From the first time I got Vim3.0, I was very enthusiastic.  It has almost no
problems.  The swapfile handling and the backup possibilities are robust, also
the protection against editing one file twice.  It is very compatible to the
real VI (and that is a MUST, because my brain is trained over years in using
it).  (Gert van Antwerpen, Holland)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
Vim 3.0 を初めて得た時から、非常に熱狂した。ほとんど何の問題点もみあたらなかった。スワップファイルの扱いとバックアップの可能性が非常に堅固で、ひとつのファイルを 2 重に編集することから守ってもくれる。VI との互換性も非常に高い (この数年私の脳はすっかり VI に洗脳されているので、これは絶対条件である)。(Gert van Antwerpen, オランダ)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Visual mode in Vim is a very powerful thing! (Tony Nugent, Australia)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
Vim のビジュアルモードは、凄くパワフルな機能だ！(Tony Nugent, オーストラリア)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
I have to say that Vim is =THE= single greatest piece of source code to ever
come across the net (Jim Battle, USA).
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
Vim は今までネットに存在しなかった @{訳注: 定冠詞 THE が付く@} 唯一のもっとも偉大なソースコード作品と言わざるを得ないだろう。(Jim Battle, アメリカ合衆国)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
In fact, if you do want to get a new vi I'd suggest Vim-3.0.  This is, by
far, the best version of vi I've ever seen (Albert W. Schueller).
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
実際、新しい vi が必要ならば Vim-3.0 をお奨めする。これは今まで見たなかで断然最高のバージョンの vi だ。(Albert W. Schueller)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
I should mention that Vim is a very good editor and can compete with anything
(Ilya Beloozerov).
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
Vim は良いエディタで他の如何なるものにも匹敵するものだ、というべきだろう。(Ilya Beloozerov)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
To tell the truth sometimes I used elvis, vile, xvi, calvin, etc.  And this is
the reason that I can state that Vim is the best! (Ferenc Deak, Hungary)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
実を言えば時々 elvis、vile、xvi、calvin やその他の使っていた。だからこそ Vim が最高だと断言できる！(Ferenc Deak, ハンガリー)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Vim is by far the best editor that I have used in a long time, and I have
looked at just about every thing that is available for every platform that I
use.  Vim is the best on all of them.  (Guy L. Oliver)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
Vim は私が長年使用してきた断然最高のエディタである。そして私が使用した全てのプラットフォームに存在するいろんなものをみてきた。それらのなかでも Vim は最高だ。(Guy L. Oliver)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Vim is the greatest editor since the stone chisel.  (Jose Unpingco, USA)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
Vim は石ノミ以来、最高のエディタです。(Jose Unpingco, アメリカ合衆国)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
I would like to say that with Vim I am finally making the 'emacs to vi'
transition - as an Editor it is so much better in many ways: keyboard layout,
memory usage, text alteration to name 3.  (Mark Adam)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
こう言いたい、Vim に出会って私はついに emacs から vi に鞍替えした - あらゆる点で優れたエディタだ: キーボードレイアウト、メモリ使用量、text alteration to name 3 @{訳注: 訳不明@}。(Mark Adam)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
In fact, now if I want to know what a particular setting does in vi, I fire up
Vim and check out its help!  (Nikhil Patel, USA)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
実際、今 vi 独特の設定について知りたいのならば、Vim を起動してそのヘルプをチェックする！(Nikhil Patel, アメリカ合衆国)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
As a vi user, Vim has made working with text a far more pleasant task than
before I encountered this program.  (Steinar Knutsen, Norway)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
vi ユーザーとして、Vim はテキストに関わる仕事を以前に遭遇していたよりも、はるかに愉快なものにしてくれた。(Steinar Knutsen, ノルウェー)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
I use Vim since version 3.0.  Since that time, it is the ONLY editor I use,
with Solaris, Linux and OS/2 Warp.  I suggest all my friends to use Vim, they
try, and they continue using it.  Vim is really the best software I have ever
downloaded from the Internet, and the best editor I know of.  (Marco
Eccettuato, Italy)
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
Vim をバージョン 3.0 から使っている。そのころから、Solaris、Linux、そして OS/2Warp で使用した唯一のエディタだった。友達全員に Vim を使うように薦め、彼らはトライし、今も使い続けている。Vim はインターネットからダウンロードした中で本当に最高のソフトウェアであり、知りうる限りで最高のエディタである。(Marco Eccettuato, イタリア)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
In summary:
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
以上、要約すれば: (Vim が熱いぜ!)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
     __     ___		    _	    _	_  ___ _____ `
     \ \   / (_)_ __ ___   (_)___  | | | |/ _ \_   _| `
      \ \ / /| | '_ ` _ \  | / __| | |_| | | | || | `
       \ V / | | | | | | | | \__ \ |  _  | |_| || | `
	\_/  |_|_| |_| |_| |_|___/ |_| |_|\___/ |_| `
	     ____ _____ _   _ _____ _____ _ _ `
	    / ___|_   _| | | |	___|  ___| | | `
	    \___ \ | | | | | | |_  | |_  | | | `
	     ___) || | | |_| |	_| |  _| |_|_| `
	    |____/ |_|	\___/|_|   |_|	 (_|_)	    (Tony Nugent, Australia) `
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@verbatim
__     ___             _       _   _  ___ _____ `
\ \   / (_)_ __ ___   (_)___  | | | |/ _ \_   _| `
 \ \ / /| | '_ ` _ \  | / __| | |_| | | | || | `
  \ V / | | | | | | | | \__ \ |  _  | |_| || | `
   \_/  |_|_| |_| |_| |_|___/ |_| |_|\___/ |_| `
         ____ _____ _   _ _____  _____ _ _ `
        / ___|_   _| | | |   ___|  ___| | | `
        \___ \ | | | | | | |_   | |_  | | | `
        ___)  || | | |_| |  _|  |  _| |_|_| `
        |____/ |_|  \___/|_|    |_|   (_|_)      (Tony Nugent, Australia) `
@end verbatim
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
 vim:tw=78:ts=8:ft=help:norl:
@end ifset
