@ifset JA  @c ----------- v -----------  JA  -*- tab-width: 8 -*-
@node rileft.txt, , , 目次
@unnumbered 右横書き (書字方向が右から左になるモード)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
*rileft.txt*    For Vim version 8.1.  Last change: 2006 Apr 24


		  VIM REFERENCE MANUAL    by Avner Lottem
					  updated by Nadim Shaikli
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@verbatim
*rileft.txt*    For Vim バージョン 8.1.  Last change: 2006 Apr 24


        VIMリファレンスマニュアル    by Avner Lottem
                         updated by Nadim Shaikli
@end verbatim
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
Right to Left display mode for Vim				*rileft*
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{rileft}
@cindex rileft
Vim における "右左" 書きとヘブライマッピング
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
These functions were originally created by Avner Lottem:
   E-mail: alottem@iil.intel.com
   Phone:  +972-4-8307322
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
これらの機能は Avner Lottem によって作成された

E-mail: alottem@@iil.intel.com @*
Phone:  +972-4-8307322
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
{Vi does not have any of these commands}
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@{Vi にはこれらのコマンドはない@}
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
								*E26*
{only available when compiled with the |+rightleft| feature}
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{E26}
@erindex E26
@{Vim が |@ref{+rightleft}| 機能付きでコンパイルされたときのみ有効@}
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
Introduction
------------
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@unnumberedsec はじめに
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
Some languages such as Arabic, Farsi, Hebrew (among others) require the
ability to display their text from right-to-left.  Files in those languages
are stored conventionally and the right-to-left requirement is only a
function of the display engine (per the Unicode specification).  In
right-to-left oriented files the characters appear on the screen from
right to left.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
アラビア語、ペルシア語、ヘブライ語など、いくつかの言語では文章を右から左へ表示する。これらの言語で書かれたファイルは普通に記録され、右から左へ表示するのはグラフィックエンジンの機能である (Unicode を利用して)。右左指向ファイルでは文字は画面の右から左へ書かれる。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Bidirectionality (or bidi for short) is what Unicode offers as a full
solution to these languages.  Bidi offers the user the ability to view
both right-to-left as well as left-to-right text properly at the same time
within the same window.  Vim currently, due to simplicity, does not offer
bidi and is merely opting to present a functional means to display/enter/use
right-to-left languages.  An older hybrid solution in which direction is
encoded for every character (or group of characters) are not supported either
as this kind of support is out of the scope of a simple addition to an
existing editor (and it's not sanctioned by Unicode either).
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
双方向性 (Bidirectionality 略して bidi) は Unicode がこれらの言語を扱うために提供しているものである。双方向性はユーザーが "右から左" のテキストと "左から右" のテキストを同時に同じウィンドウで適切に表示できるようにする。Vim は現在のところ、簡素でいるために、双方向性を提供していない。単に "右から左" 言語を表示、入力、使用する機能を提供している。古い混在方法、文字単位 (または複数文字) で表示する方向を決める方法はサポートされていない。そして、この種のサポートは既存のエディタに簡単に加えることはできない (そして Unicode でも承認されていない)。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
Highlights
----------
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@unnumberedsec 概要
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
o  Editing left-to-right files as in the original Vim, no change.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@itemize
@item"左右" ファイルの編集はオリジナルの Vim と同じで、変更はない
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  Viewing and editing files in right-to-left windows.  File orientation
   is per window, so it is possible to view the same file in right-to-left
   and left-to-right modes, simultaneously.  (Useful for editing mixed files
   in which both right-to-left and left-to-right text exist).
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item "右から左" ウィンドウでファイルを閲覧、編集できる。ファイルはウィンドウ単位で指向方向を選択できるので、同じファイルを "右左" と "左右" ウィンドウで同時に閲覧することが可能である。(これは表示方向の違う複数の言語が混在している時に便利である)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  Compatibility to the original Vim.  Almost all features work in
   right-to-left mode (see Bugs below).
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item オリジナルの Vim との互換性。ほとんど全ての機能が "右左" モードでも使用できる。(下記「バグ」の章を参照)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  Backing from reverse insert mode to the correct place in the file
   (if possible).
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item 反転入力モードからの復帰がファイルの正しい場所で行われる (可能な限り)。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  No special terminal with right-to-left capabilities is required.  The
   right-to-left changes are completely hardware independent.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item "右左" 機能を使用するのに特別な端末を必要としない。"右左" 拡張機能は完全にハードウェア非依存である。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  Many languages use and require right-to-left support.  These languages
   can quite easily be supported given the inclusion of their required
   keyboard mappings and some possible minor code change.  Some of the
   current supported languages include - |arabic.txt|, |farsi.txt| and
   |hebrew.txt|.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item たくさんの言語が "右左" 言語サポートを必要とする。このサポートに手を加え他の "右左" 言語 (アラビア語など) に対応させるのは簡単だろう。文字エンコードに合わせてキーボードマッピングを変更したり、ほんの少しコードに手を加えればいい。現在はこれら |@ref{arabic.txt}|, |@ref{farsi.txt}|, |@ref{hebrew.txt}| の言語サポートを含んでいる。
@end itemize
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
Of Interest...
--------------
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@unnumberedsec 重要
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  Invocations
   -----------
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@unnumberedsubsec 機能を有効にするために
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
   + 'rightleft' ('rl') sets window orientation to right-to-left.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@itemize
@item '@option{rightleft}' ('@option{rl}') ウィンドウを "右から左" 指向に設定する。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
   + 'delcombine' ('deco'), boolean, if editing UTF-8 encoded languages,
     allows one to remove a composing character which gets superimposed
     on those that proceeded them (some languages require this).
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item '@option{delcombine}' ('@option{deco}')。真偽値。UTF-8 でエンコードされた言語を編集中に合成文字を構成している文字を削除すると合成文字全体を削除する。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
   + 'rightleftcmd' ('rlc') sets the command-line within certain modes
     (such as search) to be utilized in right-to-left orientation as well.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item '@option{rightleftcmd}' ('@option{rlc}') "右から左" 指向で便利なように、あるモード (検索など) のコマンドラインの入力方法を設定する。
@end itemize
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  Typing backwards					*ins-reverse*
   ----------------
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{ins-reverse}
@cindex ins-reverse
@cindex 後方タイピング
@unnumberedsubsec 後方タイピング
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
   In lieu of using full-fledged the 'rightleft' option, one can opt for
   reverse insertion.  When the 'revins' (reverse insert) option is set,
   inserting happens backwards.  This can be used to type right-to-left
   text.  When inserting characters the cursor is not moved and the text
   moves rightwards.  A <BS> deletes the character under the cursor.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
全面的に '@option{rightleft}' オプションを使う代わりに、もう 1 つ逆方向に挿入する方法がある。'@option{revins}' (逆挿入) オプションが有効になっていると、挿入した文字が後方に流れていく。"右左" 方向のテキストを入力するのに使える。キャラクタを挿入すると、カーソルはその場から動かずテキストが右へ流れていく。@key{<BS>} はカーソルの下の文字を削除する。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
   CTRL-W and CTRL-U also work in the opposite direction.  <BS>, CTRL-W
   and CTRL-U do not stop at the start of insert or end of line, no matter
   how the 'backspace' option is set.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@kbd{CTRL-W} と @kbd{CTRL-U} も反対の方向へ働く。'@option{backspace}' オプションが指定されているかにかかわらず @key{<BS>}、@kbd{CTRL-W}、@kbd{CTRL-U} は入力の開始点や行末で停止しない。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
   There is no reverse replace mode (yet).
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
(まだ) 逆置換モードは実装されていない。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
   If the 'showmode' option is set, "-- REVERSE INSERT --" will be shown
   in the status line when reverse Insert mode is active.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
'@option{showmode}' オプションが設定されていると、逆挿入モードが有効になっている時には状態表示行 (ステータスライン) に "@samp{-- REVERSE INSERT --}" が表示されるだろう。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  Pasting when in a rightleft window
   ----------------------------------
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@unnumberedsubsec "右左" ウィンドウでの貼り付け
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
   When cutting text with the mouse and pasting it in a rightleft window
   the text will be reversed, because the characters come from the cut buffer
   from the left to the right, while inserted in the file from the right to
   the left.   In order to avoid it, toggle 'revins' before pasting.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
マウスでカットした文章を "右左" ウィンドウに貼り付けると、"左右" バッファからカットされたバッファの文字を "右左" ファイルへ入力することになるので、テキストは反転される。これを避けるには貼り付け前に '@option{revins}' を切り替える。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
Bugs
----
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@unnumberedsec バグ
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
o  Does not handle CTRL-A and CTRL-X commands (add and subtract) correctly
   when in rightleft window.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@itemize
@item "右左" ウィンドウでは @kbd{CTRL-A} と @kbd{CTRL-X} (足し算、引き算) コマンドは正しく働かない。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  Does not support reverse insert and rightleft modes on the command-line.
   However, functionality of the editor is not reduced, because it is
   possible to enter mappings, abbreviations and searches typed from the
   left to the right on the command-line.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item 逆挿入とコマンドラインでの "右左" モードはサポートされない。しかしながらマッピング、短縮入力、検索、コマンドラインでの "左右" 入力が可能なので、エディタの機能性はそこなわれない
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  Somewhat slower in right-to-left mode, because right-to-left motion is
   emulated inside Vim, not by the controlling terminal.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item "右左" モードでは多少遅くなる。"右左" の動作は端末制御ではなく Vim でのエミュレーションによって実現されているため。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  When the Athena GUI is used, the bottom scrollbar works in the wrong
   direction.  This is difficult to fix.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item Athena GUI を使用すると、下スクロールバーが間違った方向に働く。これを修正するのは難しい。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  When both 'rightleft' and 'revins' are on: 'textwidth' does not work.
   Lines do not wrap at all; you just get a single, long line.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item '@option{rightleft}' と '@option{revins}' が両方とも有効になっていると: '@option{textwidth}' が動作しない。行が折り返されない; 長い行が作成される。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
o  There is no full bidirectionality (bidi) support.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item すべての双方向性 (bidi) をサポートしているわけではない。
@end itemize
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
 vim:tw=78:ts=8:noet:ft=help:norl:
@end ifset
