@ifset JA  @c ----------- v -----------  JA  -*- tab-width: 8 -*-
@node sponsor.txt, , , 目次
@unnumbered sponsor.txt
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
*sponsor.txt*   For Vim version 8.0.  Last change: 2008 Jun 21


		  VIM REFERENCE MANUAL    by Bram Moolenaar
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@cindex sponsor.txt
@verbatim
*sponsor.txt*   For Vim バージョン 8.0.  Last change: 2008 Jun 21


		  VIMリファレンスマニュアル    by Bram Moolenaar
@end verbatim
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------



@ifset EN
SPONSOR VIM DEVELOPMENT						*sponsor*
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{sponsor}
@cindex sponsor
@section 開発支援 (スポンサー)
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Fixing bugs and adding new features takes a lot of time and effort.  To show
your appreciation for the work and motivate Bram and others to continue
working on Vim please send a donation.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
バグの修正や新機能の追加には多くの時間と努力が必要です。その仕事に対するあなたの評価を形にするために、また、Bram や他の人の Vim を開発しようとする気持ちを継続させるために、寄付をお願いしています。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Since Bram is back to a paid job the money will now be used to help children
in Uganda.  See |uganda|.  But at the same time donations increase Bram's
motivation to keep working on Vim!
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
Bram は再び就職したため、寄付金はウガンダの子供達を援助するために使われます。|uganda| を参照してください。寄付は Bram が Vim の開発を継続するための励みにもなっています。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
For the most recent information about sponsoring look on the Vim web site:

	http://www.vim.org/sponsor/

More explanations can be found in the |sponsor-faq|.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
開発支援に関する最新の情報は Vim のウェブサイトを参照ください。

@url{http://www.vim.org/sponsor/}

|@ref{sponsor-faq, , sponsor-faq}| にさらに説明があります。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
REGISTERED VIM USER						*register*
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{register}
@cindex register
@section ユーザー登録
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
You can become a registered Vim user by sending at least 10 euro.  This works
similar to sponsoring Vim, see |sponsor| above.  Registration was made
possible for the situation where your boss or bookkeeper may be willing to
register software, but does not like the terms "sponsoring" and "donation".
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
10 ユーロ以上の送金で Vim の登録ユーザーになれます。これは開発支援と似たようなものです。上記 |sponsor| を参照してください。上司や帳簿係はソフトウェアに出費してくれるが、"開発支援" や "寄付"という名目では問題がある、という場合に使ってください。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
More explanations can be found in the |register-faq|.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
|register-faq| にさらに説明があります。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
VOTE FOR FEATURES					*vote-for-features*
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{vote-for-features}
@cindex vote-for-features
@section 機能への投票
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
To give registered Vim users and sponsors an advantage over lurkers they can
vote for the items Bram should work on.  How does this voting work?
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
登録ユーザーやスポンサーには、Bram がするべき作業を決定するための投票権が与えられます。投票の手順は次のとおりです。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
1.  You send at least 10 euro.  See below for ways to transfer money
    |send-money|.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@enumerate
@item 10 ユーロ以上送金をしてください。送金方法は下記を参照してください。|@ref{send-money, , send-money}|
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
2.  You will be e-mailed a registration key.  Enter this key on your account
    page on the Vim website.  You can easily create an account if you don't
    have one yet.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item 登録キーが送られてくるので、そのキーを Vim のウェブサイトにあるご自身のアカウントページで入力してください。アカウントを持っていなかったとしても、簡単に作ることができます。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
3.  You can enter your votes on the voting page.  There is a link to that page
    on your account page after entering a registration key.  Your votes will
    be counted for two years.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item 投票ページで投票します。登録キーを入力すると、投票ページへのリンクがアカウントページに作成されます。票は二年間有効です。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
4.  The voting results appear on the results page, which is visible for
    everybody:  http://www.vim.org/sponsor/vote_results.php
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item 結果は投票結果ページで確認できます。このページはだれでも見ることができます。@url{http://www.vim.org/sponsor/vote_results.php}
@end enumerate
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Additionally, once you have sent 100 euro or more in total, your name appears
in the "Vim hall of honour":   http://www.vim.org/sponsor/hall_of_honour.php
But only if you enable this on your account page.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
送金額が合計で 100 ユーロを越えると、名誉の殿堂 (Vim hall of honour) にあなたの名前が載ります。@url{http://www.vim.org/sponsor/hall_of_honour.php} しかしそれは、あなたが自分のアカウントページでそれを許可した場合のみです。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
HOW TO SEND MONEY						*send-money*
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{send-money}
@cindex send-money
@section 送金方法
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Credit card	Through PayPal, see the PayPal site for information:
			https://www.paypal.com/en_US/mrb/pal=XAC62PML3GF8Q
		The e-mail address for sending sponsorship money is:
			donate@vim.org
		The e-mail address for Vim registration is:
			register@vim.org
		Using Euro is preferred, other currencies are also accepted.
		In Euro countries a bank transfer is preferred, this has lower
		costs.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@table @asis
@item クレジットカード
クレジットカードでの送金には PayPal を使ってください。詳しいことは PayPal のサイトを参照してください:@*@*
@url{https://www.paypal.com/en_US/mrb/pal=XAC62PML3GF8Q}@*@*
開発支援の送金のためのメールアドレスはこれです:@*@*
@email{donate@@vim.org}@*@*
ユーザー登録のためのメールアドレスはこれです:@*@*
@email{register@@vim.org}@*@*
なるべくユーロを使って欲しいのですが、他の通貨も受け付けています。ヨーロッパ在住なら銀行振込の方が手数料が安いです。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Other methods	See |iccf-donations|.
		Include "Vim sponsor" or "Vim registration" in the comment of
		your money transfer.  Send me an e-mail that mentions the
		amount you transferred if you want to vote for features and
		show others you are a registered Vim user or sponsor.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item 他の方法
|@ref{iccf-donations, , iccf-donations}| を参照してください。送金するときにコメント欄に "Vim sponsor" か "Vim registration" と記入してください。あなたが Vim の登録ユーザーやスポンサーであることを他の人に分かるようにしたり、機能へ投票したい場合は、いくら送金したのかを、私にメールで知らせてください。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Cash		Small amounts can be sent with ordinary mail.  Put something
		around the money, so that it's not noticeable from the
		outside.  Mention your e-mail address if you want to vote for
		features and show others you are a registered Vim user or
		sponsor.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item 現金
少額の場合は郵送することもできます。お金は、外から見えないように、何かで包装してください。あなたが Vim の登録ユーザーやスポンサーであることを他の人に分かるようにしたり、機能へ投票したい場合は、あなたのメールアドレスを書き添えてください。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
You can use this permanent address:
			Bram Moolenaar
			Finsterruetihof 1
			8134 Adliswil
			Switzerland
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@item 送付先の住所は次のとおりです:
Bram Moolenaar@*
Finsterruetihof 1@*
8134 Adliswil@*
Switzerland
@end table
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------



@ifset EN
QUESTIONS AND ANSWERS				*sponsor-faq* *register-faq*
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{sponsor-faq}
@anchor{register-faq}
@cindex sponsor-faq
@cindex register-faq
@section 質問と回答
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Why should I give money?

If you do not show your appreciation for Vim then Bram will be less motivated
to fix bugs and add new features.  He will do something else instead.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
なぜ送金しないといけないの？

Vim に対する評価を形にしなかった場合、バグを修正したり新機能を追加しようとするBram の動機が弱まります。彼は何か他のことをするでしょう。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
How much money should I send?

That is up to you.  The more you give, the more children will be helped.
An indication for individuals that use Vim at home: 10 Euro per year.  For
professional use: 30 Euro per year per person.  Send at least 10 euro to be
able to vote for features.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
いくら送金すればいいの？

いくらでも結構です。たくさん送金すれば、たくさんの子供達が救われます。目安としては、ホームユーザーなら年に 10 ユーロ、仕事で使う場合は一人あたり年に 30 ユーロほどでしょうか。10 ユーロ以上送金すると機能へ投票できるようになります。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
What do I get in return?

Each registered Vim user and sponsor who donates at least 10 euro will be able
to vote for new features.  These votes will give priority to the work on Vim.
The votes are valid for two years.  The more money you send the more your
votes count |votes-counted|.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
何かいいことあるの？

10 ユーロ以上寄付した登録ユーザーとスポンサーは新機能へ投票できます。投票によって Vim 開発の優先順位が決まります。票は二年間有効です。金額が大きいほど投票得点が大きくなります |@ref{votes-counted, , votes-counted}|。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
If you send 100 Euro or more in total you will be mentioned on the "Vim hall
of honour" page on the Vim web site.  But only if you enable this on your
account page.  You can also select whether the amount will be visible.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
送金額が合計で 100 ユーロ以上になると、名誉の殿堂 (Vim hall of honour) にあなたの名前が載ります。しかしそれは、あなたが自分のアカウントページでそれを許可した場合のみです。金額を表示するかどうかを選択することもできます。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
How do I become a Vim sponsor or registered Vim user?

Send money, as explained above |send-money| and include your e-mail address.
When the money has been received you will receive a unique registration key.
This key can be used on the Vim website to activate voting on your Vim
account.  You will then get an extra page where you can vote for features and
choose whether others will be able to see that you donated.  There is a link
to this page on your "My Account" page.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
登録ユーザーやスポンサーになるにはどうすればいいの？

上記 |@ref{send-money, , send-money}| に従って送金し、メールアドレスを知らせてください。送金が完了すると、登録キーが送付されます。登録キーは Vim のウェブサイトのアカウントで、機能へ投票できるようにするために使います。登録キーを使うと、投票ページが追加されます。あなたが寄付したことを他の人が確認できるかどうかを設定することもできます。そのページへのリンクは "My Account" ページにあります。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
What is the difference between sponsoring and registering?

It has a different name.  Use the term "registration" if your boss doesn't
like "sponsoring" or "donation".  The benefits are the same.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
登録ユーザーとスポンサーの違いは？

名前が違うだけです。あなたの上司が "開発支援" や "寄付" を好まない場合に "ユーザー登録" という名目を使ってください。特典は同じです。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
How can I send money?

See |send-money|.  Check the web site for the most recent information:
http://www.vim.org/sponsor/
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
どうやって送金するの？

|send-money| を参照してください。最新情報はウェブサイトで確認してください:
@url{http://www.vim.org/sponsor/}
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
Why don't you use the SourceForge donation system?

SourceForge takes 5% of the donations for themselves.  If you want to support
SourceForge you can send money to them directly.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
なぜ SourceForge の寄付システムを使わないの？

SourceForge は寄付金の 5% を手数料として取るからです。SouceForge を支援したい場合は直接彼らに送金してください。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
I cannot afford to send money, may I still use Vim?

Yes.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
私には送金するほど経済的余裕がありません。それでも Vim を使えますか？

はい。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
I did not register Vim, can I use all available features?

Yes.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
私はユーザー登録してません。すべての機能を使えますか？

はい。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
I noticed a bug, do I need to register before I can report it?

No, suggestions for improving Vim can always be given.  For improvements use
the developer |maillist|, for reporting bugs see |bugs|.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
バグを発見しました。報告するにはユーザー登録が必要ですか？

必要ありません。Vim をより良くするための提案はいつでも歓迎します。改良に関しては開発メーリングリスト |@ref{maillist, ,maillist|} を使ってください。バグ報告に関しては |bugs| を参照してください。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
How are my votes counted?				*votes-counted*
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{votes-counted}
@cindex votes-counted
@section 私の投票はどのように集計されるのですか？
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
You may vote when you send 10 euro or more.  You can enter up to ten votes.
You can select the same item several times to give it more points.  You can
also enter three counter votes, these count as negative points.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
10 ユーロ以上送金すると投票できるようになります。10 票まで投票できます。複数のポイントを入れるために、同じ項目に複数の票を入れることもできます。3 票の反対票を入れることもできます。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
When you send 30 euro or more the points are doubled.  Above 100 euro they
count four times, above 300 euro they count six times, above 1000 euro ten
times.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
30 ユーロ以上送金するとポイントが倍になります。100 ユーロなら 4 倍、300 ユーロなら 6 倍、1000 ユーロ以上なら 10 倍です。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
Can I change my votes?

You can change your votes any time you like, up to two years after you
sent money.  The points will be counted right away.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
投票先を変更できますか？

いつでも好きなときに投票先を変更できます。票は送金してから二年間有効です。ポイントはただちに反映されます。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
Can I add an item to vote on?

Not directly.  You can suggest items to vote on to Bram.  He will consider
fitting your item into the list.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
投票したい項目を追加できますか？

直接はできません。投票したい項目について Bram に相談してください。その項目を一覧に加えるかどうかは彼が判断します
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
How about Charityware?

Currently the Vim donations go to |uganda| anyway.  Thus it doesn't matter if
you sponsor Vim or ICCF.  Except that Vim sponsoring will allow you to vote
for features.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
チャリティウェアとは？

現在、Vim への寄付金は |@ref{uganda, , udanda}| に送金されます。そのため、Vim を支援するのと ICCF を支援するのは、機能へ投票できるかどうかの違いしかありません。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
I donated $$$, now please add feature XYZ!

There is no direct relation between your donation and the work Bram does.
Otherwise you would be paying for work and we would have to pay tax over the
donation.  If you want to hire Bram for specific work, contact him directly,
don't use the donation system.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
私は $$$ 円寄付しました。XYZ の機能を加えてください。

Bram の作業と寄付の間に直接的な関係はありません。対価が仕事に対して支払われるとすると、私たちはその寄付に関して納税しなければなりません。特定の仕事のために Bram を雇いたい場合は、寄付ではなく、彼に直接連絡してください。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
Are the donations tax deductible?

That depends on your country.  The donations to help the children in |Uganda|
are tax deductible in Holland, Germany, Canada and in the USA.  See the ICCF
website http://iccf-holland.org/donate.html.  You must send an e-mail to Bram
to let him know that the donation is done because of the use of Vim.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
寄付金は税金控除の対象になりますか？

国によって違います。|@ref{Uganda, , Uganda}| の子供達を援助するための寄付は、オランダ、ドイツ、カナダ、アメリカ、で税金が控除されます。ICCF のウェブサイトを参照してください @url{http://iccf-holland.org/donate.html}。 Vim を使用することに対して寄付したことを、メールで Bram に知らせてください。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
Can you send me a bill?

No, because there is no relation between the money you send and the work that
is done.  But a receipt is possible.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
明細書はもらえますか？

いいえ。なぜなら、寄付金と仕事の間には関係がないからです。領収書なら発行できます。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------



@ifset EN
 vim:tw=78:ts=8:ft=help:norl:
@end ifset
