@ifset JA  @c ----------- v -----------  JA  -*- tab-width: 8 -*-
@node usr_toc.txt, usr_01.txt
@unnumbered 目次
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
*usr_toc.txt*	For Vim version 8.0.  Last change: 2016 Mar 25

		     VIM USER MANUAL - by Bram Moolenaar

			      Table Of Contents			*user-manual*
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{user-manual}
@cindex user-manual
@verbatim
*usr_toc.txt*   For Vim バージョン 8.0.  Last change: 2016 Mar 25

		     VIM USER MANUAL - by Bram Moolenaar

			      目次
@end verbatim
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
==============================================================================
Overview ~

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@menu
大見出し一覧

@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
Getting Started
|usr_01.txt|  About the manuals
|usr_02.txt|  The first steps in Vim
|usr_03.txt|  Moving around
|usr_04.txt|  Making small changes
|usr_05.txt|  Set your settings
|usr_06.txt|  Using syntax highlighting
|usr_07.txt|  Editing more than one file
|usr_08.txt|  Splitting windows
|usr_09.txt|  Using the GUI
|usr_10.txt|  Making big changes
|usr_11.txt|  Recovering from a crash
|usr_12.txt|  Clever tricks
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
初級編
* usr_01.txt:: マニュアルについて
* usr_02.txt:: 初めての Vim
* usr_03.txt:: カーソルの移動
* usr_04.txt:: 簡単な編集
* usr_05.txt:: 設定の変更
* usr_06.txt:: 構文強調表示
* usr_07.txt:: 複数のファイルを開く
* usr_08.txt:: ウィンドウの分割
* usr_09.txt:: GUI を使う
* usr_10.txt:: 大規模な編集
* usr_11.txt:: クラッシュからの復帰
* usr_12.txt:: 便利な小技
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
Editing Effectively
|usr_20.txt|  Typing command-line commands quickly
|usr_21.txt|  Go away and come back
|usr_22.txt|  Finding the file to edit
|usr_23.txt|  Editing other files
|usr_24.txt|  Inserting quickly
|usr_25.txt|  Editing formatted text
|usr_26.txt|  Repeating
|usr_27.txt|  Search commands and patterns
|usr_28.txt|  Folding
|usr_29.txt|  Moving through programs
|usr_30.txt|  Editing programs
|usr_31.txt|  Exploiting the GUI
|usr_32.txt|  The undo tree

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
上級編
* usr_20.txt:: コマンドラインを素早く入力する
* usr_21.txt:: 中断と再開
* usr_22.txt:: ファイルを探す
* usr_23.txt:: 特殊なファイルを編集する
* usr_24.txt:: 素早く入力する
* usr_25.txt:: テキストの整形
* usr_26.txt:: 繰り返し
* usr_27.txt:: 検索コマンドと正規表現
* usr_28.txt:: 折り畳み
* usr_29.txt:: プログラムの中を移動する
* usr_30.txt:: プログラムの編集
* usr_31.txt:: GUI を活用する
* usr_32.txt:: undo ツリー
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Tuning Vim
|usr_40.txt|  Make new commands
|usr_41.txt|  Write a Vim script
|usr_42.txt|  Add new menus
|usr_43.txt|  Using filetypes
|usr_44.txt|  Your own syntax highlighted
|usr_45.txt|  Select your language
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
カスタマイズ
* usr_40.txt:: 新しいコマンドを作る
* usr_41.txt:: Vim script 書法
* usr_42.txt:: 新しいメニューを追加する
* usr_43.txt:: ファイルタイプを使う
* usr_44.txt:: 構文ファイルを作成する
* usr_45.txt:: 言語を選択する
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Making Vim Run
|usr_90.txt|  Installing Vim
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
インストール
* usr_90.txt:: Vim のインストール
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
Reference manual
|reference_toc|     More detailed information for all commands
@end ifset

@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
リファレンスマニュアル
@c |@ref{reference_toc, , reference_toc}| 全コマンドの詳細情報

インデックス
@c * Indexes::
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
The user manual is available as a single, ready to print HTML and PDF file
here:
	http://vimdoc.sf.net
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------

シングルファイルで印刷に適した HTML 形式と PDF 形式のユーザーマニュアルが用意されています:
    @url{http://vimdoc.sf.net}
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
==============================================================================
Getting Started ~

Read this from start to end to learn the essential commands.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
初級編

最初から順番に読んで基本的なコマンドを学びましょう。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_01.txt|  About the manuals
		|01.1|	Two manuals
		|01.2|	Vim installed
		|01.3|	Using the Vim tutor
		|01.4|	Copyright
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
|@ref{usr_01.txt, , usr_01}| マニュアルについて
@detailmenu
* 01.1 :: 2 つのマニュアル
* 01.2 :: Vim の準備
* 01.3 :: チュートリアル
* 01.4 :: 著作権 (Copyright)
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_02.txt|  The first steps in Vim
		|02.1|	Running Vim for the First Time
		|02.2|	Inserting text
		|02.3|	Moving around
		|02.4|	Deleting characters
		|02.5|	Undo and Redo
		|02.6|	Other editing commands
		|02.7|	Getting out
		|02.8|	Finding help
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
|@ref{usr_02.txt, , usr_02}| 初めての Vim
@detailmenu
* 02.1:: Vim の起動方法
* 02.2:: 文字の挿入
* 02.3:: カーソル移動
* 02.4:: 文字の削除
* 02.5:: undo (取り消し) と redo (やり直し)
* 02.6:: 他の編集コマンド
* 02.7:: Vim の終了
* 02.8:: ヘルプの引き方
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_03.txt|  Moving around
		|03.1|	Word movement
		|03.2|	Moving to the start or end of a line
		|03.3|	Moving to a character
		|03.4|	Matching a paren
		|03.5|	Moving to a specific line
		|03.6|	Telling where you are
		|03.7|	Scrolling around
		|03.8|	Simple searches
		|03.9|	Simple search patterns
		|03.10|	Using marks
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
|@ref{usr_03.txt, , usr_03}| カーソルの移動
@detailmenu
* 03.1:: 単語ごとの移動
* 03.2:: 行頭、行末への移動
* 03.3:: 文字への移動
* 03.4:: カッコの対応
* 03.5:: 特定の行への移動
* 03.6:: 現在の場所を表示
* 03.7:: スクロール
* 03.8:: 簡単な検索
* 03.9:: 簡単なパターン検索
* 03.10:: マークの使用
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_04.txt|  Making small changes
		|04.1|	Operators and motions
		|04.2|	Changing text
		|04.3|	Repeating a change
		|04.4|	Visual mode
		|04.5|	Moving text
		|04.6|	Copying text
		|04.7|	Using the clipboard
		|04.8|	Text objects
		|04.9|	Replace mode
		|04.10|	Conclusion

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
|@ref{usr_04.txt, , usr_04}| 簡単な編集
@detailmenu
* 04.1:: オペレータとモーション
* 04.2:: テキストの変更
* 04.3:: 変更の繰り返し
* 04.4:: ビジュアルモード
* 04.5:: テキストの移動
* 04.6:: テキストのコピー
* 04.7:: クリップボード
* 04.8:: テキストオブジェクト
* 04.9:: 置換モード
* 04.10:: 終わりに
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_05.txt|  Set your settings
		|05.1|	The vimrc file
		|05.2|	The example vimrc file explained
		|05.3|	Simple mappings
		|05.4|	Adding a package
		|05.5|	Adding a plugin
		|05.6|	Adding a help file
		|05.7|	The option window
		|05.8|	Often used options

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
|@ref{usr_05.txt, , usr_05}| 設定の変更
@detailmenu
* 05.1:: vimrc ファイル
* 05.2:: 見本 vimrc ファイルの解説
* 05.3:: 簡単なマップ
* 05.4:: パッケージの追加
* 05.5:: プラグインの追加
* 05.6:: ヘルプファイルの追加
* 05.7:: オプションウィンドウ
* 05.8:: よく使うオプション
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_06.txt|  Using syntax highlighting
		|06.1|	Switching it on
		|06.2|	No or wrong colors?
		|06.3|	Different colors
		|06.4|	With colors or without colors
		|06.5|	Printing with colors
		|06.6|	Further reading

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
|@ref{usr_06.txt, , usr_06}| 構文強調表示
@detailmenu
* 06.1:: 構文強調表示を有効にする
* 06.2:: 色がつかない？変な色になる？
* 06.3:: 色を変える
* 06.4:: カラーを使う？使わない？
* 06.5:: カラー印刷
* 06.6:: 詳しい情報
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_07.txt|  Editing more than one file
		|07.1|	Edit another file
		|07.2|	A list of files
		|07.3|	Jumping from file to file
		|07.4|	Backup files
		|07.5|	Copy text between files
		|07.6|	Viewing a file
		|07.7|	Changing the file name

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
|@ref{usr_07.txt, , usr_07}| 複数のファイルを開く
@detailmenu
* 07.1:: 他のファイルを開く
* 07.2:: ファイルのリスト
* 07.3:: 他のファイルにジャンプする
* 07.4:: バックアップファイル
* 07.5:: 他のファイルにテキストをコピーする
* 07.6:: 読み込み専用モード
* 07.7:: ファイル名の変更
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_08.txt|  Splitting windows
		|08.1|	Split a window
		|08.2|	Split a window on another file
		|08.3|	Window size
		|08.4|	Vertical splits
		|08.5|	Moving windows
		|08.6|	Commands for all windows
		|08.7|	Viewing differences with vimdiff
		|08.8|	Various

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
|@ref{usr_08.txt, , usr_08}| ウィンドウの分割
@detailmenu
* 08.1:: ウィンドウの分割
* 08.2:: ウィンドウを分割してファイルを開く
* 08.3:: ウィンドウのサイズ
* 08.4:: 縦分割
* 08.5:: ウィンドウの移動
* 08.6:: 全ウィンドウを対象とするコマンド
* 08.7:: vimdiff で差分を表示する
* 08.8:: その他
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_09.txt|  Using the GUI
		|09.1|	Parts of the GUI
		|09.2|	Using the mouse
		|09.3|	The clipboard
		|09.4|	Select mode

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
|@ref{usr_09.txt, , usr_09}| GUI を使う
@detailmenu
* 09.1:: GUI の部品
* 09.2:: GUI でマウスを使う
* 09.3:: GUI でクリップボード
* 09.4:: GUI で選択モード
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_10.txt|  Making big changes
		|10.1|	Record and playback commands
		|10.2|	Substitution
		|10.3|	Command ranges
		|10.4|	The global command
		|10.5|	Visual block mode
		|10.6|	Reading and writing part of a file
		|10.7|	Formatting text
		|10.8|	Changing case
		|10.9|	Using an external program

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
|@ref{usr_10.txt, , usr_10}| 大規模な編集
@detailmenu
* 10.1:: 操作の記録と再実行
* 10.2:: 置換
* 10.3:: コマンドの範囲指定
* 10.4:: global コマンド
* 10.5:: 矩形選択
* 10.6:: ファイルの一部の保存と読み込み
* 10.7:: テキストの整形
* 10.8:: 大文字/小文字の変換
* 10.9:: 外部プログラムを使う
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_11.txt|  Recovering from a crash
		|11.1|	Basic recovery
		|11.2|	Where is the swap file?
		|11.3|	Crashed or not?
		|11.4|	Further reading

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
|@ref{usr_11.txt, , usr_11}| クラッシュからの復帰
@detailmenu
* 11.1:: リカバリの基本
* 11.2:: スワップファイルはどこにある？
* 11.3:: クラッシュした？
* 11.4:: さらなる情報
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_12.txt|  Clever tricks
		|12.1|	Replace a word
		|12.2|	Change "Last, First" to "First Last"
		|12.3|	Sort a list
		|12.4|	Reverse line order
		|12.5|	Count words
		|12.6|	Find a man page
		|12.7|	Trim blanks
		|12.8|	Find where a word is used

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
|@ref{usr_12.txt, , usr_12}| 便利な小技
@detailmenu
* 12.1:: 単語を置換する
* 12.2:: "Last, First" を "First Last" に変更する
* 12.3:: リストをソートする
* 12.4:: 行を逆順に並べ替える
* 12.5:: 単語を数える
* 12.6:: マニュアルを引く
* 12.7:: 空白を取り除く
* 12.8:: 単語が使われている場所を検索する
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
==============================================================================
Editing Effectively ~

Subjects that can be read independently.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
上級編

これらの項目は好きな順番で読んでも構いません。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_20.txt|  Typing command-line commands quickly
		|20.1|	Command line editing
		|20.2|	Command line abbreviations
		|20.3|	Command line completion
		|20.4|	Command line history
		|20.5|	Command line window

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
|@ref{usr_20.txt, , usr_20}| コマンドラインを素早く入力する
@detailmenu
* 20.1:: コマンドライン編集
* 20.2:: コマンドライン短縮入力
* 20.3:: コマンドライン補完
* 20.4:: コマンドライン履歴
* 20.5:: コマンドラインウィンドウ
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_21.txt|  Go away and come back
		|21.1|	Suspend and resume
		|21.2|	Executing shell commands
		|21.3|	Remembering information; viminfo
		|21.4|	Sessions
		|21.5|	Views
		|21.6|	Modelines

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
|@ref{usr_21.txt, , usr_21}| 中断と再開
@detailmenu
* 21.1:: サスペンドとレジューム
* 21.2:: シェルコマンドの実行
* 21.3:: viminfo に情報を記録する
* 21.4:: セッション
* 21.5:: ビュー
* 21.6:: モードライン
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_22.txt|  Finding the file to edit
		|22.1|	The file explorer
		|22.2|	The current directory
		|22.3|	Finding a file
		|22.4|	The buffer list

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
|@ref{usr_22.txt, , usr_22}| ファイルを探す
@detailmenu
* 22.1:: ファイルブラウザー
* 22.2:: カレントディレクトリ
* 22.3:: ファイルを探す
* 22.4:: バッファリスト
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_23.txt|  Editing other files
		|23.1|	DOS, Mac and Unix files
		|23.2|	Files on the internet
		|23.3|	Encryption
		|23.4|	Binary files
		|23.5|	Compressed files

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
|@ref{usr_23.txt, , usr_23}| 特殊なファイルを編集する
@detailmenu
* 23.1:: DOS、Mac、Unix形式のファイル
* 23.2:: インターネット上のファイル
* 23.3:: 暗号化
* 23.4:: バイナリファイル
* 23.5:: 圧縮ファイル
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_24.txt|  Inserting quickly
		|24.1|	Making corrections
		|24.2|	Showing matches
		|24.3|	Completion
		|24.4|	Repeating an insert
		|24.5|	Copying from another line
		|24.6|	Inserting a register
		|24.7|	Abbreviations
		|24.8|	Entering special characters
		|24.9|	Digraphs
		|24.10|	Normal mode commands

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
|@ref{usr_24.txt, , usr_24}| 素早く入力する
@detailmenu
* 24.1:: 修正する
* 24.2:: 対応する括弧を表示する
* 24.3:: 補完
* 24.4:: 挿入を繰り返す
* 24.5:: 隣の行からコピーする
* 24.6:: レジスタを挿入する
* 24.7:: 短縮形 (Abbreviations)
* 24.8:: 特殊な文字を入力する
* 24.9:: ダイグラフ (Digraph)
* 24.10:: ノーマルモードコマンド
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_25.txt|  Editing formatted text
		|25.1|	Breaking lines
		|25.2|	Aligning text
		|25.3|	Indents and tabs
		|25.4|	Dealing with long lines
		|25.5|	Editing tables

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
|@ref{usr_25.txt, , usr_25}| テキストの整形
@detailmenu
* 25.1:: 行を改行する
* 25.2:: テキストの位置揃え
* 25.3:: インデントとタブ
* 25.4:: 長い行の扱い
* 25.5:: 表の編集
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_26.txt|  Repeating
		|26.1|	Repeating with Visual mode
		|26.2|	Add and subtract
		|26.3|	Making a change in many files
		|26.4|	Using Vim from a shell script

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
|@ref{usr_26.txt, , usr_26}| 繰り返し
@detailmenu
* 26.1:: ビジュアルモードを使って繰り返す
* 26.2:: 加算と減算
* 26.3:: 複数のファイルを変更する
* 26.4:: シェルスクリプトから Vim を使う
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_27.txt|  Search commands and patterns
		|27.1|	Ignoring case
		|27.2|	Wrapping around the file end
		|27.3|	Offsets
		|27.4|	Matching multiple times
		|27.5|	Alternatives
		|27.6|	Character ranges
		|27.7|	Character classes
		|27.8|	Matching a line break
		|27.9|	Examples

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
|@ref{usr_27.txt, , usr_27}| 検索コマンドと正規表現
@detailmenu
* 27.1:: 大文字と小文字を区別しない
* 27.2:: ファイルの端で折り返す
* 27.3:: オフセット
* 27.4:: 繰り返しマッチ
* 27.5:: 選択肢
* 27.6:: 文字範囲
* 27.7:: 文字クラス
* 27.8:: 改行記号にマッチ
* 27.9:: 例
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_28.txt|  Folding
		|28.1|	What is folding?
		|28.2|	Manual folding
		|28.3|	Working with folds
		|28.4|	Saving and restoring folds
		|28.5|	Folding by indent
		|28.6|	Folding with markers
		|28.7|	Folding by syntax
		|28.8|	Folding by expression
		|28.9|	Folding unchanged lines
		|28.10|	Which fold method to use?

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
|@ref{usr_28.txt, , usr_28}| 折り畳み
@detailmenu
* 28.1:: 折り畳みとは
* 28.2:: 手動で折り畳む
* 28.3:: 折り畳みを使って作業する
* 28.4:: 折り畳みの保存と復元
* 28.5:: インデントで折り畳む
* 28.6:: マーカーで折り畳む
* 28.7:: 構文で折り畳む
* 28.8:: スクリプトで折り畳む
* 28.9:: 変更のない行を折り畳む
* 28.10:: どれを使えばいいの？
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_29.txt|  Moving through programs
		|29.1|	Using tags
		|29.2|	The preview window
		|29.3|	Moving through a program
		|29.4|	Finding global identifiers
		|29.5|	Finding local identifiers

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
|@ref{usr_29.txt, , usr_29}| プログラムの中を移動する
@detailmenu
* 29.1:: タグを使う
* 29.2:: プレビューウィンドウ
* 29.3:: プログラムの中を移動する
* 29.4:: グローバル識別子を検索する
* 29.5:: ローカル識別子を検索する
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_30.txt|  Editing programs
		|30.1|	Compiling
		|30.2|	Indenting C files
		|30.3|	Automatic indenting
		|30.4|	Other indenting
		|30.5|	Tabs and spaces
		|30.6|	Formatting comments

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
|@ref{usr_30.txt, , usr_30}| プログラムの編集
@detailmenu
* 30.1:: コンパイル
* 30.2:: C 言語系インデント
* 30.3:: インデント設定の自動化
* 30.4:: その他のインデント
* 30.5:: タブとスペース
* 30.6:: コメントの整形
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_31.txt|  Exploiting the GUI
		|31.1|	The file browser
		|31.2|	Confirmation
		|31.3|	Menu shortcuts
		|31.4|	Vim window position and size
		|31.5|	Various

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
|@ref{usr_31.txt, , usr_31}| GUI を活用する
@detailmenu
* 31.1:: ファイルブラウザー
* 31.2:: 操作確認
* 31.3:: メニューのショートカット
* 31.4:: Vim ウィンドウの位置とサイズ
* 31.5:: その他
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_32.txt|  The undo tree
		|32.1|	Undo up to a file write
		|32.2|	Numbering changes
		|32.3|	Jumping around the tree
		|32.4|	Time travelling

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
|@ref{usr_32.txt, , usr_32}| undo ツリー
@detailmenu
* 32.1:: ファイル保存時への undo
* 32.2:: 変更の番号付け
* 32.3:: ツリーを飛び回る
* 32.4:: タイムトラベル
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
==============================================================================
Tuning Vim ~

Make Vim work as you like it.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
カスタマイズ

Vim の動作を好きなように変更できます。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_40.txt|  Make new commands
		|40.1|	Key mapping
		|40.2|	Defining command-line commands
		|40.3|	Autocommands

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
|@ref{usr_40.txt, , usr_40}| 新しいコマンドを作る
@detailmenu
* 40.1:: キーマッピング
* 40.2:: コマンドラインコマンドを定義する
* 40.3:: 自動コマンド
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_41.txt|  Write a Vim script
		|41.1|	Introduction
		|41.2|	Variables
		|41.3|	Expressions
		|41.4|	Conditionals
		|41.5|	Executing an expression
		|41.6|	Using functions
		|41.7|	Defining a function
		|41.8|	Lists and Dictionaries
		|41.9|	Exceptions
		|41.10|	Various remarks
		|41.11|	Writing a plugin
		|41.12|	Writing a filetype plugin
		|41.13|	Writing a compiler plugin
		|41.14|	Writing a plugin that loads quickly
		|41.15|	Writing library scripts
		|41.16|	Distributing Vim scripts

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
|@ref{usr_41.txt, , usr_41}| Vim script 書法
@detailmenu
* 41.1:: はじめに
* 41.2:: 変数
* 41.3:: 式
* 41.4:: 条件式
* 41.5:: 式を実行する
* 41.6:: 関数を使う
* 41.7:: 関数を定義する
* 41.8:: リストと辞書
* 41.9:: 例外
* 41.10:: 注意事項
* 41.11:: プラグインを書く
* 41.12:: ファイルタイププラグインを書く
* 41.13:: コンパイラプラグインを書く
* 41.14:: プラグインを書く (高速ロード版)
* 41.15:: ライブラリスクリプトを書く
* 41.16:: Vim script を配布する
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_42.txt|  Add new menus
		|42.1|	Introduction
		|42.2|	Menu commands
		|42.3|	Various
		|42.4|	Toolbar and popup menus

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
|@ref{usr_42.txt, , usr_42}| 新しいメニューの追加
@detailmenu
* 42.1:: はじめに
* 42.2:: メニューコマンド
* 42.3:: その他いろいろ
* 42.4:: ツールバーとポップアップメニュー
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_43.txt|  Using filetypes
		|43.1|	Plugins for a filetype
		|43.2|	Adding a filetype

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
|@ref{usr_43.txt, , usr_43}| ファイルタイプを使う
@detailmenu
* 43.1:: ファイルタイププラグイン
* 43.2:: ファイルタイプを追加する
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_44.txt|  Your own syntax highlighted
		|44.1|	Basic syntax commands
		|44.2|	Keywords
		|44.3|	Matches
		|44.4|	Regions
		|44.5|	Nested items
		|44.6|	Following groups
		|44.7|	Other arguments
		|44.8|	Clusters
		|44.9|	Including another syntax file
		|44.10|	Synchronizing
		|44.11|	Installing a syntax file
		|44.12|	Portable syntax file layout

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
|@ref{usr_44.txt, , usr_44}| 構文ファイルを作成する
@detailmenu
* 44.1:: 基本的な syntax コマンド
* 44.2:: キーワード
* 44.3:: マッチ
* 44.4:: リージョン
* 44.5:: 構文アイテムを入れ子にする
* 44.6:: グループの並び
* 44.7:: その他の引数
* 44.8:: クラスタ
* 44.9:: 他の構文ファイルをインクルードする
* 44.10:: シンクロナイズ
* 44.11:: 構文ファイルをインストールする
* 44.12:: ポータブルな文法定義ファイル
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_45.txt|  Select your language
		|45.1|	Language for Messages
		|45.2|	Language for Menus
		|45.3|	Using another encoding
		|45.4|	Editing files with a different encoding
		|45.5|	Entering language text

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
|@ref{usr_45.txt, , usr_45}| 言語を選択する
@detailmenu
* 45.1:: メッセージの言語
* 45.2:: メニューの言語
* 45.3:: 他のエンコーディングを使う
* 45.4:: 異なるエンコーディングのファイルを編集する
* 45.5:: 言語のテキストを入力する
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
==============================================================================
Making Vim Run ~

Before you can use Vim.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
インストール

インストール方法を説明します。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_90.txt|  Installing Vim
		|90.1|	Unix
		|90.2|	MS-Windows
		|90.3|	Upgrading
		|90.4|	Common installation issues
		|90.5|	Uninstalling Vim

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
|@ref{usr_90.txt, , usr_90}| Vim のインストール
@detailmenu
* 90.1:: Unix
* 90.2:: MS-Windows
* 90.3:: アップグレード
* 90.4:: よくある問題
* 90.5:: アンインストール
@end detailmenu
@end menu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
==============================================================================

Copyright: see |manual-copyright|  vim:tw=78:ts=8:ft=help:norl:
@end ifset
