\input texinfo-ja              @c -*- mode: texinfo; coding: utf-8 -*-
@clear EN
@clear JA
@set JA
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@documentencoding UTF-8
@documentlanguage ja
@setfilename vim_user_manual.info
@settitle Vim User Manual
@syncodeindex vr cp
@syncodeindex fn cp
@finalout
@afourpaper

@titlepage
@title Vim ユーザーマニュアル
@page
@vskip 0pt plus 1filll
@end titlepage
@iftex
@shortcontents
@contents
@end iftex
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@node 目次, マニュアルについて
@top 目次
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
*usr_toc.txt*	For Vim version 8.0.  Last change: 2016 Mar 25

		     VIM USER MANUAL - by Bram Moolenaar

			      Table Of Contents			*user-manual*
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@anchor{usr_toc.txt}
@anchor{user-manual}
@cindex usr_toc.txt
@cindex user-manual
@verbatim
*usr_toc.txt*   For Vim バージョン 8.0.  Last change: 2016 Mar 25

		     VIM USER MANUAL - by Bram Moolenaar

			      目次
@end verbatim
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
==============================================================================
Overview ~

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
@menu
大見出し一覧

@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
Getting Started
|usr_01.txt|  About the manuals
|usr_02.txt|  The first steps in Vim
|usr_03.txt|  Moving around
|usr_04.txt|  Making small changes
|usr_05.txt|  Set your settings
|usr_06.txt|  Using syntax highlighting
|usr_07.txt|  Editing more than one file
|usr_08.txt|  Splitting windows
|usr_09.txt|  Using the GUI
|usr_10.txt|  Making big changes
|usr_11.txt|  Recovering from a crash
|usr_12.txt|  Clever tricks
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
初級編
* 目次::                  usr_toc.txt
* マニュアルについて::    usr_01.txt
* 初めての Vim::          usr_02.txt
* カーソルの移動::        usr_03.txt
* 簡単な編集::            usr_04.txt
* 設定の変更::            usr_05.txt
* 構文強調表示::          usr_06.txt
* 複数のファイルを開く::  usr_07.txt
* ウィンドウの分割::      usr_08.txt
* GUI を使う::            usr_09.txt
* 大規模な編集::          usr_10.txt
* クラッシュからの復帰::  usr_11.txt
* 便利な小技::            usr_12.txt
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
Editing Effectively
|usr_20.txt|  Typing command-line commands quickly
|usr_21.txt|  Go away and come back
|usr_22.txt|  Finding the file to edit
|usr_23.txt|  Editing other files
|usr_24.txt|  Inserting quickly
|usr_25.txt|  Editing formatted text
|usr_26.txt|  Repeating
|usr_27.txt|  Search commands and patterns
|usr_28.txt|  Folding
|usr_29.txt|  Moving through programs
|usr_30.txt|  Editing programs
|usr_31.txt|  Exploiting the GUI
|usr_32.txt|  The undo tree

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
上級編
* コマンドラインを素早く入力する:: usr_20.txt
* 中断と再開::                     usr_21.txt
* ファイルを探す::                 usr_22.txt
* 特殊なファイルを編集する::       usr_23.txt
* 素早く入力する::                 usr_24.txt
* テキストの整形::                 usr_25.txt
* 繰り返し::                       usr_26.txt
* 検索コマンドと正規表現::         usr_27.txt
* 折り畳み::                       usr_28.txt
* プログラムの中を移動する::       usr_29.txt
* プログラムの編集::               usr_30.txt
* GUI を活用する::                 usr_31.txt
* undo ツリー::                    usr_32.txt
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Tuning Vim
|usr_40.txt|  Make new commands
|usr_41.txt|  Write a Vim script
|usr_42.txt|  Add new menus
|usr_43.txt|  Using filetypes
|usr_44.txt|  Your own syntax highlighted
|usr_45.txt|  Select your language
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
カスタマイズ
@c * 新しいコマンドを作る::     usr_40.txt
@c * Vim script 書法::          usr_41.txt
@c * 新しいメニューを追加する:: usr_42.txt
@c * ファイルタイプを使う::     usr_43.txt
@c * 構文ファイルを作成する::   usr_44.txt
@c * 言語を選択する::           usr_45.txt
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
Making Vim Run
|usr_90.txt|  Installing Vim
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
インストール
@c * Vim のインストール::     usr_90.txt
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------


@ifset EN
Reference manual
|reference_toc|     More detailed information for all commands
@end ifset

@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
リファレンスマニュアル
@c * 全コマンドの詳細情報::  reference_toc.txt
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset JA  @c ----------- v -----------  JA  ----------- v -----------

インデックス
* Index::
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ifset EN
The user manual is available as a single, ready to print HTML and PDF file
here:
	http://vimdoc.sf.net
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------

シングルファイルで印刷に適した HTML 形式と PDF 形式の
ユーザーマニュアルが用意されています:
    @url{http://vimdoc.sf.net}
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
==============================================================================
Getting Started ~

Read this from start to end to learn the essential commands.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
初級編

最初から順番に読んで基本的なコマンドを学びましょう。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_01.txt|  About the manuals
		|01.1|	Two manuals
		|01.2|	Vim installed
		|01.3|	Using the Vim tutor
		|01.4|	Copyright
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
マニュアルについて (usr_01)
@detailmenu
* 2 つのマニュアル::
* Vim の準備::
* チュートリアル::
* 著作権 (Copyright)::
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_02.txt|  The first steps in Vim
		|02.1|	Running Vim for the First Time
		|02.2|	Inserting text
		|02.3|	Moving around
		|02.4|	Deleting characters
		|02.5|	Undo and Redo
		|02.6|	Other editing commands
		|02.7|	Getting out
		|02.8|	Finding help
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
初めての Vim (usr_02)
@detailmenu
* Vim の起動方法::
* 文字の挿入::
* カーソル移動::
* 文字の削除::
* undo (取り消し) と redo (やり直し)::
* 他の編集コマンド::
* Vim の終了::
* ヘルプの引き方::
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_03.txt|  Moving around
		|03.1|	Word movement
		|03.2|	Moving to the start or end of a line
		|03.3|	Moving to a character
		|03.4|	Matching a paren
		|03.5|	Moving to a specific line
		|03.6|	Telling where you are
		|03.7|	Scrolling around
		|03.8|	Simple searches
		|03.9|	Simple search patterns
		|03.10|	Using marks
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
カーソルの移動 (usr_03)
@detailmenu
* 単語ごとの移動::
* 行頭、行末への移動::
* 文字への移動::
* カッコの対応::
* 特定の行への移動::
* 現在の場所を表示::
* スクロール::
* 簡単な検索::
* 簡単なパターン検索::
* マークの使用::
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_04.txt|  Making small changes
		|04.1|	Operators and motions
		|04.2|	Changing text
		|04.3|	Repeating a change
		|04.4|	Visual mode
		|04.5|	Moving text
		|04.6|	Copying text
		|04.7|	Using the clipboard
		|04.8|	Text objects
		|04.9|	Replace mode
		|04.10|	Conclusion

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
簡単な編集 (usr_04)
@detailmenu
* オペレータとモーション::
* テキストの変更::
* 変更の繰り返し::
* ビジュアルモード::
* テキストの移動::
* テキストのコピー::
* クリップボード::
* テキストオブジェクト::
* 置換モード::
* 終わりに::
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_05.txt|  Set your settings
		|05.1|	The vimrc file
		|05.2|	The example vimrc file explained
		|05.3|	Simple mappings
		|05.4|	Adding a package
		|05.5|	Adding a plugin
		|05.6|	Adding a help file
		|05.7|	The option window
		|05.8|	Often used options

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
設定の変更 (usr_05)
@detailmenu
* vimrc ファイル::
* 見本 vimrc ファイルの解説::
* 簡単なマップ::
* パッケージの追加::
* プラグインの追加::
* ヘルプファイルの追加::
* オプションウィンドウ::
* よく使うオプション::
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_06.txt|  Using syntax highlighting
		|06.1|	Switching it on
		|06.2|	No or wrong colors?
		|06.3|	Different colors
		|06.4|	With colors or without colors
		|06.5|	Printing with colors
		|06.6|	Further reading

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
構文強調表示 (usr_06)
@detailmenu
* 構文強調表示を有効にする::
* 色がつかない？変な色になる？::
* 色を変える::
* カラーを使う？使わない？::
* カラー印刷::
* 詳しい情報::
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_07.txt|  Editing more than one file
		|07.1|	Edit another file
		|07.2|	A list of files
		|07.3|	Jumping from file to file
		|07.4|	Backup files
		|07.5|	Copy text between files
		|07.6|	Viewing a file
		|07.7|	Changing the file name

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
複数のファイルを開く (usr_07)
@detailmenu
* 他のファイルを開く::
* ファイルのリスト::
* 他のファイルにジャンプする::
* バックアップファイル::
* 他のファイルにテキストをコピーする::
* 読み込み専用モード::
* ファイル名の変更::
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_08.txt|  Splitting windows
		|08.1|	Split a window
		|08.2|	Split a window on another file
		|08.3|	Window size
		|08.4|	Vertical splits
		|08.5|	Moving windows
		|08.6|	Commands for all windows
		|08.7|	Viewing differences with vimdiff
		|08.8|	Various

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
ウィンドウの分割 (usr_08)
@detailmenu
* ウィンドウの分割::
* ウィンドウを分割してファイルを開く::
* ウィンドウのサイズ::
* 縦分割::
* ウィンドウの移動::
* 全ウィンドウを対象とするコマンド::
* vimdiff で差分を表示する::
* その他::
* タブページ::
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_09.txt|  Using the GUI
		|09.1|	Parts of the GUI
		|09.2|	Using the mouse
		|09.3|	The clipboard
		|09.4|	Select mode

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
GUI を使う (usr_09)
@detailmenu
* GUI の部品::
* GUI でマウスを使う::
* GUI でクリップボード::
* GUI で選択モード::
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_10.txt|  Making big changes
		|10.1|	Record and playback commands
		|10.2|	Substitution
		|10.3|	Command ranges
		|10.4|	The global command
		|10.5|	Visual block mode
		|10.6|	Reading and writing part of a file
		|10.7|	Formatting text
		|10.8|	Changing case
		|10.9|	Using an external program

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
大規模な編集 (usr_10)
@detailmenu
* 操作の記録と再実行::
* 置換::
* コマンドの範囲指定::
* global コマンド::
* 矩形選択::
* ファイルの一部の保存と読み込み::
* テキストの整形.::
* 大文字/小文字の変換::
* 外部プログラムを使う::
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_11.txt|  Recovering from a crash
		|11.1|	Basic recovery
		|11.2|	Where is the swap file?
		|11.3|	Crashed or not?
		|11.4|	Further reading

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
クラッシュからの復帰 (usr_11)
@detailmenu
* リカバリの基本::
* スワップファイルはどこにある？::
* クラッシュした？::
* さらなる情報::
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_12.txt|  Clever tricks
		|12.1|	Replace a word
		|12.2|	Change "Last, First" to "First Last"
		|12.3|	Sort a list
		|12.4|	Reverse line order
		|12.5|	Count words
		|12.6|	Find a man page
		|12.7|	Trim blanks
		|12.8|	Find where a word is used

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
便利な小技 (usr_12)
@detailmenu
* 単語を置換する::
* "Last，First" を "First Last" に変更する::
* リストをソートする::
* 行を逆順に並べ替える::
* 単語を数える::
* マニュアルを引く::
* 空白を取り除く::
* 単語が使われている場所を検索する::
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
==============================================================================
Editing Effectively ~

Subjects that can be read independently.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
上級編

これらの項目は好きな順番で読んでも構いません。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_20.txt|  Typing command-line commands quickly
		|20.1|	Command line editing
		|20.2|	Command line abbreviations
		|20.3|	Command line completion
		|20.4|	Command line history
		|20.5|	Command line window

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
コマンドラインを素早く入力する (usr_20)
@detailmenu
* コマンドライン編集::
* コマンドライン短縮入力::
* コマンドライン補完::
* コマンドライン履歴::
* コマンドラインウィンドウ::
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_21.txt|  Go away and come back
		|21.1|	Suspend and resume
		|21.2|	Executing shell commands
		|21.3|	Remembering information; viminfo
		|21.4|	Sessions
		|21.5|	Views
		|21.6|	Modelines

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
中断と再開 (usr_21)
@detailmenu
* サスペンドとレジューム::
* シェルコマンドの実行::
* viminfo に情報を記録する::
* セッション::
* ビュー::
* モードライン::
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_22.txt|  Finding the file to edit
		|22.1|	The file explorer
		|22.2|	The current directory
		|22.3|	Finding a file
		|22.4|	The buffer list

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
ファイルを探す (usr_22)
@detailmenu
* ファイルブラウザー::
* カレントディレクトリ::
* ファイルを探す.::
* バッファリスト::
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_23.txt|  Editing other files
		|23.1|	DOS, Mac and Unix files
		|23.2|	Files on the internet
		|23.3|	Encryption
		|23.4|	Binary files
		|23.5|	Compressed files

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
特殊なファイルを編集する (usr_23)
@detailmenu
* DOS、Mac、Unix形式のファイル::
* インターネット上のファイル::
* 暗号化::
* バイナリファイル::
* 圧縮ファイル::
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_24.txt|  Inserting quickly
		|24.1|	Making corrections
		|24.2|	Showing matches
		|24.3|	Completion
		|24.4|	Repeating an insert
		|24.5|	Copying from another line
		|24.6|	Inserting a register
		|24.7|	Abbreviations
		|24.8|	Entering special characters
		|24.9|	Digraphs
		|24.10|	Normal mode commands

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
素早く入力する (usr_24)
@detailmenu
* 修正する::
* 対応する括弧を表示する::
* 補完::
* 挿入を繰り返す::
* 隣の行からコピーする::
* レジスタを挿入する::
* 短縮形 (Abbreviations)::
* 特殊な文字を入力する::
* ダイグラフ (Digraph)::
* ノーマルモードコマンド::
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_25.txt|  Editing formatted text
		|25.1|	Breaking lines
		|25.2|	Aligning text
		|25.3|	Indents and tabs
		|25.4|	Dealing with long lines
		|25.5|	Editing tables

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
テキストの整形 (usr_25)
@detailmenu
* 行を改行する::
* テキストの位置揃え::
* インデントとタブ::
* 長い行の扱い::
* 表の編集::
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_26.txt|  Repeating
		|26.1|	Repeating with Visual mode
		|26.2|	Add and subtract
		|26.3|	Making a change in many files
		|26.4|	Using Vim from a shell script

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
繰り返し (usr_26)
@detailmenu
* ビジュアルモードを使って繰り返す::
* 加算と減算::
* 複数のファイルを変更する::
* シェルスクリプトから Vim を使う::
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_27.txt|  Search commands and patterns
		|27.1|	Ignoring case
		|27.2|	Wrapping around the file end
		|27.3|	Offsets
		|27.4|	Matching multiple times
		|27.5|	Alternatives
		|27.6|	Character ranges
		|27.7|	Character classes
		|27.8|	Matching a line break
		|27.9|	Examples

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
検索コマンドと正規表現 (usr_27)
@detailmenu
* 大文字と小文字を区別しない::
* ファイルの端で折り返す::
* オフセット::
* 繰り返しマッチ::
* 選択肢::
* 文字範囲::
* 文字クラス::
* 改行記号にマッチ::
* 例::
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_28.txt|  Folding
		|28.1|	What is folding?
		|28.2|	Manual folding
		|28.3|	Working with folds
		|28.4|	Saving and restoring folds
		|28.5|	Folding by indent
		|28.6|	Folding with markers
		|28.7|	Folding by syntax
		|28.8|	Folding by expression
		|28.9|	Folding unchanged lines
		|28.10|	Which fold method to use?

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
折り畳み (usr_28)
@detailmenu
* 折り畳みとは::
* 手動で折り畳む::
* 折り畳みを使って作業する::
* 折り畳みの保存と復元::
* インデントで折り畳む::
* マーカーで折り畳む::
* 構文で折り畳む::
* スクリプトで折り畳む::
* 変更のない行を折り畳む::
* どれを使えばいいの？::
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_29.txt|  Moving through programs
		|29.1|	Using tags
		|29.2|	The preview window
		|29.3|	Moving through a program
		|29.4|	Finding global identifiers
		|29.5|	Finding local identifiers

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
プログラムの中を移動する (usr_29)
@detailmenu
* タグを使う::
* プレビューウィンドウ::
* プログラムの中を移動する.::
* グローバル識別子を検索する::
* ローカル識別子を検索する::
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_30.txt|  Editing programs
		|30.1|	Compiling
		|30.2|	Indenting C files
		|30.3|	Automatic indenting
		|30.4|	Other indenting
		|30.5|	Tabs and spaces
		|30.6|	Formatting comments

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
プログラムの編集 (usr_30)
@detailmenu
* コンパイル::
* C 言語系インデント::
* インデント設定の自動化::
* その他のインデント::
* タブとスペース::
* コメントの整形::
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_31.txt|  Exploiting the GUI
		|31.1|	The file browser
		|31.2|	Confirmation
		|31.3|	Menu shortcuts
		|31.4|	Vim window position and size
		|31.5|	Various

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
GUI を活用する (usr_31)
@detailmenu
* ファイルブラウザー.::
* 操作確認::
* メニューのショートカット::
* Vim ウィンドウの位置とサイズ::
* その他.::
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_32.txt|  The undo tree
		|32.1|	Undo up to a file write
		|32.2|	Numbering changes
		|32.3|	Jumping around the tree
		|32.4|	Time travelling

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
undo ツリー (usr_32)
@detailmenu
* ファイル保存時への undo::
* 変更の番号付け::
* ツリーを飛び回る::
* タイムトラベル::
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------
@ignore
@ifset EN
==============================================================================
Tuning Vim ~

Make Vim work as you like it.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
カスタマイズ

Vim の動作を好きなように変更できます。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_40.txt|  Make new commands
		|40.1|	Key mapping
		|40.2|	Defining command-line commands
		|40.3|	Autocommands

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
新しいコマンドを作る (usr_40)
@detailmenu
* キーマッピング::
* コマンドラインコマンドを定義する::
* 自動コマンド::
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_41.txt|  Write a Vim script
		|41.1|	Introduction
		|41.2|	Variables
		|41.3|	Expressions
		|41.4|	Conditionals
		|41.5|	Executing an expression
		|41.6|	Using functions
		|41.7|	Defining a function
		|41.8|	Lists and Dictionaries
		|41.9|	Exceptions
		|41.10|	Various remarks
		|41.11|	Writing a plugin
		|41.12|	Writing a filetype plugin
		|41.13|	Writing a compiler plugin
		|41.14|	Writing a plugin that loads quickly
		|41.15|	Writing library scripts
		|41.16|	Distributing Vim scripts

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
Vim script 書法 (usr_41)
@detailmenu
* はじめに::
* 変数::
* 式::
* 条件式::
* 式を実行する::
* 関数を使う::
* 関数を定義する::
* リストと辞書::
* 例外::
* 注意事項::
* プラグインを書く::
* ファイルタイププラグインを書く::
* コンパイラプラグインを書く::
* プラグインを書く (高速ロード版)::
* ライブラリスクリプトを書く::
* Vim script を配布する::

@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_42.txt|  Add new menus
		|42.1|	Introduction
		|42.2|	Menu commands
		|42.3|	Various
		|42.4|	Toolbar and popup menus

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
新しいメニューの追加 (usr_42)
@detailmenu
* はじめに::
* メニューコマンド::
* その他いろいろ::
* ツールバーとポップアップメニュー::
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_43.txt|  Using filetypes
		|43.1|	Plugins for a filetype
		|43.2|	Adding a filetype

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
ファイルタイプを使う (usr_43)
@detailmenu
* ファイルタイププラグイン::
* ファイルタイプを追加する::
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_44.txt|  Your own syntax highlighted
		|44.1|	Basic syntax commands
		|44.2|	Keywords
		|44.3|	Matches
		|44.4|	Regions
		|44.5|	Nested items
		|44.6|	Following groups
		|44.7|	Other arguments
		|44.8|	Clusters
		|44.9|	Including another syntax file
		|44.10|	Synchronizing
		|44.11|	Installing a syntax file
		|44.12|	Portable syntax file layout

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
構文ファイルを作成する (usr_44)
@detailmenu
* 基本的な syntax コマンド::
* キーワード::
* マッチ::
* リージョン::
* 構文アイテムを入れ子にする::
* グループの並び::
* その他の引数::
* クラスタ::
* 他の構文ファイルをインクルードする::
* シンクロナイズ::
* 構文ファイルをインストールする::
* ポータブルな文法定義ファイル::
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_45.txt|  Select your language
		|45.1|	Language for Messages
		|45.2|	Language for Menus
		|45.3|	Using another encoding
		|45.4|	Editing files with a different encoding
		|45.5|	Entering language text

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
言語を選択する (usr_45)
@detailmenu
* メッセージの言語::
* メニューの言語::
* 他のエンコーディングを使う::
* 異なるエンコーディングのファイルを編集する::
* 言語のテキストを入力する::
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
==============================================================================
Making Vim Run ~

Before you can use Vim.
@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
インストール

インストール方法を説明します。
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
|usr_90.txt|  Installing Vim
		|90.1|	Unix
		|90.2|	MS-Windows
		|90.3|	Upgrading
		|90.4|	Common installation issues
		|90.5|	Uninstalling Vim

@end ifset
@ifset JA  @c ----------- v -----------  JA  ----------- v -----------
Vim のインストール (usr_90)
@detailmenu
* WUnix::
* MS-Windows::
* アップグレード::
* よくある問題::
* アンインストール::
@end detailmenu
@end ifset @c ----------- ^ -----------  JA  ----------- ^ -----------

@ifset EN
==============================================================================

Copyright: see |manual-copyright|  vim:tw=78:ts=8:ft=help:norl:
@end ifset
@end ignore
@end menu

@include usr_01.texi
@include usr_02.texi
@include usr_03.texi
@include usr_04.texi
@include usr_05.texi
@include usr_06.texi
@include usr_07.texi
@include usr_08.texi
@include usr_09.texi
@include usr_10.texi
@include usr_11.texi
@include usr_12.texi
@include usr_20.texi
@include usr_21.texi
@include usr_22.texi
@include usr_23.texi
@include usr_24.texi
@include usr_25.texi
@include usr_26.texi
@include usr_27.texi
@include usr_28.texi
@include usr_29.texi
@include usr_30.texi
@include usr_31.texi
@include usr_32.texi
@c @include usr_40.texi
@c @include usr_41.texi
@c @include usr_42.texi
@c @include usr_43.texi
@c @include usr_44.texi
@c @include usr_45.texi
@c @include usr_90.texi

@node Index
@unnumbered Index

@printindex cp

@bye
